### ISSUE TITLE
replace_str_substrs

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#11]
Create \"replace_str_substrs()\" under beartype._util.text.utiltextmunge and refactor *ALL* calls to str.replace() throughout the codebase to call the aforementioned function.

The function signature should resemble the following:

def replace_str_substrs(text: str, substr: str) -> str:

The body of the function should do the following:
* If the passed string does *NOT* contain at least one instance of the passed substring, raise an exception.
* Else, return: str.replace(text, substr)

Why? Because the builtin str.replace() method performs *NO* such validation,
inviting non-human-readable exceptions when we inevitably muck things up.

**Comment by Heliotrop3** [comment]
@leycec , if the replace_str_substrs is meant to wrap str.replace, then wouldn't we also need a param for what to replace the substr with? 
The return statement of the below function throws a TypeError because we didn't supply the String class with what we want to replace the substring with.

    def replace_str_substrs(text: str, substr: str) -> str:
        assert isinstance(text, str), '{!r} not string.'.format(text)
        assert isinstance(substr, str), '{!r} not string.'.format(substr)

        # Catch cases where str.replace will match on
        if substr not in text:
            raise ValueError('{!r} not in {!r}'.format(substr, text))
        return str.replace(text, substr)  # 

Evidently, satiating the String's gluttony requires feeding it the third parameter. 

    def replace_str_substrs(text: str, substr: str, new: str) -> str:
        assert isinstance(new, str), '{!r} not string.'.format(new) # Make sure the new param won't cause trouble
        ... 
        return str.replace(text, substr, new) # Call str.replace

**Comment by leycec** [comment]
`</sigh>`

You're absolutely right... *of course.* You caught my discretely hidden `FIXME:` comment out on a blatant bug and then went to the trouble of fixing that bug, which makes you a wonderful asset and just the sort of `FIXME:` sleuth we need around here.

I could technically close this out by just revising the `FIXME:` and calling it a "Job well done, chaps!", but that would be sad and make me feel bad. You went to all this trouble. So, I'd might as well finally resolve this `FIXME:` once and for all. I will, of course, use your helpfully supplied `replace_str_substrs()` function as a base.

**Let's end this.** :rage1:

**Comment by leycec** [comment]
**Boom!** Terminated with extreme prejudice. Specifically:

* `replace_str_substrs()` is now a thing in the private `beartype._util.text.utiltextmunge` submodule, shamelessly plagiarized wholesale from your above contribution. Plagiarism: *feels good, man.*
* All previously unsafe calls to the `str.replace()` method – which is *all* of them except one, interestingly – now call the safe `replace_str_substrs()` function instead.

You made this happen, @Heliotrop3. I heartily congratulate your pedantry and hope for similar pedantry in the future. Find all our bugs! Solve them for us! Vast riches and voluminous thanks shall await, for you are the ultimate Beartyper.

Also, I love your username. I wish we could grow Peruvian heliotropes here, but... you know. That whole USDA Hardiness Zone 3 thing (*think Arctic circle, stupefied penguins, and bare-chested polar bears wrestling on our front lawn*) puts a damper on the import South American perennial landscaping.
