### ISSUE TITLE
mypy 0.940: Condition can't be inferred, unable to merge overloads  [misc]

### ISSUE THREAD

**Issue by twoertwein** [beartype/beartype#113]
Mypy 0.940 with the beartype 0.10.3 triggers this mypy error (might be a mypy 0.940 issue  - it just released):

```py
from beartype import beartype

@beartype
def test(x: int) -> int:
    return x
```

> /home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-sgDWaTGJ-py3.10/lib/python3.10/site-packages/beartype/_decor/main.py:294: error: Condition can't be inferred, unable to merge overloads  [misc]

**Comment by twoertwein** [comment]
Sorry, duplicate of #112

**Comment by leycec** [comment]
@harens, et al.: We have :rocket: for `beartype 0.10.4`:

```bash
$ pip3 install --upgrade beartype
```

If anyone needs me, I'll be stuffing esoteric imported media from Japan into my head all evening.

![like this](https://static.wikia.nocookie.net/berserk/images/d/dc/Manga_E330_Chitch_Expended.png/revision/latest/scale-to-width-down/792?cb=20190409075253)
<sup>it do be like this</sup>
