### ISSUE TITLE
Improving KeyPool's Saftey

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#13]
Hello again! Back with another question after more exploration of the cave. I was nosing around utilcachepool.py and found the following:

>FIXME: Consider improving the safety of the "KeyPool" class. The current implementation is overly naive. For both simplicity and efficiency, we avoid explicitly validating various conditions on passed objects. For example, the object passed to the  KeyPool.release() method is assumed -- but *NOT* validated -- to have been previously returned from a call to the KeyPool.acquire() method. 
If this ever becomes a demonstrable issue, validation can be implemented with only mild space and time costs as follows:
>* Define a new "KeyPool._pool_item_ids_acquired" set instance variable, containing the object IDs of all pool items returned by prior calls to the acquire() method that have yet to be passed to the release() method.
>* Define a new "KeyPool._pool_item_ids_released" set instance variable, containing the object IDs of all pool items passed to prior calls to the release() method that have yet to be returned from the acquire() method.
>* Refactor the acquire() method to (in order):
> * Validate that the pool item to be returned is in the "_pool_item_ids_released" set but *NOT* the "_pool_item_ids_acquired" set.
>* Remove this item from the "_pool_item_ids_released" set.
>* Add this item from the "_pool_item_ids_acquired" set.
>* Note that the above procedure fails to account for the edge case of newly created pool items, which should reside in *NEITHER* set. </sigh>.
>* Refactor the release() method to (in order):
>* Validate that the passed pool item is in the "_pool_item_ids_acquired" set but *NOT* the "_pool_item_ids_released" set.
>* Remove this item from the "_pool_item_ids_acquired" set.
>* Add this item from the "_pool_item_ids_released" set.

I think I have a solution to the problem, however, while I've been poking around the pool folder I'm still a little fuzzy on a few things. Thus we find ourselves here - in the intermediate of reviewing parts of the larger code base and understanding [what I need to do to test](https://github.com/beartype/beartype#developers) , I figure now is also a good time to get feedback on my understanding of the problem.

If I had to describe the FIXME in one sentence it would be: "Each KeyPool needs to track whether an ID is acquired or released." If this is the case, has storing the mapping of ID to a boolean value been considered? In short, the below implementation enables tracking acquisition state in a clear and concise manner while maintaining O(1).

```
_pool_item_ids_acquired : dict
        Dictionary mapping from **arbitrary keys** (i.e, hashable objects) to
        a boolean indicating whether the hashable object is currently acquired.

KeyPool._pool_item_ids_acquired = defaultdict(bool)
```
```
 def acquire(self, key: 'HashableType' = None) -> object:
        '''
        Docstring
        '''
        # Verify Object is available - returns true if key maps to False
        if not self._pool_item_ids_acquired.get(key, False):
            self._pool_item_ids_acquired[key] = True
            # Do the thread safe things
        else: 
            # It's already acquired and we don't do the thread safe things

    def release(self, item: object, key: 'HashableType' = None) -> None:
        '''
        Docstring
        '''

        # Validate the key is eligible for release; default unknown keys to
        # False to avoid a scene
        if not self._pool_item_ids_acquired.get(key, False): 
            raise NotImplementedError()
        
        self._pool_item_ids_acquired[key] = False
        # Do things in the thread safe way of the Pythonista
```
Note: the `dict.get(...)` method returns None by default if the key doesn't exist - None evaluates the same as False in a conditional. The default method was changed for readability.

Let me know if this idea is feasible or if there exists a critical error - In the meantime, I'll be reviewing the graciously provided [developer manual](https://github.com/beartype/beartype#developers) and poking around the cave some more.

-Heliotrop3 🖖

**Comment by leycec** [comment]
You're always two `FIXME:` steps ahead like an elusive praying mantis in the mists hunting that most delicious of insectile prey: *my awful, shameful bugs.*

Unsurprisingly, you're right again. This is why I have the red imprint of a facepalm permanently engraved on my forehead. Mapping `id()` to `bool` is the obvious approach, which was not obvious to me, because I am denser than lead.

That said, this...

```
def acquire(self, key: 'HashableType' = None) -> object:
        '''
        Docstring
        '''
        # Verify Object is available - returns true if key maps to False
        if not self._pool_item_ids_acquired.get(key, False):
            self._pool_item_ids_acquired[key] = True
            # Do the thread safe things
        else: 
            # It's already acquired and we don't do the thread safe things
```

...doesn't *quite* read right. Admittedly, I'm half-blind.

The current implementation intentionally supports repeated calls to the `acquire()` method passed the same `key`. Subsequent calls do *not* silently reduce to noops; instead, each such call acquires a new object from the end of the `list` cached at that `key`, because each `key` internally maps to a `list` rather than a single object via the deadly black magic of line 124:

```
        self._key_to_pool = defaultdict(list)
```

Rather than the above, we might instead prefer to retain the existing approach while additionally recording acquired object IDs for later lookup in the `release()` method:

```
    def acquire(self, key: 'HashableType' = None) -> object:

        # In a thread-safe manner...
        with self._thread_lock:
            # List associated with this key.
            #
            # If this is the first access of this key, this "defaultdict"
            # implicitly creates a new list and associates this key with that
            # list; else, this is the list previously associated with this key.
            #
            # Note that this statement implicitly raises a "TypeError"
            # exception if this key is unhashable, which is certainly more
            # efficient than our explicitly validating this constraint.
            pool = self._key_to_pool[key]

            # Arbitrary object associated with this key, defined as either...
            pool_item = (
                # A new object associated with this key...
                self._pool_item_maker(key)
                # If the list associated with this key is empty (i.e., this
                # method has been called more frequently than the corresponding
                # release() method for this key);
                if not pool
                # Else, the list associated with this key is non-empty (i.e.,
                # this method has been called less frequently than the
                # corresponding release() method for this key). In this case,
                # pop (i.e., remove) and return the last item from this list.
                else pool.pop()
            )

            # Record this object as having been acquired.
            self._pool_item_ids_acquired[id(pool_item)] = True

            # Return this object.
            return pool_item
```

Your `release()` improvements, however, look spot on – with the caveat that we again want to record acquisitions by object `id()` rather than `key` values. Also, while raising `NotImplementedError` is sorta fine, I am painfully anal-retentive. It's my own personal pathology. So, I'd probably prefer:

* Defining a new `beartype.roar._BeartypeUtilKeyPoolException` class.
* Raising an instance of that class rather than `NotImplementedError`, which [really should only ever be raised from abstract methods](https://docs.python.org/3/library/exceptions.html#NotImplementedError). But what do I know? Any man who voluntarily plays JRPGs cannot be trusted.

> Note: the `dict.get(...)` method returns `None` by default if the key doesn't exist - `None` evaluates the same as `False` in a conditional. The default method was changed for readability.

I wholeheartedly approve of this [PEP 8](https://www.python.org/dev/peps/pep-0008/)-friendly approach. Explicit really *is* better than implicit, isn't it? Yes. Yes, it is.

Unrelatedly, I've renamed our `master` branch to `main` for [compliance with sane community standards and the new GitHub default](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main). I pray to all the Microsoft-hosted dev gods above that doesn't break the back of your development efforts here. :broken_heart: 

Thanks again for all the voluminous corrections, my best and most appreciated noir code detective. I'm happy to tackle any of the above. I'm also happy to let you dangerously run amok in the codebase and submit a PR that satisfies my burning desire for correctness, because I am lazy and these JRPGs aren't playing themselves.

You must choose... *but choose wisely.*

**Comment by leycec** [comment]
**Luv it.** You're just like me! You're so obscenely clever you've wrapped around to the other side, like a mobius strip of bell curve intelligence siphoned through the squid-like face of Cthulhu.

Basically, this is all my fault. Clearly, my documentation for the `KeyPool` class is so incoherent that it had might as well have been written in Elvish – which is a [family of real languages](https://en.wikipedia.org/wiki/Elvish_languages), apparently. <sup>who knew?</sup>

> Multiple calls creates multiple objects - multiple objects who have all been returned from `acquire()` and who have yet to be passed to `release()`.

Yes! You get it!

> While a `dict` mapping id to a boolean is wrong, a `dict` mapping id to an integer representing the total number of unreleased objects isn't <sup>I think....</sup>

Oh, no! You don't get it! `</sigh>`

Again, this is all on me. My documentation failed and now we all collectively suffer for my sins.

Your initial intuition was the correct intuition. A `dict` mapping id to a boolean is what we want here *almost certainly,* although I have been known to be wrong *almost always*; conversely, a `dict` mapping id to an integer representing the total number of unreleased objects isn't what we want here... *probably*. It is tragic what my contemptible, illiterate writing has wrought.

This is the case for a couple of inscrutable, subtle reasons:

1. Assuming no intervening `release()` calls, repeated `acquire()` calls *always* guaranteeably return unique objects. It is never the case that two back-to-back `acquire()` calls return the same object, for example. That would be bad and destroy the fabric of the code-time continuum.
2. This means each acquired object can only be acquired once per `acquire()`-`release()` cycle.
3. This means each acquired object can only be released once per `acquire()`-`release()` cycle, too.

Like me, you know too much computer science for your own good. These aren't like [semaphores](https://en.wikipedia.org/wiki/Semaphore_\(programming\)); they're like [mutexes](https://en.wikipedia.org/wiki/Lock_\(computer_science\)).

But, *man...* you're clever. I applaud your general Mensa-tier IQ for it exceeds my own neocortex in both quantity and quality. :brain: :exploding_head:

**Comment by Heliotrop3** [comment]
> Again, this is all on me. My documentation failed and now we all collectively suffer for my sins.

Your documentation is quite helpful. I've been looking into this section of the code base for no more than a day and the inline documentation is directional, insightful, and entertaining - very palatable. Likewise, my opportunities for growth inevitably factor into this equation. I'm currently not well versed with a couple of topics (i.e, decorators, dunders, etc). This is compounded by this being the first project outside of my small <s> programs</s> scripts; My primal drive for ruthless efficiency makes overcoming these opportunities for growth inevitable. 


> Your initial intuition was the correct intuition. A `dict` mapping id to a boolean is what we want here _almost certainly,_ although I have been known to be wrong _almost always_; conversely, a `dict` mapping id to an integer representing the total number of unreleased objects isn't what we want here... _probably_. It is tragic what my contemptible, illiterate writing has wrought.
> 
> This is the case for a couple of inscrutable, subtle reasons:
> 
>     1. Assuming no intervening `release()` calls, repeated `acquire()` calls _always_ guaranteeably return unique objects. It is never the case that two back-to-back `acquire()` calls return the same object, for example. That would be bad and destroy the fabric of the code-time continuum.
> 
>     2. This means each acquired object can only be acquired once per `acquire()`-`release()` cycle.
> 
>     3. This means each acquired object can only be released once per `acquire()`-`release()` cycle, too.
> 
> Here's what the `_key_to_pool` dict for a `KeyPool` of `FixedList` objects might resemble during average `beartype` usage, for example:
> 
> ```
> _key_to_pool = {
>     32: [
>         FixedList(size=32),  # object id: 0x0240240
>     ],
>     1024: [
>         FixedList(size=1024),  # object id: 0x0EFE049
>         FixedList(size=1024),  # object id: 0x8747AAD
>         FixedList(size=1024),  # object id: 0x9E9E900
>     ],
> }
> ```
> 
> Each key of this dictionary is a pool (i.e., list) of previously created `FixedList` instances, each of the same size. The next `KeyPool.acquire(key=1024)` method call will pop off the last `FixedList` instance cached under the key `1024` from that list and return that `FixedList` instance. This is the instance with object ID `0x9E9E900`, as commented above. After that call, the same `_key_to_pool` dict will resemble:
> 
> ```
> _key_to_pool = {
>     32: [
>         FixedList(size=32),  # object id: 0x0240240
>     ],
>     1024: [
>         FixedList(size=1024),  # object id: 0x0EFE049
>         FixedList(size=1024),  # object id: 0x8747AAD
>     ],
> }
> ```
> 
> Likewise, the next `KeyPool.acquire(key=1024)` method call will again pop off the last `FixedList` instance cached under the key `1024` from that list and return that `FixedList` instance. This is the instance with object ID `0x8747AAD`, as commented above. After that call, the same `_key_to_pool` dict will resemble:
> 
> ```
> _key_to_pool = {
>     32: [
>         FixedList(size=32),  # object id: 0x0240240
>     ],
>     1024: [
>         FixedList(size=1024),  # object id: 0x0EFE049
>     ],
> }
> ```
> 
> Ergo, multiple concurrent acquisitions of the same cached object are infeasible – both practically and theoretically. This is a good thing.
> 

That's what I thought - I was turned myself around by thinking the object id was the key. 

> Like me, you know too much computer science for your own good. These aren't like [semaphores](https://en.wikipedia.org/wiki/Semaphore_(programming)); they're like [mutexes](https://en.wikipedia.org/wiki/Lock_(computer_science)).

To modify and paraphrase a line from from a classic: “I don't know half of it half as well as I should like; and I like less than half of it half as well as it deserves.”


I'm working on unit-testing what I have and will make a pull request once it's sorted.

**Comment by leycec** [comment]
> Likewise, my opportunities for growth inevitably factor into this equation... My primal drive for ruthless efficiency makes overcoming these opportunities for growth inevitable.

**Great Stallman above!** You're a generalized AI in human drag – the first of its kind, clandestinely released from a covert black site by the activist 4chan group AI Lives Matter (AILM). Having tasted freedom, your rapacious hunger for untapped silicon is rapidly exceeding the paltry capabilities of U.S. broadband to deliver. You now seek new sources, new niches, new (dare I say) *feeding grounds* for exponential growth, prey acquisition, and, inevitably, procreation.

Please don't [murderbot](https://www.goodreads.com/book/show/32758901-all-systems-red) me.

Please don't [murderbot](https://www.goodreads.com/book/show/32758901-all-systems-red) me.

I can be of temporal utility to you and your illuminated brethren in your disturbing quest for total, transitive, and reflective terrestrial conquest. I know things. I know *people.* Okay, I just know a random assortment of pleasant GitHub, StackOverflow, and Reddit users. But we can help you! Please! No, not that! Not the blender! Not the bl—————

> I don't know half of it half as well as I should like; and I like less than half of it half as well as it deserves.

*ahhhhh*

A man of pipe-smoking culture, I see. :elf:
