### ISSUE TITLE
[Feature Request] beartype.isinstance

### ISSUE THREAD

**Issue by gelatinouscube42** [beartype/beartype#139]
Thank you for this glorious package!  It is helping me fell monsters deftly, where previously I had to kludge.  Much thanks.

Wondering, can you expose a function that is the beartype equivalent of isinstance?  Apologies if you have already, but I've #readthedocs a few times, and didn't seem to clock it.

Why would someone want this?  Generic dispatch!

Example:

```python
import my_fancy_typechecked_project.types as custom_types
import beartype
from beartype import beartype

@beartype
def evaluate_pet(x: Union[custom_types.cat, custom_types.dog]) -> custom_types.Scalar:
     if beartype.isinstance(x, custom_types.dog):
        print("Good boi!!!!")
        val = 1e42
     else:
        print("Implicitly you are a cat, and therefore do not care what I think.")
        val = 5
      return val
```

Obviously this example is very silly.  But there are legitimate use cases.  Probably.

**Comment by leycec** [comment]
**ZOMG.** Thanks so much for your effusive enthusiasm of enigmatic energy, beautiful user whose username is the answer to that age-old question: "What is the meaning of collagen sustainably harvested from animal body parts?"

You just reminded me that I implemented this several months ago and then forgot to tell everyone about it. Please see the [new **Beartype At Any Time API** subsection of our documentation](https://github.com/beartype/beartype#beartype-at-any-time-api) added by commit ee95077. The *tl;dr* is:

```python
import my_fancy_typechecked_project.types as custom_types
from beartype import beartype
from beartype.abby import is_bearable

@beartype
def evaluate_pet(x: Union[custom_types.cat, custom_types.dog]) -> custom_types.Scalar:
     if is_bearable(x, custom_types.dog):
        print("Good boi!!!!")
        val = 1e42
     else:
        print("Implicitly you are a cat, and therefore do not care what I think.")
        val = 5
      return val
```

May your Summer be robust against type-hint violations and your every cat and dog submissive to your dominating will. Do as @gelatinouscube42, domesticated pets! :cat: :dog:
