### ISSUE TITLE
Windows defender Blocking install when installing Pglet 

### ISSUE THREAD

**Issue by da-geek-incite** [beartype/beartype#146]
![image](https://user-images.githubusercontent.com/76908143/179367709-2533c7d4-0cf6-44ab-ba88-22eaa159ec5e.png)

**Comment by leycec** [comment]
**So this is how you repay us, Windows.** [Pglet](https://github.com/pglet/pglet) isn't @beartype, though? Moreover, pglet doesn't internally leverage @beartype – *yet*, anyway. :smirk: 

Did you mean to submit this to pglet's issue tracker instead, @da-geek-incite? Kinda feel like there's some cross-chatter in the line here. So, let's just quietly close this and pretend Windows Defender never saw nuthin'.

If this is indeed an actual @beartype issue, please reopen and we'll reassess the looming crisis of Pythonic malware at that point. :+1:
