### ISSUE TITLE
[Feature Request] Generalize @beartype to support `class` decoration

### ISSUE THREAD

**Issue by posita** [beartype/beartype#152]
Apologies if this is a dup. This is interesting…

``` py
# test_case.py
from __future__ import annotations
from typing import Union
from beartype import beartype

class Test:
    @beartype
    def okay(self) -> Test:
        return Test()

    def okay_too(self, other: Union[int, str, Test]) -> Test:
        return Test()

    @beartype
    def also_okay(self, other: Union[int, str, "Test"]) -> Test:
        return Test()

    @beartype
    def also_also_okay(self, other: Union[int, str, "Test"]) -> "Test":
        return Test()

    # @beartype  # uncomment me for ...
    def a_kaboom(self, other: Union[int, str, Test]) -> Test:
        return Test()

    @beartype  # uncomment me for ...
    def another_kaboom(self, other: Union[int, str, Test]) -> "Test":
        return Test()
```

As-is:

``` sh
% python --version  # also happens with 3.9.13
Python 3.10.5
% python -c 'import beartype ; print(beartype.__version__)'
0.10.4
% python test_case.py
[no output]
```

Now uncomment `@beartype` decorating `a_kaboom`:

``` py
% python test_case.py
Traceback (most recent call last):
  File "/…/lib/python3.10/site-packages/beartype/_decor/_pep/pep563.py", line 338, in resolve_hints_pep563_if_active
    func_hints_resolved[pith_name] = eval(
  File "<string>", line 1, in <module>
NameError: name 'Test' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/…/test_case.py", line 6, in <module>
    class Test:
  File "/…/test_case.py", line 23, in Test
    def a_kaboom(self, other: Union[int, str, Test]) -> Test:
  File "/…/lib/python3.10/site-packages/beartype/_decor/cache/cachedecor.py", line 77, in beartype
    return beartype_args_mandatory(obj, conf)
  File "/…/lib/python3.10/site-packages/beartype/_decor/_core.py", line 140, in beartype_args_mandatory
    return _beartype_func(func=obj, conf=conf)
  File "/…/lib/python3.10/site-packages/beartype/_decor/_core.py", line 168, in _beartype_func
    func_data.reinit(func, conf)
  File "/…/lib/python3.10/site-packages/beartype/_decor/_call.py", line 285, in reinit
    resolve_hints_pep563_if_active(self)
  File "/…/lib/python3.10/site-packages/beartype/_decor/_pep/pep563.py", line 375, in resolve_hints_pep563_if_active
    raise BeartypeDecorHintPep563Exception(
beartype.roar.BeartypeDecorHintPep563Exception: @beartyped Test.a_kaboom() parameter "other" PEP 563-postponed type hint 'Union[int, str, Test]' syntactically invalid (i.e., "name 'Test' is not defined") under:
~~~~[ GLOBAL SCOPE ]~~~~
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x10c09d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/…/test_case.py', '__cached__': None, 'annotations': _Feature((3, 7, 0, 'beta', 1), (3, 11, 0, 'alpha', 0), 16777216), 'Union': typing.Union, 'beartype': <function beartype at 0x10c7a7250>}
~~~~[ LOCAL SCOPE  ]~~~~
{'__module__': '__main__', '__qualname__': 'Test', 'okay': <function Test.okay at 0x10c1284c0>, 'okay_too': <function Test.okay_too at 0x10c8c8e50>, 'also_okay': <function Test.also_okay at 0x10c8c9000>, 'also_also_okay': <function Test.also_also_okay at 0x10c8c9120>}
```

You'll get something similar when uncommenting `another_kaboom` as well.

**Comment by posita** [comment]
FWIW, I get a similar error with e397a90 (but with slightly different line numbers):

``` py
Traceback (most recent call last):
  File "/…/beartype/beartype/_decor/_pep/pep563.py", line 336, in resolve_hints_pep563_if_active
    func_hints_resolved[pith_name] = eval(
  File "<string>", line 1, in <module>
NameError: name 'Test' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/…/test_case.py", line 6, in <module>
    class Test:
  File "/…/test_case.py", line 23, in Test
    def a_kaboom(self, other: Union[int, str, Test]) -> Test:
  File "/…/beartype/beartype/_decor/_cache/cachedecor.py", line 77, in beartype
    return beartype_object(obj, conf)
  File "/…/beartype/beartype/_decor/decorcore.py", line 147, in beartype_object
    return _beartype_func(func=obj, conf=conf)
  File "/…/beartype/beartype/_decor/decorcore.py", line 307, in _beartype_func
    func_data.reinit(func, conf)
  File "/…/beartype/beartype/_decor/_decorcall.py", line 285, in reinit
    resolve_hints_pep563_if_active(self)
  File "/…/beartype/beartype/_decor/_pep/pep563.py", line 373, in resolve_hints_pep563_if_active
    raise BeartypeDecorHintPep563Exception(
beartype.roar.BeartypeDecorHintPep563Exception: @beartyped __main__.Test.a_kaboom() parameter "other" PEP 563-postponed type hint 'Union[int, str, Test]' syntactically invalid (i.e., "name 'Test' is not defined") under:
~~~~[ GLOBAL SCOPE ]~~~~
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x103365270>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/…/test_case.py', '__cached__': None, 'annotations': _Feature((3, 7, 0, 'beta', 1), (3, 11, 0, 'alpha', 0), 16777216), 'Union': typing.Union, 'beartype': <function beartype at 0x1039d8310>}
~~~~[ LOCAL SCOPE  ]~~~~
{'__module__': '__main__', '__qualname__': 'Test', 'okay': <function Test.okay at 0x1033f0790>, 'okay_too': <function Test.okay_too at 0x103ba4af0>, 'also_okay': <function Test.also_okay at 0x103ba4ca0>, 'also_also_okay': <function Test.also_also_okay at 0x103ba4dc0>}
```

**Comment by posita** [comment]
I'm pretty sure `Iterable[<unquoted_forward_reference>]` will fail as well.

**Comment by leycec** [comment]
```python
from __future__ import annotations
```

**Welp.** There's yer problem right there, @posita. :face_with_head_bandage: 

Just when you thought the fearless `pydantic` crew had *finally* beaten [PEP 563](https://peps.python.org/pep-0563) into the filth-clogged gutter of the `python-typing` mailing list and we could all begin to seek therapeutic GitHub-centred group counselling...

![johnny again](https://c.tenor.com/OQMnhrjFPVsAAAAd/heres-johnny.gif)

John Wick has a solution for this problem, too.

![solutions abound](https://c.tenor.com/uoYwIW3op2AAAAAC/john-wick-keanu-reeves.gif)

**Comment by posita** [comment]
[!["Oh..... SHIT"! {Carol Cleveland)](https://c.tenor.com/UW6Mslmkh28AAAAM/hqrg-well.gif)](https://youtu.be/YZ1DCCKFvKw)

If it's convenient, I'm happy to pretend I never saw this. 😉

[![Nothing to see here!](https://c.tenor.com/O9a0ZA-Qs-AAAAAM/john-bender-sarcasm.gif)](https://youtu.be/TQqsRKdmLck)

**Comment by leycec** [comment]
**Calgon, take me away!** Don't do it, Calgon! *Noooooooooo–*

Okay. So, pretty sure (but technically uncertain) this is just to due to unexpected eccentricities in Python's core decorator design that we can't particularly do anything about. If only we could, Python; if only we could.

When decorating a method, the @beartype decorator runs at a relatively early time – early enough that the class defining that method **has yet to be defined.** From the painfully myopic perspective of @beartype, the enclosing `Test` scope does not exist.

This is one of a few reasons why generalizing @beartype to support full-blown class decoration would be the bee's arthritic knees. Once we reach that API Shangri-La, the following alternative *should* work as expected. Let's choose to believe these specious words I am spewing about as if they mean something:

```python
# test_case.py
from __future__ import annotations
from typing import Union
from beartype import beartype

@beartype
class Test:
    def okay(self) -> Test:
        return Test()

    def okay_too(self, other: Union[int, str, Test]) -> Test:
        return Test()

    def also_okay(self, other: Union[int, str, "Test"]) -> Test:
        return Test()

    def also_also_okay(self, other: Union[int, str, "Test"]) -> "Test":
        return Test()

    def no_longer_a_kaboom(self, other: Union[int, str, Test]) -> Test:
        return Test()

    def no_longer_another_kaboom(self, other: Union[int, str, Test]) -> "Test":
        return Test()
```

Let's prod me into doing something by slyly renaming this issue into a feature request. You demand it, we'll do it! Sometime. For unspecified definitions of "sometime" that may involve non-trivial convolutions of the eleventh dimension of the space-time continuum. Not a problem, of course. A bit of Spice from Arakis and we'll be good to go, gentlemen! :salt:

**Comment by leycec** [comment]
Dance, disgustingly slinky mammal. Dance, I say.

![cat is happening](https://c.tenor.com/DJwsoiydW_QAAAAM/smooth-criminal-cat.gif)

And that is how we publicly rejoice when @leycec does something he should have done *before* losing his last hair follicle. Yes, it's all true. Commit a37a2d4 generalizes @beartype to fully decorate classes. I'm *fairly* certain everything behaves as expected despite not actually testing anything... :smiling_face_with_tear: 

**OH, WHO AM I KIDDING!?!?** I'm sure everything's broken. Let's exhaustively test this until I pass out from heatstroke-induced dehydration. Apparently, living in a cottage without air conditioning is a thing people should not do anymore. I'll show them all! :hot_face:

**Comment by leycec** [comment]
![chuckles](https://c.tenor.com/gFFtQIFjFq4AAAAM/yes-sweet.gif)

This precious meme can only mean one thing...

**Resolved by 3bdc74b.** Yes. YES! Gentlemen, it's all true. For the low, low price of your invaluable time away from essential life duties like [Ironsworn GMing](https://www.reddit.com/r/Ironsworn), <sup>*looks sick, bro – "sick" still means "cool," right?*</sup> `@beartype` now supports all this and more via fully-blown class decoration support.

This constitutes the last meaningful changeset in the `beartype 0.11.0` release cycle. *Let's do this.*

**Comment by posita** [comment]
Having been largely misattributed for this accidental feature request, I feel it is my duty to declare your attempt to Locate Your Objective in this Delve of this Haunted Icereach as resolved with a Strong Hit. I also wish you luck in returning to your game of Call of Savage Dragon Worlds in the Dark Powered by Numenuma Fate, 4th Edition by West Palladium Jackson Games. You are one step closer to becoming the Torg.

![Crit, bro!](https://c.tenor.com/CARgJFTXTO4AAAAM/nat20-d20.gif)

**Comment by leycec** [comment]
> I feel it is my duty to declare your attempt to Locate Your Objective in your Delve of this Haunted Icereach as resolved with a Strong Hit. I also wish you luck in returning to your game of Call of Savage Dragon Worlds in the Dark Powered by Numenuma Fate™, 4th Edition by West Palladium Jackson Games®.

**Holy dragon balls.** I read that in the thick, gravel-throated intonation of Christopher Lee's Saruman, who was also required by Jackson's dubious legal counsel to slowly read out each of the ™ and ® Unicode symbols. Thanks so much for the morning chuckles. :laughing:
