### ISSUE TITLE
Make `is_bearable` a bona fide type guard!

### ISSUE THREAD

**Issue by rsokl** [beartype/beartype#166]
`is_bearable` rules, **but**, with one minor modification, it could *rule*: enable [type-narrowing](https://mypy.readthedocs.io/en/latest/type_narrowing.html#generic-typeguards)!

```python
from typing import TypeGuard, TypeVar, Type

from beartype import BeartypeConf
from beartype.abby import is_bearable

T = TypeVar("T")

# Proposed signature for `is_bearable` to support type-narrowing
def is_bearable2(
    obj: object,
    hint: Type[T],
    *,
    conf: BeartypeConf = BeartypeConf(),
) -> TypeGuard[T]:
    ...


def gimme_strings(y: list[str]): ...
def gimme_ints(y: list[int]): ...

def beartype_feels_that_there_is_two_sides_to_every_story_and_doesnt_want_to_get_too_political(
    x: list[int | str],
):
    if is_bearable(x, list[str]):
        # We've learned new things about `x` given that it has survived and made it
        # into this context. 
        # But is_bearable doesn't let static type checkers know about its lived experience!
        gimme_strings(x)  # mypy/pyright: error

    if is_bearable(x, list[int]):
        gimme_ints(x)  # mypy/pyright: error


def beartype_actually_just_read_a_thread_on_reddit_about_this_very_topic_and_has_some_thoughts(
    x: list[int | str],
):
    if is_bearable2(x, list[str]):
        # `x` has been though a lot, let's celebrate its courageous story 
        gimme_strings(x)  # mypy/pyright: OK!

    if is_bearable2(x, list[int]):
        gimme_ints(x)  # mypy/pyright: OK!
```

This change has more to it than meets the eye: it turns `is_bearable` from a validator into a parser [^1]. The virtues of parsing seem to be under-appreciated in the Python world, and even harder to put into practice there. `beartype` can help to change that[^2]!

[^1]: A validator checks that some condition is met by our data. End of story. A parser consumes less-structured data and produces more-structured output. At runtime, these are effectively the same thing. But, statically, the parser captures what we have learned about our data in the form of the type that it returns: it conveys the data's type, [*plus a proof*](https://kataskeue.com/gdp.pdf) that the data has been parsed. Read more about this here: https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/

[^2]: There is lots to discuss here, and I am not as experienced in this area as I would like to be, but I think that `is_bearable`, with added type-narrowing capabilities, has the power to be transformative in the way that people can design their projects. It enables one to avoid the ad-hoc validation, and to instead stratify one's program into a parsing phase – the only place where failure can happen due to invalid input – and an execution phase. This strategy is not made obvious by the likes of typeguard.

**Comment by leycec** [comment]
**Brilliant machine-learning specialists think alike.** [*Exactly* alike](https://github.com/beartype/beartype/issues/164), in fact.

@justinchuby gently suggested we do this three days ago at #164. Like the neural nets you relentlessly fine-tune, I've quickly learned that both you and @justinchuby are right about everything. I don't even question incoming issues by you or @justinchuby anymore. I just blindly implement everything you suggest. Then... @beartype magically becomes better. There are majestic forces at play here beyond my diminutive understanding – which is a good thing. I only barely grok half of the @beartype codebase anymore. Sometimes I look at this code in the autumnal dark of a Saturday evening and I'm like: "What grotesque mockery of a sentient parser are you becoming, @beartype!?!?"

What I'm saying is: *we did this three days ago!* Would you like to help us test? If so, please temporarily update to the newest live GitHub-hosted version. All tests pass as of our most recent commit, which enjoys ~97% test coverage or so. This will also get you full `pyright` **+** PyLance **+** VSCode compatibility, class decoration support, colourful violation messages, and (*...germane to this topic*) a *much* faster `is_bearable()` runtime type-checking parser <sup>:heart_eyes_cat:</sup> – among many other delicious type-checking freebies.

Assuming you manage @beartype with `pip`, the magical one-liner that will change your QA life is:

```bash
python3 -m pip install git+https://github.com/beartype/beartype.git@f34e2b3e785b01ea49272fce73ca832c6508fe71
```

**Comment by rsokl** [comment]
Wonderful! I tried searching for "type narrowing" but should have looked for "typeguard" as well. doh!

**Comment by leycec** [comment]
**Even further resolved by 430065bf2cf.** Strongly inspired by your example above (especially your *utterly* hilarious social media jibes), I've added a [new FAQ entry on beartype's explicit support for type narrowing](https://github.com/beartype/beartype#id27). All this human-readable glory is because of your gentle prodding.

I still repeatedly :rofl: at this comment:

```python
        # `x` has been though a lot, let's celebrate its courageous story
```

**Comment by lorenzo-w** [comment]
For the record and for anyone stumbling upon this old issue via Google and subsequently dispairing as the described fucntionality just isn't there in the package:

The `TypeGuard` return type was removed again by commit [2ae007](https://github.com/beartype/beartype/commit/2ae007b3dc0e1dcd28ea6865f477afb085df3776) to resolve #255, which boils down to an upstream issue with the typing system itself. So buckle up, it's probably going to be some time before we can get it back 🫠

**Comment by leycec** [comment]
**Gah!** Thanks so much for the clarification, @lorenzo-w. Indeed, the current implementation of `typing.TypeGuard` by static type-checkers like mypy and `pyright` is fundamentally flawed; it's overly narrow to the point of being pragmatically useless. `typing.TypeGuard` only matches low-level *unsubscripted types* (like `list` or `dict`), whereas the @beartype userbase expected `typing.TypeGuard` to match full-blown *subscripted type hints* (like `list[str]` or `dict[T]`). Despite looking like actual types, subscripted type hints aren't actually types. I weep for `typing`. :sob: 

Kinda sad, really. Since `typing.TypeGuard` only matches types, it's pretty much useless for real-world usage.

**Comment by lorenzo-w** [comment]
**Good news everybody!**
[PEP 747](https://peps.python.org/pep-0747/) has landed (unlike some of the same-numbered planes ^^). It defines a new annotation `TypeForm[T]`, which can be used in place of `type[T]` and explicitly supports type narrowing. It will be in Python 3.14 and [according to the docs](https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.TypeForm) in the next minor release of `typing-extensions`. As soon as that's out, we can have our cake 🎉🍰

**Comment by leycec** [comment]
**So much excitement.** There are *more* than a few public @beartype APIs that can immediately benefit from `TypeForm` – and even more private @beartype APIs. Let us party like base `typing` hedonists over at #459, which @JWCS has so graciously opened up. :partying_face:
