### ISSUE TITLE
[Documentation] Update "README.rst" to reflect beartype's hard-earned support for pyright 😄 

### ISSUE THREAD

**Issue by rsokl** [beartype/beartype#170]
https://github.com/beartype/beartype#under-vscode currently tells users to disable pylance in order to use beartype, which is no longer necessary: beartype now valiantly supports mypy and pyright! ❤️

**Comment by leycec** [comment]
**Gah!** Thanks a heap for the gentle reminder that demonstrable badness is still afoot in our `README.rst`. I'd meant to excise away that entire subsection. It's unnecessarily combative, which is a bad look for @beartype in 2022. It's also embarrassingly wrong to push VSCode's mypy extension, when doing so pathetically slows VSCode to a crawl *and* when mypy is arguably less accurate than pyright in common use cases and painfully broken in others (e.g., recursive type hints).

Sadly, this got pushed under the rotten rug in our feverish push to release `beartype 0.11.0`. Thankfully, we have a brief reprieve before the madness resumes. I still need to actually document everything everyone did for `beartype 0.11.0`. So, this is now the first action item on that list!

Thanks again for helping us out of the pit of bad documentation that we have dug. :grin:

**Comment by leycec** [comment]
**Resolved by 430065b.** [Our existing FAQ entry on VSCode](https://github.com/beartype/beartype#id25) has been fundamentally rewritten from the ground up to be considerably more charitable to `pyright`, whose stupefying speed justifies its default usage in Pylance.

Thanks so much for the gentle reminder, @rsokl. You make AI happen. Hopefully, not scary AI.
