### ISSUE TITLE
[Feature Request] Implicit numeric tower option in `beartype.BeartypeConf`

### ISSUE THREAD

**Issue by leycec** [beartype/beartype#174]
### Discussed in https://github.com/beartype/beartype/discussions/173

<div type='discussions-op-text'>

<sup>Originally posted by **felixchenier** September 26, 2022</sup>
Good morning

I'm trying to see if beartype would fit my need as a simple-to-operate real-time type checker. This is for a public API that I'm building, and I don't want to manually check everything, or to reprogram something that is for sure a very deep rabbit hole!

But I have an issue with beartype being a little bit too rigorous. Many of my functions accept floats as parameters, and I expect the users (including me) to sometimes provide integers instead of floats. The calculations work, and mypy is also fine with it. However, by using beartype, I have a runtime error (int != float), which in my case is not what I would need.

I don't want to mess with every signature and change (a: float) to (a: Union[float, int]), which:
1. is ugly and useless;
2. will fail eventually, since I will forget one, mypy won't tell me, but I'll have plenty of users who will have unexpected runtime errors.

Is there an easy way to switch off some type checks, such as this one?

Thank you!</div>

**Comment by leycec** [comment]
*...heh.* This is a classic conundrum.

By default, @beartype intentionally rejects lossy coercions – because they're lossy. In most mission-critical fields (like finance or biotech, the latter of which my wife and I work in), lossy coercions are often outright prohibited by binding contracts, internal policies, and/or governmental regulations; in less mission-critical fields, lossy coercions are still typically seen as undesirable. Since @beartype is oriented towards scientific applications, a loss of numerical precision without the explicit consent of the developer is generally bad and *not* something we want actively encourage or promote...


By default, anyway! Thankfully, @beartype fully supports [Python's explicit tower](https://docs.python.org/3/library/numbers.html#numbers.Real). Admittedly, you probably don't want to. This is a laborious refactoring that would you require you to explicitly retype *all* type hints across your public API from `float` to `numeric.Real`: e.g.,

```python
# Consider globally replacing all uses of "float" in annotations like this...
@beartype
def crunch_numbers(numbers: list[float]) -> float:
    return sum(numbers)

# ...with uses of "numeric.Real", instead. @beartype already supports this
# out-of-the-box. Rejoice! \o/
from numeric import Real

@beartype
def crunch_numbers(numbers: list[Real]) -> Real:
    return sum(numbers)
```

You are now thinking: "I hate @beartype." I knew it. You *were* thinking that.

But that's fine. You're not wrong to want the [implicit numeric tower](https://peps.python.org/pep-0484/#the-numeric-tower). You're right, actually. We really should support that with a new option. I believe we can eventually satisfy everyone, because @beartype's three middle names are Mr. Happy Bear.

But first: a **M**ostly **M**eaningless **M**onologue to **M**yself (MMMtM) on PEP 484. :grimacing: 

## B-b-ut... PEP 484!

So. It comes to this.

There's a conflict here between [PEP 8's maxim that "Explicit is better than implicit"](https://peps.python.org/pep-0008) and [PEP 484's implicit numeric tower](https://peps.python.org/pep-0484/#the-numeric-tower). Whenever something conflicts with PEP 8, @beartype usually errs on the side of PEP 8. PEP 8 is the bible we all code by, after all. We believe Guido, Jukka Lehtosalo, and Łukasz Langa got [that subsection of PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower) profoundly wrong. They meant well, but that's how the road to unpleasant places is paved. That said...

## Options Are Fun for the Whole Family

**@beartype really should provide an option to enable the implicit numeric tower.** If you have this pressing API need without which @beartype is uselessly dead to you, then so does everybody else, @felixchenier.

Fortunately, @beartype has an existing public configuration API. We could certainly add a new public boolean to that API instructing @beartype to respect implicit number coercions (e.g., `complex` -> `float` -> `int`). I'm kinda at a loss of what to name that boolean, but I'm sure we can hack out something reasonably disambiguous. Possibilities include:

* `is_implicit_numeric_tower`? `is_allow_numeric_coercion`? Painfully long, but painfully clear.
* `is_coerce_numbers`? Blessedly shorter... and still mostly blessedly clear.
* `is_numeric_tower`? Even shorter, but now we're trending towards ambiguity.

Anyway! Let's assume `is_coerce_numbers` for sanity. Here's how you'd actually use it:

```python
from beartype import beartype, BeartypeConf

beartype_towering = beartype(conf=BeartypeConf(is_coerce_numbers=True))
'''
:func:`beartype.beartype` decorator configured to enable the
:pep:`484`-compliant **implicit numeric tower** (i.e., allow lossy coercions
from `complex` to `float` to `int` types).
'''

@beartype_towering
def crunch_numbers(numbers: list[float]) -> float:
    return sum(numbers)

# This is now fine.
crunch_numbers([3, 1, 4, 1, 5, 9])

# This is still fine, too.
crunch_numbers([3.1, 4.1, 5.9])
```

Best of both worlds right there, right? Your public API preserves its current annotations and mypy-compliance. Meanwhile, you just decorate classes and callables with your API-specific `@beartype_towering` decorator that nobody else needs to know about.

Would that satisfy everything on your end?

## The Road to Heaven Is Paved with Good Commits

Might I say, too, that I *love* hearing from fellow Canucks. My wife and I had a dusty road trip across the Quebec wilderness a few years back. Francophones everywhere are a wonderfully hospitable people. The l'Acropole des Draveurs in the [Montagne des Érables](https://en.wikipedia.org/wiki/Montagne_des_%C3%89rables) is not a thing we will ever forget, either.

Thanks so much for the thoughtful feature request, @felixchenier. We promise to satisfy your API's urgent need for the implicit numeric tower as soon as our Bengal cat stops angrily squealing for food. Gah! Down, feisty cat with wickedly blood-sharp claws! Down! :tiger: :tiger2:

**Comment by leycec** [comment]
> If there was a beartype.check_argument_types() function, that would be insanely great.

**Bwaha!** My documentation must be even worse than I thought. Okay, my documentation absolutely is worse than I thought – because @beartype does provide a growing laundry list of statement-level near-real-time runtime type-checkers that guarantee `O(1)` time complexity with negligible constants.  Rejoice, gentlemen! :partying_face: 

You have a menu of **four** options here, depending on whether you prefer a procedural or object-oriented API and whether you prefer your check to raise an exception *or* just return `True` or `False`:

```python
# Import the requisite machinery.
>>> from beartype.door import TypeHint, die_if_unbearable, is_bearable

# Procedurally return "True" only if an object satisfies a hint.
>>> is_bearable('Stop exploding, you cowards.', list | bool | None)
False
>>> is_bearable('Stop exploding, you cowards.', list | bool | None | str)
True

# Object-orientedly do the same thing if you prefer your APIs hard-boiled.
>>> TypeHint(list | bool | None).is_bearable('Stop exploding, you cowards.')
False

# Procedurally raise an exception if an object violates a hint.
>>> die_if_unbearable("My people ate them all!", list | int | None)
BeartypeDoorHintViolation: Object 'My people ate them all!' violates
type hint list | int | None, as str 'My people ate them all!' not
<class "builtins.NoneType">, list, or int.
>>> die_if_unbearable("My people ate them all!", list | int | None | str)
# <-- silence is golden

# Object-orientedly do the same thing if that's just how you roll.
>>> TypeHint(list | int | None | str).die_if_unbearable('My people ate them all!')
False
```

They're *not* quite as automated as typeguard's `check_argument_types()` and `check_return_type()` utilities, which automatically check against the type hints annotating the current function. But [those utilities fail for closures and nested callables](https://typeguard.readthedocs.io/en/latest/userguide.html#using-type-checker-functions). So, that's probably just as well.

Also, everything above runs in around **1µs** (i.e., one millionth of a second) regardless of input size. You know. Just sayin'.

Also...

> But they often add so many frames to the traceback, that it significantly negatively affects debugging.

This must be your lucky Wednesday. @beartype-decorated callables **add absolutely no additional frames to the traceback** (except for a single extra frame that performs the actual type-check, of course). The proof is in the dairy-free pudding. Behold!

```python
>>> from beartype import beartype
>>> @beartype
... def omg(wtf: str) -> int:
...     return len(wtf)
>>> omg(b"I can't believe it's a byte-string.")
Traceback (most recent call last):
  Input In [28] in <cell line: 1>
    omg(b"I can't believe it's a byte-string.")
  File <@beartype(__main__.omg) at 0x7f57a9abfbe0>:21 in omg
BeartypeCallHintParamViolation: @beartyped __main__.omg()
parameter wtf=b"I can't believe it's a byte-string." violates type hint
<class 'str'>, as bytes b"I can't believe it's a byte-string." not instance of str.
```

Note the complete lack of *any* stack frames in that traceback.

Just like you, everyone wanted that. Everyone hates traceback frames, too. Everyone was right. So we deeply refactored @beartype to ensure that a few releases ago. These must be the glory days of typing, indeed.

> What? I violated something? What's been violated, is it okay? I hope so much I didn't break something. What is a type hint? What is an instance? What is that bear that violates types? I quit.

:laughing: 

Oh, man. You got me. You're a great writer, too. I'm rolling in my seat over here and the cat's looking at me funny... *yet again.*

You're right, of course. @beartype is excrutiatingly exact to the point of gross stupidity and negligence. Thankfully, @beartype exceptions are now colour-coded as of `beartype 0.11.0`:

![it's all true](https://user-images.githubusercontent.com/11205048/188284817-8e063b94-7bac-40a8-a6a1-35b99bcdcce6.png)

Suck it, `typeguard`! Just kidding, of course. We all love @agronholm here and just wish he had a bit more time to throw at `typeguard`.

So, colouring helps @beartype readability a *bit.* But... yeah. We can and really should do better there. Let's consider what can be done while I pet our purring Bengal cat like a real Canadian Prime Minister.

**Comment by felixchenier** [comment]
Wow, that's pure magic. Sorry for not reading the doc well, the thing is that I'm not formed in computer science. I mostly learned by myself, and there are lots of concepts that I know for sure, but not to the point where I could put a name on it. Since the doc has lots of CS jargon, then I'm often a bit lost in it. But than you @leycec for your examples in this reply, I see more and more how I could use beartype. I added a question here: #176 about numpy ArrayLike. If we can get ArrayLike and implicit numeric tower to work, then I'm pretty sure beartype will become a solid addition to my toolkit. In the mean time, I programmed a lousy, deficient, ugly, slow, shaky, short-sighted and bald type checker for my temporary needs, so I'm not in a rush.

**Comment by leycec** [comment]
Oh, no worries whatsoever! My wife's entirely self-taught, too – which is probably why she codes circles around me like a software tyrant while I'm mostly just fiddling with type-checking here in the back corner. The self-taught are often the best. Take it from most well-known musicians, for example; they can't read sheet music and never went to Conservatory, but we all know their names. You're kinda like that. :full_moon_with_face: 

I'm currently obsessed with documenting everything we pushed out for `beartype 0.11.0`. So, it may take a hot minute or two for me to finally implement this feature request for the implicit numeric tower. On the bright side, when I finally do, it should be pretty trivial. Let's choose to believe these seductive words I am saying.

**Comment by leycec** [comment]
**It's happening.** I... decided against documentation, because documentation is boring. Instead, we're going hard on our configuration API for @beartype's upcoming `0.12.x` release cycle. That means this is up next. The tension is palpable.

Rejoice, @felixchenier! @beartype is *almost* usable for your use case now. :grin:

**Comment by leycec** [comment]
**It happened!** Although difficult to believe, [I did something and even documented it](https://github.com/beartype/beartype#beartypeconf-is-pep484-tower):

```python
# Import the requisite machinery.
from beartype import beartype, BeartypeConf

# Dynamically create a new @beartowertype decorator enabling the tower.
beartowertype = beartype(conf=BeartypeConf(is_pep484_tower=False))

# Decorate with this decorator instead of the vanilla @beartype decorator.
@beartowertype
def crunch_numbers(numbers: list[float]) -> float:
    return sum(numbers)

# This is now fine.
crunch_numbers([3, 1, 4, 1, 5, 9])

# This is still fine, too.
crunch_numbers([3.1, 4.1, 5.9])
```

We'll be publishing this in our upcoming `beartype 0.12.0` release this Friday. I *think* that only leaves [`numpy.typing.ArrayLike` and `numpy.typing.DTypeLike`](https://github.com/beartype/beartype/discussions/176) as your final concerns, right?

Sadly, I am tired. The mind is willing; the flesh is weak. Would you mind if I take a rain check on those two for a bit? Supporting NumPy type hints is critically relevant to @beartype... but so is passing out on my bed. With any luck (and no small amount of prodding), we'll tackle both in `beartype 0.13.0`.

Thanks again for all the interest *and* being such an awesome Québécois! Please gently prod me in a discussion or issue if I stay tired and fail to do anything about `numpy.typing`. Until then, may the spooky maple leaves of Halloween be with us all. :maple_leaf: :jack_o_lantern: :maple_leaf:
