### ISSUE TITLE
[Feature Request] `beartype.BeartypeConf.is_color` option to avoid embedding ANSI escape sequences in type-checking violation exception messages

### ISSUE THREAD

**Issue by foxx** [beartype/beartype#178]
Long time no speak! First of all, awesome work on the recent improvements to BearType, this library really is the gift that keeps on giving.

## The Problem

For some reason, BearType colourized exception messages do not play nicely with libraries such as Python Rich, which have their own traceback colourizing system. As you can see from the below image, some of the ANSI codes are not properly escaped.

![image](https://user-images.githubusercontent.com/651797/194388159-ec7ab2f4-d7b7-47a7-93a3-c109f12e6915.png)

## Workaround

Currently I've had to work around this issue by using the `strip_text_ansi` function to replace the exception args before calling the traceback handler.

```py
from beartype import beartype
from beartype.roar import BeartypeException
from beartype._util.text.utiltextcolour import strip_text_ansi
from rich.console import Console

console = Console()

try:
    return func(*args, **kwargs)

except BeartypeException as exc:
    # Beartype applies automatic colouring of exception messages, however this
    # collides with automatic traceback handlers such as `python-rich`. So we
    # strip out the colour codes.
    exc.args = (strip_text_ansi(exc.args[0]),)
    console.print_exception(show_locals=False)

except Exception as exc:
    console.print_exception(show_locals=False)   
```

This results in a much cleaner message;

<img width="880" alt="image" src="https://user-images.githubusercontent.com/651797/194389721-e1b3505a-0049-4352-82a5-45f7deb959b8.png">

## Proposed Solution

How would you feel about having a flag which makes message colouring in BearType exception messages optional?

Or perhaps a section in the README which has a quick copy/paste monkeypatch which sets all the beartype ANSI variables to empty strings?

Certainly open to other ideas here too, including pushing this problem upstream, although one may argue that the ability to disable colour without relying on `tty` detection could be useful for beartype users.

**Comment by foxx** [comment]
Absolute legend, thank you for patching this so quickly!

**Comment by leycec** [comment]
**Resolved by 6be82a7.** IPython tells the truth even if @leycec never does:

```python
# Import the requisite machinery.
>>> from beartype import beartype, BeartypeConf

# Disable color.
>>> @beartype(conf=BeartypeConf(is_color=False))
... def monochrome_dreams() -> None:
...     return 'A beautiful bluebird came flying down'

# @beartype will now raise monochrome violations. \o/
>>> try:
...     monochrome_dreams()
... except Exception as exception:
...     exception_message = str(exception)
>>> exception_message
'@beartyped __main__.monochrome_dreams() return \'A beautiful bluebird came flying down\' violates type hint None, as str 'A beautiful bluebird came flying down' not instance of <class "builtins.NoneType">.'

# Prove we actually do what we say we're doing.
>>> @beartype
... def prismatic_dreams() -> None:
...     return 'My eyes caught the color, as it lead me down the road'
>>> try:
...     prismatic_dreams()
... except Exception as exception:
...     exception_message = str(exception)
>>> exception_message
'@beartyped __main__.monochrome_dreams() return \x1b[33m\'A beautiful bluebird came flying down\'\x1b[0m violates type hint \x1b[1m\x1b[34mNone\x1b[0m, as \x1b[1m\x1b[31mstr\x1b[0m \x1b[33m\'A beautiful bluebird came flying down\'\x1b[0m not instance of \x1b[1m\x1b[34m<class "builtins.NoneType">\x1b[0m.'
```

Note the horrid wall of ANSI in the latter but *not* the former case. Astute readers may now be thinking to themselves:

> B-b-but... I don't wanna type `@beartype(conf=BeartypeConf(is_color=False))` everywhere!

Fear not, astute readership. @beartype still got your back. <sup>*apparently that's a good thing*</sup>

The object returned by calling `beartype(conf=BeartypeConf(is_color=False))` is itself a decorator you can use everywhere in place of `@beartype`: e.g.,

```python
# Import the requisite machinery.
from beartype import beartype, BeartypeConf

# Monochrome @beartype decorator.
monobeartype = beartype(conf=BeartypeConf(is_color=False))

# Use @monobeartype everywhere you previously used @beartype.
@monobeartype
def monochrome_dreams() -> None:
    return 'A beautiful bluebird came flying down'
```

:partying_face:

**Comment by foxx** [comment]
Outstanding, thank you @leycec !

**Comment by leycec** [comment]
Oh, you're most welcome. I'm currently putting the finishing touches on [public documentation for beartype's configuration API](https://github.com/beartype/beartype#beartype-configuration) – including both `is_color` and a [comparable new `is_pep484_tower` setting](https://github.com/beartype/beartype/issues/174). Once finalized, I'll happily push out a new `beartype 0.12.0` release.

Let's see if this magic happens by Halloween. The Pumpkin King is optimistic. :jack_o_lantern:
