### ISSUE TITLE
[Feature Request] BeartypeException object metadata

### ISSUE THREAD

**Issue by Jasha10** [beartype/beartype#180]
Hello hello @leycec!

I have an idea to improve the debugging experience by adding metadata to beartype's exceptions. In a nutshell the proposal is to add attributes to the raised `beartype.roar.BeartypeException` instance so that, with a `try: ... except`, it's easy to inspect the inputs and beartyped function that caused the exception.

#### Motivating example
Here's a typical beartype exception:
```python
beartype.roar.BeartypeCallHintParamViolation: @beartyped my_module.MyClass.__init__() parameter my_array="array([[False, False],
       [False, False],
       [ True, False],
       [ True, False],
... violates type hint NArray[Shape['11 foo'], bool], as <protocol "numpy.ndarray"> "array([[False, False],
       [False, False],
       [ True, False],
       [ True, False],
... not instance of <class "ntyping.common.NArray[Shape['11 foo'], bool]">.
```
(for context, `ntyping` is my personal fork of [`ramonhagenaars/nptyping`](https://github.com/ramonhagenaars/nptyping).)

To debug this error, I need to know the shape and dtype of the `my_array` array. This would be easy if the `BeartypeCallHintParamViolation` exception instance would expose an interface for accessing the `my_array` argument:
```python
try:
    ...  # bad code
except roar.BeartypeCallHintParamViolation as exc:
    bad_arg = exc.interface_exposing_the_input_that_violated_your_type_hint
    print(f"{bad_arg.shape=}")
    print(f"{bad_arg.dtype=}")
    ...
```

---

Of course, simply calling `pdb.post_mortem()` in the `except` block works well enough. Also, I know that implementing something like this might have implications for e.g. memory usage; perhaps keeping a reference to `my_array` in the exception object will prevent that array from being garbage collected. There might be other tradeoffs I'm not aware of. Anyway, I wanted to throw this idea out there; do with it what you will :P

**Comment by leycec** [comment]
**Excellent request is excellent.**

> `ntyping` is my personal fork of [ramonhagenaars/nptyping](https://github.com/ramonhagenaars/nptyping)

![true heroism](https://media.tenor.com/5UQfISvkv1YAAAAC/heroes-thor.gif)

> To debug this error, I need to know the shape and dtype of the `my_array` array.

@beartype let us all down here. Actually, I blame NumPy. What's up with that `repr()` string, NumPy? A sane NumPy would print the shape and dtype in its `repr()` strings. Sadly, we live in the bad timeline.

In theory, yet another alternative to `pdb` madness would be to [subclass `numpy.ndarray` with your own debugging-specific subclass that defined a sane `__repr__()`](https://numpy.org/doc/stable/user/basics.subclassing.html)... *is what I would be saying to you if NumPy was sane.* But we've already established that NumPy is less sane than we prefer. In practice, NumPy wasn't designed to support object-oriented subclassing. :feelsgood: 

That means @beartype needs to do something to help you. B-b-but...

> ...perhaps keeping a reference to `my_array` in the exception object will prevent that array from being garbage collected.

Indeed, that is the case. Thankfully, Python silently attaches a public `__traceback__` instance variable to every exception enabling you to programmatically inspect the entire call stack (including the `my_array` object responsible for this violation) **but only for the short duration of the `except ...:` clause catching that exception (to avoid aforementioned garbage collection entanglements):** e.g.,

```python
from beartype import beartype
from beartype.roar import BeartypeCallHintViolation
from numpy import ndarray, array

@beartype
def shes_gonna_blow_captain(my_array: ndarray) -> int:
    return my_array

try:
    shes_gonna_blow_captain(array((1, 0)))
except BeartypeCallHintViolation as exc:
    func_frame_wrapper = exc.__traceback__.tb_next.tb_frame
    func_locals = func_frame_wrapper.f_locals
    my_array = func_locals['args'][0]
    print(f'dtype: {my_array.dtype}, shape: {my_array.shape}\n')
    raise
```

...which helpfully prints:

```
dtype: int64, shape: (2,)

Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 12, in <module>
    shes_gonna_blow_captain(array((1, 0)))
  File "<@beartype(__main__.shes_gonna_blow_captain) at 0x7fee21deecb0>", line 40, in shes_gonna_blow_captain
beartype.roar.BeartypeCallHintReturnViolation: @beartyped __main__.shes_gonna_blow_captain() return "array([1, 0])" violates type hint <class 'int'>, as <protocol "numpy.ndarray"> "array([1, 0])" not instance of int.
```

I admit that whole `my_array = func_locals['args'][0]` part conditionally depends on your calling convention and is thus extremely smelly. Still... what you want *is* technically available without me needing to break @beartype over my knee. :sweat_smile:

**Comment by leycec** [comment]
Alternately, @beartype could publicly expose a **weak reference** to the object responsible for a type-checking violation. This would require you to keep around a global reference to that object (e.g., to prevent Python from prematurely garbage collecting that object before you get a chance to debug it). That's a deal breaker for many use cases.

Still, would you be interested in something like that? I'd be happy to make that happen when I find a spare free weekend lying around. A typing enthusiast can dream. :grin:

**Comment by Jasha10** [comment]
Thanks so much for sharing your knowledge about working with tracebacks, @leycec. Working directly with the traceback frames certainly does cover this use-case.

Exposing a `culprit` instance variable on the exception classes certainly *would* be convenient. I must admit that I feel guilty about adding things to your todo list, which is no-doubt lengthy already.

In your estimation, would adding a `culprit` instance variable to `BeartypeCallHintViolation` be difficult? Would this be a "good first issue" for _someone like me_ to take a stab at?

**Comment by leycec** [comment]
Oh, you're most welcome. And thank *you* so much for the spirited interest! 2022 ain't seen nuthin' yet. :smile_cat: 

> In your estimation, would adding a `culprit` instance variable to `BeartypeCallHintViolation` be difficult?

**Easy-peasy,** which leads us to...

> Would this be a "good first issue" for someone like me to take a stab at?

Yes! Yes! So much "Yes!" If you find a spare hour or two to hurl into the purgatorial fires that are @beartype development, please do:

1. Define a new `BeartypeCallHintViolation.culprit` instance variable in the existing `beartype.roar._roarexc` submodule, passed at instantiation time to the `BeartypeCallHintViolation.__init__()` method as a mandatory `culprit` parameter. For safety, this parameter should be validated to be an instance of either `weakref.ProxyType` or `weakref.CallableProxyType` from the standard library: e.g.,

```python
# In "beartype.roar._roarexc"...
from typing import Union
from weakref import ProxyType, CallableProxyType

_PROXY_TYPES = (ProxyType, CallableProxyType)
'''
Tuple of the types of all objects created and returned by the
:func:`weakref.proxy` factory function.
'''

class BeartypeCallHintViolation(BeartypeCallHintException):
    '''
    Abstract base class of all **beartyped callable type-checking violations.**

    Instances of subclasses of this exception are raised from wrapper functions
    generated by the :func:`beartype.beartype` decorator when either passed a
    parameter or returning an object whose value is of **unexpected
    PEP-compliant type** (i.e., violating a PEP-compliant type hint annotated
    for that parameter or return value).
    '''

    # ..................{ INITIALIZERS                       }..................
    def __init__(
        self,
        message: str,
        culprit: Union[ProxyType, CallableProxyType],
    ) -> None:
        '''
        Initialize this exception.

        Parameters
        ----------
        message : str
            Human-readable message describing this exception.
        culprit : Union[ProxyType, CallableProxyType]
            **Weak reference proxy** (i.e., object created and returned by the
            :func:`weakref.proxy` factory function) safely referring to the
            **culprit** (i.e., object violating the PEP-compliant type hint
            annotating a parameter passed to *or* object returned from the
            wrapper function generated by the :func:`beartype.beartype`
            decorator raising this exception).

            As the name implies, this proxy transparently proxies this culprit
            and is thus usable exactly as this culprit is usable. This proxy is
            guaranteed to safely refer to this culprit for the duration of the
            ``except ...:`` block directly catching this exception. However,
            this culprit may be garbage-collected at any time thereafter; this
            proxy is *not* guaranteed to safely refer to this culprit outside of
            that block. This proxy should thus *only* be accessed inside the
            ``except ...:`` block directly catching this exception.
        '''

        # Initialize the superclass with the passed message.
        super().__init__(message)

        # If this culprit is *NOT* a weak reference proxy, raise an exception.
        if not isinstance(culprit, _PROXY_TYPES):
             raise _BeartypeCallHintPepRaiseException(
                 f'Culprit {repr(culprit)} not weak reference proxy.')
        # Else, this culprit is a weak reference proxy.

        # Classify this weak reference proxy.
        self.culprit = culprit
```

2. In the existing `beartype._decor._error.errormain` submodule...
3. In the existing `get_beartype_violation()` function...
4. Where the `exception` object returned by that function is instantiated...
5. Pass a new weak reference proxy to this culprit: e.g.,

```python
# In "beartype._decor._error.errormain"...
from weakref import proxy

def get_beartype_violation(
    ...

    # Exception of the desired class embedding this cause.
    exception = exception_cls(  # type: ignore[misc]
        message=exception_message,
        culprit=proxy(pith_value),
    )
```

Then **glory unfolds.** Bask in the vast radiance of a newly debuggable @beartype! :sun_with_face:

**Comment by Jasha10** [comment]
I have a feeling in my bones that I'll find a spare free weekend lying around some time soon. _Leave it to me :D_

**Comment by leycec** [comment]
The future of typing itself now lies in your capably outstretched arms. Reach for your very destiny! :magic_wand: :star2:

**Comment by leycec** [comment]
**Oh ho ho.** I'm currently digging deep into this ancient feature request, which resonates into the future like a time capsule from a Halcyon Age long past.

Implementing this is proving surprisingly non-trivial. It's just as well that nobody did nuthin' until now. Laziness prevails, friends. Nonetheless, this is slated for our upcoming @beartype 0.12.0 release. Let's see what Santa Bearclaws brings to nice Pythonistas who deserve something more than coal for once this Christmas. :santa:

**Comment by Jasha10** [comment]
Hooray!

**Comment by leycec** [comment]
**Joyous New Year's!** 2022 happened – and @beartype did something about it in a2ca015.

In 2022, I resolved this at a growing cost to my bald patch that is now spreading outward like a mild fungal growth you do *not* talk about. In 2023, you too will be able to inspect the exact culprit(s) responsible for your type-checking violations. The [documentation is voluminous and has puns, so please read it](https://github.com/beartype/beartype#BeartypeCallHintViolation). But *nobody* (including me) reads a sprawling mess of single-page gibberish that burns the eyes, so here's the ~~5-second~~ 500-second **tl;dr:**

* The `beartype.roar.BeartypeCallHintViolation` exception class that is the root of all type-checking exceptions now defines a read-only `culprits` property.
* The value of the `culprits` property is guaranteed to be a non-empty tuple containing, for each object responsible for a type-checking violation:
  * If that object can be weakly referenced *and* that object is still alive, that object. In other words, you do *not* need to explicitly dereference weak references. Praise be to the `culprits` property!
  * If that object cannot be weakly referenced *or* that object is now dead, the `repr()` of that object taken prior to its death. Since this is only a last-ditch fallback to assist in runtime debugging, a `repr()` is better than nothing. In other words, you do *not* need to worry about unexpected exceptions when accessing the `culprits` property. Praise be to the `culprits` property!
* If the root object responsible for this type-checking violation is a standard container (e.g., `dict`, `list`), the value of the `culprits` property is a 2-tuple `(root_culprit, leaf_culprit)`, where:
  * `root_culprit` is that container.
  * `leaf_culprit` is the actual nested item of that container that violated this type-check.
* Else, the value of the `culprits` property is a 1-tuple `(culprit)`.

If this confuses you, then you're like me. A minimal-length example will shed light into the darkness of our mutual ignorance:

```python
from beartype import beartype
from beartype.roar import BeartypeCallHintViolation

class SpiritBearIGiveYouSalmonToGoAway(object): pass
class SpiritBearIGiftYouHoneyNotToStay(object): pass

SPIRIT_BEAR_REFUSE_TO_GO_AWAY = SpiritBearIGiftYouHoneyNotToStay()

@beartype
def when_spirit_bear_hibernates_in_your_bed(
    best_bear_den: SpiritBearIGiveYouSalmonToGoAway) -> None: pass

# MAGIC HAPPENS HERE. Catch exceptions and inspect their "culprits"!
try:
    when_spirit_bear_hibernates_in_your_bed(SPIRIT_BEAR_REFUSE_TO_GO_AWAY)
except BeartypeCallHintViolation as exception:
    # Assert that exactly one culprit was responsible for this exception.
    assert len(exception.culprits) == 1

    # Culprit of this exception.
    culprit = exception.culprits[0]

    # Assert that this culprit is the same object passed to this function.
    assert culprit is SPIRIT_BEAR_REFUSE_TO_GO_AWAY
```

2023: *you are officially on notice.* `\o/`

**Comment by Jasha10** [comment]
Praise be to the `culprits` property!
