### ISSUE TITLE
beartype gets angry at jax.lax.scan

### ISSUE THREAD

**Issue by murphyk** [beartype/beartype#183]
This fails (also with typeguard).
The error is 
```
beartype.roar.BeartypeCallHintParamViolation: @beartyped namedtuple_Params.Params.__new__()
 parameter mean="Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=1/0)>" 
violates type hint <class 'float'>,
 as <protocol "jax.interpreters.partial_eval.DynamicJaxprTracer"> 
"Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=1/0)>" not instance of float
```

(The code work fine without the `@typechecker` decorator.)
I think the problem is that jax can call functions with traced types, when used inside jit or lax.scan,
which are not compatible with the user-specified types. 
Does this means that dynamic typing cannot be used with jax?  :(

```
from jax import lax
import jax.numpy as jnp
from beartype import beartype as typechecker
#from typeguard import typechecked as typechecker
from jaxtyping import Array, Float, jaxtyped
from typing import NamedTuple, Union, Optional

@typechecker
class Params(NamedTuple):
    mean: float

def step(carry, t):
    p = Params(mean=t)
    return carry, p

carry = (0.0)
step(carry, 42.0) # ok

carry , params = lax.scan(step, carry, jnp.arange(0, 3, dtype=float)) # fail

```

@slinderman @patrick-kidger

**Comment by patrick-kidger** [comment]
Replace the `float` with a `Float[Array, ""]`?

Or a `Union` of the two if you want to allow both.

**Comment by murphyk** [comment]
Yes I tried that
```
Scalar = Union[float, Float[Array, ""]] # python float or scalar jax device array with dtype float

@typechecker
class Params(NamedTuple):
    mean: Scalar
```
but now I get the error 
```
beartype.roar.BeartypeCallHintParamViolation: @beartyped namedtuple_Params.Params.__new__()
 parameter mean="DeviceArray([0., 1., 2.], dtype=float32)" violates 
type hint typing.Union[float, jaxtyping.Float[Array, '']], as <protocol "jaxlib.xla_extension.DeviceArray">
 "DeviceArray([0., 1., 2.], dtype=float32)" not <class "jaxtyping.Float[Array, '']"> or float.
```
I guess this is because lax.scan accumulates the results in the leaves of a pytree, since the return value (without type checking) is
```
Params(mean=DeviceArray([0., 1., 2.], dtype=float32))
```
If I redefine it to 
```
@typechecker
class Params(NamedTuple):
    mean: Union[Scalar, Float[Array, "dims"]]
```
then it works.

So I guess this is not a beartype bug, but a logic bug on my side...

**Comment by leycec** [comment]
**Phew!** Laziness prevailed. Before I read and understood the discussion, the dust had settled.

This is the way every issue should be. Thanks so much for all your awesome interest in @beartype, @murphyk. I promise you that @beartype will eventually play nicely with JAX. Until then, please continue to keep us apprised of all the badness you uncover in your probabilistic ML journeys. :face_with_thermometer:
