### ISSUE TITLE
could die_if_unbearable return the original object?

### ISSUE THREAD

**Issue by hhoeflin** [beartype/beartype#208]
Hi,

thanks for beartype, a very nice library. I was using die_if_unbearable in the context of h5py, so for example I wanted
```
f['mydataset'][index]
```
where f is and h5py.Group object. The current issue is that f['mydataset'] could not only return a h5py.Dataset, but also a h5py.Group and some other objects. So I wanted to wrap it in die_if_unbearable like so
```
die_if_unbearable(f['mydataset'], h5py.Dataset)[index]
```
however, which does not work as die_if_unbearable returns `None`. Would it be possible to let die_if_unbearable return the original object with TypeVar type hinting to that effect?

Thanks!

**Comment by hhoeflin** [comment]
Hmmm, seems like I actually misunderstood how this can be used. Sorry. closing.

**Comment by leycec** [comment]
Thanks for the kindest words! I must confess that I am dumb and thus fail to understand, but I'd be delighted to help @beartype help you help @beartype help y– **`RecursionError`** in whatever way we can. `h5py` is a fascinating beast that @beartype can (*probably*) tame for you.

Just ping me again here or under another issue if you think up anything else! Until then, may the well-annotated codebase be with you always. :smile:
