### ISSUE TITLE
Feature request: support `TypeGuard`

### ISSUE THREAD

**Issue by patrick-kidger** [beartype/beartype#221]
Presumably this is a known limitation, so I'm just registering my interest in supporting this annotation.

```python
from beartype import beartype
from typing import TypeGuard

@beartype
def f(x) -> TypeGuard[int]:
    return True

# beartype.roar.BeartypeDecorHintPepUnsupportedException: @beartyped __main__.f() return type hint typing.TypeGuard[int] currently unsupported by @beartype.
```

Not too big of a deal as I can work around this with a
```python
if not TYPE_CHECKING:
    class TypeGuard:
        def __class_getitem__(cls, item):
            return bool
```

**Comment by leycec** [comment]
**Resolved by 3d552ab.** As this video snapshot of someone like me demonstrates, it's happening.

![happening](https://media.tenor.com/xVDx_aPbtC0AAAAS/idk-mind.gif)

Thanks again for your tremendous outpouring of interest, @patrick-kidger. You rock Google X. :brain:
