### ISSUE TITLE
[Feature Request] `beartype.door.die_if_unbearable()` + `typing.TypeGuard` integration

### ISSUE THREAD

**Issue by skeggse** [beartype/beartype#265]
I think it'd be super neat if beartype provided a way to assert that a value matched a particular type definition, and made that clear to typecheckers via `TypeGuard` or similar mechanisms. Right now, I can use `is_bearable` to refine the type based on branching, but I'd love to just `die_if_unbearable` and have the type checker know that we now have confidence that `value` is of a particular type!

ref https://github.com/beartype/beartype/issues/139 + https://github.com/beartype/beartype/issues/255

**Comment by leycec** [comment]
**So much agreement.** It would be *wonderful* if somebody is not me standardized a new `typing.TypeWall` type hint with a new PEP. Whereas `typing.TypeGuard[...]` instructs a static type-checker that an object satisfies a type hint *inside* an `if` conditional branch, `typing.TypeWall[...]` would similarly instruct a static type-checker that an object satisfies a type hint *after* a call to a callable typed as returning `typing.TypeWall[...]`.

A bear bro can dream. Until then, I eat five day-old refried pizza. :yum:

**Comment by leycec** [comment]
**Ugh.** It deeply saddens me to close this issue out unresolved, but... *yeah.* Python leaves us little choice here. It's unlikely that `typing` devs intend to do what we want; they're mostly mono-focused on pure-static type-checking, despite the year currently reading 2024. I grunt in consternation.

This issue tracker has become a festering hive of bugs and feature requests. In a futile effort to restore a modicum of hygiene, let's quietly close this and pretend `typing.TypeGuard[...]` actually did something useful. More grunting in consternation. :face_exhaling:

**Comment by skeggse** [comment]
I too have such a hard time closing an issue as wontfix! I agree that this is an upstream issue, and I appreciate your focus!
