### ISSUE TITLE
Beartype 0.16.0 does not play nicely with PyTorch.

### ISSUE THREAD

**Issue by dcharatan** [beartype/beartype#282]
Whenever beartype 0.16.0 is installed in a virtual environment and a script that imports PyTorch is run, the following error occurs:

```
BeartypeDecorHintPep484Exception(
beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).
```

This could be an issue with PyTorch, but I figured it would be worth posting here, since:

1.  Beartype's maintainers are probably in a better position to diagnose the issue.
2. The issue is likely to affect a noticeable number of beartype's users.

# Reproducing the Error

```
python3 -m venv venv
source venv/bin/activate
pip install torch torchvision torchaudio beartype
python3 -c "import torch"
```

# Environment

I tested this on the following environments:

## Mac

* Python 3.10.9
* MacOS Ventura 13.2 (22D49)
* Output of `pip freeze`:

```
beartype==0.16.0
certifi==2023.7.22
charset-normalizer==3.2.0
filelock==3.12.4
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
Pillow==10.0.1
requests==2.31.0
sympy==1.12
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
typing_extensions==4.7.1
urllib3==2.0.4
```

## Ubuntu

* Python 3.10.12
* Ubuntu 22.04.3 LTS
* Output of `pip freeze`:

```
beartype==0.16.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.5
filelock==3.12.4
idna==3.4
Jinja2==3.1.2
lit==16.0.6
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
Pillow==10.0.1
requests==2.31.0
sympy==1.12
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
triton==2.0.0
typing_extensions==4.7.1
urllib3==2.0.4
```

# Full Error Output

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/torch/__init__.py", line 1239, in <module>
    from torch import onnx as onnx
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/torch/onnx/__init__.py", line 12, in <module>
    from . import (  # usort:skip. Keep the order instead of sorting lexicographically
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/torch/onnx/symbolic_caffe2.py", line 4, in <module>
    from torch.onnx import symbolic_helper, symbolic_opset9 as opset9
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 611, in <module>
    def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 98, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 147, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 178, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 242, in beartype_func
    func_wrapper_code = generate_code(bear_call)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 187, in generate_code
    code_check_return = _code_check_return(bear_call)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 669, in _code_check_return
    reraise_exception_placeholder(
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/error/utilerror.py", line 214, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 618, in _code_check_return
    ) = make_func_wrapper_code(hint_sane, bear_call.conf, cls_stack)  # type: ignore[assignment]
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_decor/wrap/_wrapcode.py", line 86, in make_func_wrapper_code
    ) = make_check_expr(hint, conf, cls_stack)
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_check/code/codemake.py", line 706, in make_check_expr
    die_if_hint_pep_unsupported(
  File "/home/charatan/Downloads/venv/lib/python3.10/site-packages/beartype/_util/hint/pep/utilpeptest.py", line 205, in die_if_hint_pep_unsupported
    raise BeartypeDecorHintPep484Exception(
beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).
```

**Comment by Volcomix** [comment]
Happens to me on a fresh colab notebook: https://colab.research.google.com/drive/1sQ6vWAx695ctZsOFFN7ryLUPIjo-4DJO?usp=sharing

**Comment by rsxdalv** [comment]
I have users reporting this as causing issues on Windows, Mac, Linux and Google Colab.
This relates to:
https://github.com/rsxdalv/tts-generation-webui/issues/179
https://github.com/rsxdalv/tts-generation-webui/issues/178
https://github.com/rsxdalv/tts-generation-webui/issues/177
https://github.com/rsxdalv/tts-generation-webui/issues/175

**Comment by justinchuby** [comment]
cc @bowenbao

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/blob/591c01995b8d052ec9a960456d2748275b940c5d/torch/onnx/symbolic_helper.py#L610-L622

**Comment by leycec** [comment]
**Gah!** @beartype broke PyTorch. I didn't even think that was possible. Welp, there goes Monday... and Tuesday... and, *ohgodswhathaveidone.*

Odd that @beartype's unit tests all pass. Odder even that this PyTorch function declaration appears to be the culprit:

```python
def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
```

Clearly, that's fine. Clearly, @beartype must thus be non-fine. Wish me luck, all! I'm going in deep. <sup>*/puts on oven mits*</sup>

**Comment by leycec** [comment]
**Indeed.** As expected, @beartype *does* correctly handle `typing.NoReturn`, because @beartype has correctly handled `typing.NoReturn` for two or three or years. That certainly hasn't changed with @beartype 0.16.0. B-b-but... *what could the truth be?* And can we even handle that truth?

The issue appears to be the full declaration for this and other PyTorch functions throughout the `pytorch.onnx` subpackage:

```python
@_beartype.beartype
def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
```

I spy with my little rheumy eye... `@_beartype.beartype`! I see you over there lurking in the shadows with a bloody dagger behind your back.

What the heck is *that*!? That's *not* official @beartype stuff. That's some private PyTorch-specific decorator defined by the `torch.onnx._internal._beartype` submodule. There's a shockingly dark voodoo going on in that submodule. I see a darkness and it scares me.

## PyTorch: Yer Breakin' Mah Heart Here

@justinchuby: I vaguely recall you mentioning something about `torch.onnx._internal._beartype`. If I recall correctly, PyTorch desperately needed @beartype to implement **gradual typing** (i.e., to emit non-fatal warnings rather than raise fatal exceptions on type-checking violations). Naturally, @beartype never did that. Instead, @beartype did other stuff... *and here we are.*

Specifically, [your `_create_beartype_decorator()` function internally defines and returns a fake `@beartype` decorator whose implementation seems *possibly* problematic](https://github.com/pytorch/pytorch/blob/2c1554a0323107d821be3ff13df7833b9f0b960d/torch/onnx/_internal/_beartype.py#L74):

```python
def _create_beartype_decorator(
    runtime_check_state: RuntimeTypeCheckState,
):
    ...
    def beartype(func):
        ...
        if "return" in func.__annotations__:
            # Remove the return type from the func function's
            # annotations so that the beartype decorator does not complain
            # about the return type.
            return_type = func.__annotations__["return"]
            del func.__annotations__["return"]
            beartyped = _beartype_lib.beartype(func)
            # Restore the return type to the func function's annotations
            func.__annotations__["return"] = return_type
        else:
            beartyped = _beartype_lib.beartype(func)
        ...
```

That looks kinda sus to me. Kinda?

Long-term, this issue strongly suggests that **@beartype really needs to support gradual typing.** PyTorch needs that – and that's *not* really something that can be safely bolted onto the side of @beartype as PyTorch is currently trying (but probably failing) to do.

Short-term, let's try surgically hacking apart `torch.onnx._internal._beartype`. If I cut it enough, it will bleed. If I bleed it enough, it will cough up a short-term resolution that will at least get us past the pre-surgical explosive pain and into the post-surgical total numbness where we want to be.

**Comment by leycec** [comment]
**OHGODS.** Belay the prior comment. This is entirely @beartype's fault. I think. Maybe.

@justinchuby: You are doing `from __future__ import annotations`. You are doing PEP 563. So *that's* it. @beartype 0.16.0 significantly "improved" its handling of PEP 563. Of course, I broke something and didn't even know I broke something. Unit tests were insufficient. To explain what is happening here:

1. `torch.onnx.*` submodules enable `from __future__ import annotations` everywhere.
1. Python implicitly stringifies the `NoReturn` type hint annotating your `_onnx_unsupported()` function to the string `"NoReturn"`.
1. @beartype erroneously detects the `NoReturn` type hint *before* destringifying type hints. Naturally, the `NoReturn != `"NoReturn"`.

## The 5-Minute Plan: It's a Good Plan

Clearly:

1. @beartype should instead detect the `NoReturn` type hint *after* destringifying type hints.
2. A new PEP 563-specific unit test exercising this should be added.
3. A new @beartype 0.16.1 patch release should be immediately pushed out.

![](https://media.tenor.com/3q05lwfa4KAAAAAC/bryan-cranston-oh-dear-god.gif)
<sup>convey my feels, bryan cranston.</sup>

**Comment by leycec** [comment]
**Resolved by c8feb04.** After CI passes in a hot minute, I'll immediately push this out as @beartype 0.16.1.

Dare we pretend that @beartype 0.16.0 never happened, Microsoft? *Oh, we dare.* `</facepalm>`

**Comment by leycec** [comment]
*Aaaaaaaaaaand...* @beartype 0.16.1 has landed with a wet plopping sound. @beartype 0.16.1 should no longer be busted for PyTorch. If the words I am speaking are actually true, consider **(A)** unpinning and **(B)** requiring @beartype ≥ 0.16.1 with my abject apologies.

I am so sorry, everyone. I broke the AI. :sob:

**Comment by justinchuby** [comment]
That was very fast. Thank you so much @leycec !!
