### ISSUE TITLE
[Bug] PEP 563 + PEP 604 + Python 3.9 = :boom: 

### ISSUE THREAD

**Issue by tvdboom** [beartype/beartype#300]
For a property setter with signature
```python
    @memory.setter
    @beartype
    def memory(self, value: Bool | str | Path | Memory): ...
```
 I get the following error with Python 3.9:

`beartype.roar.BeartypeDecorHintForwardRefException: Method atom.basetransformer.BaseTransformer.memory() parameter "value" stringified type hint 'Bool | str | Path | Memory' syntactically invalid (i.e., TypeError("unsupported operand type(s) for |: '_UnionGenericAlias' and 'type'")).
`

It works without beartype becasue I use `from __future__ import annotations`. Does beartype not support this? The error dissapears in Python 3.10 (where the pipe operator is supported).

**Comment by leycec** [comment]
**Hoo, boy.** This is an *extremely* esoteric edge case that both fascinates and horrifies me. It requires a perfect storm of PEPs and Python versions, which sadly applies to your use case.

Thankfully, I know exactly why this is happening. When @beartype dynamically evaluates *your* type hints defined in *your* modules that use `from __future__ import annotations`, @beartype does so from *our* module in the @beartype codebase – which, of course, does *not* use `from __future__ import annotations`. This desynchronization between the future imports we use and the future imports you use is the problem. I was ignorant of many things. This was one of them.

I hadn't actually realized that Python's `eval()`, `exec()`, and `compile()` builtins dynamically executed code under the `__future__` imports of the current module calling those builtins – *[but that is exactly what happens](https://docs.python.org/3/reference/simple_stmts.html#future-statements).* To quote the official language reference:

> Code compiled by calls to the built-in functions `exec()` and `compile()` that occur in a module `M` containing a future statement will, by default, use the new syntax or semantics associated with the future statement.

## Nod Like You Pretend You Understand What I'm Saying, People

Thankfully, I also know exactly how to resolve this. First...

```python
# In a new "beartype.peps._pep563.pep563eval" submodule:

# Enable PEP 563.
from __future__ import annotations

def eval_pep563(*args, **kwargs) -> object:
    '''
    Dynamically evaluate the passed string signifying a Python expression
    originally defined under PEP 563 (i.e., ``from __future__ import
    annotations``) and return the resulting expression.
    '''

    # This is so dumb. This is so Python.
    return eval(*args, **kwargs)
```

And then...

```python
# In our existing "beartype._check.forward.fwdhint" submodule:
from beartype.peps._pep563.pep563eval import eval_pep563
...

    # ..................{ RESOLVE                            }..................
    # If the active Python interpreter targets Python < 3.9, this interpreter
    # fails to support all possible annotation-specific syntax possibly required
    # to dynamically evaluate this type hint (e.g., PEP 604-compliant new-style
    # unions). In this case...
    if IS_PYTHON_AT_MOST_3_9:
        try:
            hint_resolved = eval(hint, bear_call.func_wrappee_scope_forward)
        except TypeError as type_error:
            if type_error.startswith('unsupported operand type(s) for |: '):
                 hint_resolved = eval_pep563(
                     hint, bear_call.func_wrappee_scope_forward)
```

I am facepalming. The solution is so painfully dumb. Yet it is guaranteed to work. Therefore, this is me:

![serenity now](https://media.tenor.com/oeTFh5XE6eMAAAAC/facepalm-omg.gif)

**Comment by tvdboom** [comment]
Great! Any idea when the new release with the fix will go out?

**Comment by leycec** [comment]
**Almost immediately.** This is clearly critical. Ideally, I'll drop @beartype 0.16.5 containing basically just this tomorrow evening. Ideally, my hair will grow back. Hopefully, at least one of my ideals will happen.

**Comment by leycec** [comment]
**Yikes.** I threw two hours at this tonight. Alas, I failed. This issue wouldn't budge one iota! The core issue is that PEP 563 is a lie; all it does is reduce your type hints to strings. That's it. It does *not* syntactically enable PEP 604-style new unions (e.g., `int | str`); it simply reduces the useful type hint `int | str` to the useless string `"int | str"`. :face_exhaling: 

Python < 3.10 actually provides *no* means of doing what you want and justifiably expect. Yet again, this is why PEP 563 is bad. In theory, @beartype *could* do what you want and justifiably expect. How? No idea, bro. Nobody has ever done that before. Perhaps @beartype could somehow magically transfom PEP 604-style new unions into their equivalent PEP 484-style old unions. Notably, @beartype could either:

* Somehow manually parse `|`-style syntax in PEP 563-postponed type hints. Without authoring a full-fledged parser, it's unclear whether this is even feasible. It's probably not.
* Somehow transform the abstract syntax tree (AST) during `beartype.claw` import hooks: e.g.,

```python
# In theory, "beartype.claw" could transform this...
from __future__ import annotations
muh_func() -> int | str: ...

# ...into this:
from __future__ import annotations
from typing import Union
muh_func() -> Union[int, str]:
```

That looks trivial – but it's actually *really* non-trivial. Everything in AST Land™ is *really* non-trivial.

## OMG. Python Got Cray-Cray!

In short, this suddenly blossomed into a *massive* amount of open-source volunteerism for an extremely *minimal* real-world benefit. To save both my and your sanity, would you mind simply refactoring your PEP 604-style new unions into PEP 484-style old unions? Specifically:

```python
# Would you mind refactoring this...
    def memory(self, value: Bool | str | Path | Memory): ...

# ...into this?
from typing import Union
...

    def memory(self, value: Union[Bool, str, Path, Memory]): ...
```

The only thing that @beartype can reasonably do here is raise a human-readable exception giving the same exact advice as above. Would that be okay, @tvdboom? And my sincere condolences and apologies to your syntactic cleanliness. I do my utmost to support literally everything – but Python is *not* even throwing me a friggin' bone here.

![](https://media.tenor.com/ST0zLIMhJ1EAAAAC/dr-evil-austin-powers.gif)
<sup>Spit the truth, Dr. Evil.</sup>

**Comment by tvdboom** [comment]
I understand. Unfortunately, it's not only the one example I shared. My whole code base uses the pipe operator, so the only solution I see is dropping support for Python 3.9. Not ideal, but bound to happen at some point (would probably have done it next year since I recently dropped support for 3.8), but I guess it's happening now. Thanks anyway for trying:)

**Comment by leycec** [comment]
Thanks for being so understanding, @tvdboom. I can only apologize profusely and beg you to continue decorating everything with `@beartype`. As promised, commit 6e64bdd6d9c improves `@beartype` to at least raise human-readable exceptions on detecting this sort of runtime discrepancy between PEP 563 and 604 under Python < 3.10: e.g.,

```bash
$ python3.9
>>> from __future__ import annotations
>>> from beartype import beartype
>>> @beartype
... def ohgods(OHGODS: str | bytes) -> str | bytes:
...     return OHGODS
beartype.roar.BeartypeDecorHintPep604Exception: Function
__main__.ohgods() parameter "OHGODS" stringified PEP 604 type hint 'str
| bytes' syntactically invalid under Python < 3.10 (i.e.,
TypeError("unsupported operand type(s) for |: 'type' and 'type'")).
Consider either:
* Requiring Python >= 3.10. Abandon Python < 3.10 all ye who code here.
* Refactoring PEP 604 type hints into equivalent PEP 484 type hints:
  e.g.,
    # Instead of this...
    from __future__ import annotations
    def bad_func() -> int | str: ...

    # Do this. Ugly, yet it works. Worky >>>> pretty.
    from typing import Union
    def bad_func() -> Union[int, str]: ...
```

In your case, simply abandoning Python < 3.10 was probably the smart play. Ain't nobody got time for dead Python versions – especially when Python < 3.10 is so miserably deficient and slow by compare to less dead Python versions. Die, Python 3.9! Die!

Thanks again for being so awesome. *I'm so soooorry.* :sob:
