### ISSUE TITLE
Incompatibility with python_utils ?

### ISSUE THREAD

**Issue by AdrienPensart** [beartype/beartype#316]
Hello,

I am using progressbar2 (https://github.com/wolph/python-progressbar), which uses https://github.com/wolph/python-utils

and I found it was incompatible with beartype / pep warnings, minimal example to reproduce :

```
from beartype import beartype
from python_utils import types

@beartype
def foo() -> types.Optional[types.Iterator]:
    return None

if __name__ == "__main__":
    pass
```

I am not a bear magician, and it seems like some black witchcraft magic is in use with types defined in this library.

**Comment by leycec** [comment]
**Fascinating.** By inspection, it looks like the [`python_utils.types` submodule](https://github.com/wolph/python-utils/blob/develop/python_utils/types.py) is literally just the union of (in order):

1. The third-party `typing_extensions` module, which @beartype definitely supports.
1. The official `typing` module, which @beartype *definitely* definitely supports.
1. The official `types` module, which @beartype really really definitely supports.

In short, @beartype definitely supports `python_utils.types`. Thankfully, the proof is in the greasy Christmas blood pudding. Running the above example under Python 3.12 yields:

```python
/home/leycec/py/beartype/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning:
PEP 484 type hint typing.Iterator deprecated by PEP 585. This hint is scheduled for removal in the first Python
version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than
"typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
```

Allow Santa Bear Claws to now explicate. `python_utils.types.Iterator` is just a trivial alias for `typing.Iterator`, which was deprecated a few years ago by PEP 585 in favour of `collections.abc.Iterator`. To avoid this deprecation, just lightly refactor your code as follows:

```python
from beartype import beartype
from collections.abc import Iterator

@beartype
def foo() -> Iterator | None:  # <-- look, Ma! no deprecations!
    return None

if __name__ == "__main__":
    pass
```

Easy-peasy, right? I'd avoid importing *anything* from `python_utils.types`, frankly. There's *no* demonstrable reason for that submodule to exist in 2024. You also don't need the cumbersome `Optional` type hint factory anymore. Just prefer `|`-delimited unions with the builtin `None` type. If you need the above code to be backward compatible with older Python releases like Python 3.8, consider importing from the forward-compatible `beartype.typing` submodule instead: e.g.,

```python
from beartype import beartype
from beartype.typing import Iterator, Optional

@beartype
def foo() -> Optional[Iterator]:  # <-- deprecations, I demolish you!
    return None

if __name__ == "__main__":
    pass
```

Let us know if @beartype can do anything else for you. Until then, may 2024 shower you with much buff bears and black witchcraft sorcery. :muscle: :bear:
