### ISSUE TITLE
Regarding Python ≥ 3.9 requirement for validators

### ISSUE THREAD

**Issue by rsokl** [beartype/beartype#34]
Heya @leycec, I am excited to be messing around with beartype's new validators! A question about the Python ≥ 3.9 requirement: is there a reason why `typing_extensions.Annotated` cannot be used to enable use of validators with earlier versions of Python? 

I tried rerunning the `polygon_area` example in your readme using `typing_extensions.Annotated`, but ended up eating dirt at the feet of `BeartypeDecorHintNonPepException`.

Congratulations on `0.7.0`!

P.S. in the `polygon_area`, `ndarray` should be `np.ndarray` so that readers don't hit an import error.

**Comment by leycec** [comment]
> ...is there a reason why `typing_extensions.Annotated` cannot be used to enable use of validators with earlier versions of Python?

`</double_facepalm>`

I... *somehow didn't think of the most obvious thing.* Beartype definitely should support the full `typing_extensions` package, but currently doesn't do to asinine assumptions I made a year ago in the private `beartype._util.hint.pep.utilhintpepget.get_hint_pep_sign()` function we internally use to classify incoming type hints. Just **"Blurgh!"**

I consider this a critical issue – especially with validators now locked behind a Python version most users won't even be able to readily use for another year or two. Let's see what Uncle Leycec can do for everyone to patch in mostly worky `typing_extensions` support this week.

Thanks for the steady stream of bright ideas, Ryan! You shine a light on the dark spaces in our codebase, which is most of them. :candle: :candle: :candle:

> P.S. in the `polygon_area`, `ndarray` should be `np.ndarray` so that readers don't hit an import error.

@rsokl the MVP (Most Valuable Pythonista) right here. Let's fix that before I embarrass myself any further. :sweat:

**Comment by leycec** [comment]
*"Well, that escalated quickly."* — Ron Burgundy

After a ludicrous chain of 24 codebase-breaking commits, commit 25 finally restores the ignominious `fix-34` branch to worky and has thus been merged into mainline.

**Behold, data science goodfellows!** The upcoming `beartype 0.8.0` (...to be released shortly, for certain definitions of "shortly") now globally supports *all* `typing_extensions` attributes across *all* Python versions, which means beartype validators are now universally usable:

```
$ ipython3.8
>>> from beartype import beartype
>>> from typing_extensions import Annotated
>>> @beartype
... def muh_func(muh_annotated_str: Annotated[str, 'Holy balls.']) -> None:
...    print(muh_annotated_str)
>>> muh_func("I can't believe it's not typing.")
I can't believe it's not typing.
```

Thus ends another frayed neural ganglion of my sanity. :exploding_head:
