### ISSUE TITLE
[Bug] PEP 563 + PEP 604 union + undefined types = :boom: 

### ISSUE THREAD

**Issue by brettc** [beartype/beartype#342]
python: 3.11.2
beartype: 0.17.2

Hi. beartype is very cool, thank you. I'm trying to use it to tame a gigantic hierarchy of generated classes ([see here](https://github.com/stencila/stencila/blob/feat/python-cleanup/python/python/stencila/stencila_types.py)). Here is one of the problems I'm seeing, boiled down to some simple classes.

I think the same issue is causing `cattrs` to fail on structuring too (https://github.com/python-attrs/cattrs/issues/521)

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias

from beartype import beartype


@beartype
@dataclass(kw_only=True)
class A:
    a: str = ""


@beartype
@dataclass(kw_only=True)
class B:
    b: str = ""


@beartype
@dataclass(kw_only=True)
class Yes:
    c: int = 3
    # All good
    a_or_b: A | B | None = None


@beartype
@dataclass(kw_only=True)
class No:
    c: int = 3
    # This passes static type checking but fails with beartype
    # Note the definition is after the class.
    a_or_b: AorB | None = None


AorB: TypeAlias = A | B


@beartype
@dataclass(kw_only=True)
class YesAlso:
    c: int = 3
    # This works though.
    a_or_b: AorB | None = None


def test_beartype_fail():
    Yes(a_or_b=B())
    YesAlso(a_or_b=B())
    #  beartype.roar.BeartypeCallHintForwardRefException: Forward reference tests.test_beartype_fail.A | tests.test_beartype_fail.B not class.
    No(a_or_b=B())
```

**Comment by leycec** [comment]
*ohgods.* But first:

> Hi. beartype is very cool, thank you.

Thanks so much for the kind words! Emoji cat is crying with tears of joy over here. :joy_cat: 

Now, back to our regularly scheduled horrifying issue. So. The worst has finally come to pass. You have invoked the absolute worst case by enabling PEP 563 via `from __future__ import annotations`, defining a PEP 604 union over multiple undefined types, and then annotating a PEP 557 `@dataclass` with that union. We are now off the deep end of type-checking.

Most type-checkers wouldn't even touch something like this with a ten-foot `git` commit. But this is @beartype. We *love* pathological use cases like this. They may be horrifying, but horrifying things get the heart racing and give us a reason to get up in the morning.

## OH. WAITJUSTAMINUTETHERE.

I see what's happening here. This should actually be trivial for @beartype to support. @beartype *basically* already supports this. All we have to do is relax internal constraints on the allowed types of forward references to additionally allow PEP 604 unions.

In theory, trivial. In practice, let's see if I do anything except play video games and pet cats all weekend. :laughing:

**Comment by brettc** [comment]
Thanks for the speedy, informative, and entertaining reply.

> In theory, trivial. In practice, let's see if I do anything except play video games and pet cats all weekend. 😆

That sounds promising. But I hope you went for the cat option.

**Comment by leycec** [comment]
**Resolved by 8e3cef6bb6bb.** Thanks so much for this fascinating edge case that almost destroyed my preciously sanity, @brettc. I see that [you too are a man of `vim` culture](https://github.com/brettc/ivim). Also, [yeasty](https://github.com/brettc/yeasty). Pretty sure that's the best package name ever.

> ...I hope you went for the cat option.

First, I went for the cat option. Then I went for the video game option. Cats then watched video games. Apparently, cats will watch anything if it strobes epileptically enough. Cats: *the mammal that evolutionary selection forgot.* :joy_cat:

**Comment by brettc** [comment]
Thanks for getting to this so quick @leycec. I shall test drive this next week.

I see you are, or were, somehow entangled with the [Levin Lab](https://drmichaellevin.org/resources/software.html#BETSEE). 
Very interesting. And a nice cow, too. Somewhat relatedly, I am writing an evolvable 2d cellular automata in rust/python which may eventually see the light of day.

**Comment by leycec** [comment]
> I see you are, or were, somehow entangled with the [Levin Lab](https://drmichaellevin.org/resources/software.html#BETSEE).

**Yes! So much "Yes!"** You noticed something nobody else ever noticed. Indeed, [my wife's a principal researcher at the Allen Discovery Center at Tufts](https://allencenter.tufts.edu/our-team/alexis-pietak-ph-d/). If there's a beaker foaming over with suspicious chemicals, she's usually holding it.  :woman_scientist:

She's currently polishing up a super-fun upcoming computational paper with Dr. Levin that "lies at the precarious intersection between graph theory and computational biology." I may not understand what that means, but I like what I hear. Despite not understanding, I still want to spill the beans and tell you all about it – but I shouldn't spill the beans. The beans would then smell.

More importantly, Ally would then crucify me live on YouTube.

> an evolvable 2d cell simulation in rust/python which may eventually see the light of day.

**So much fun!** Rust and Python are the places to be. What Python cannot defeat, Python simply absorbs into itself as an extension. Absolutely ping at @leycec when you get that up and publicly flying.

**Relatedly:** let me know if you'd ever like to collaborate with Ally, Dr. Levin, or anyone in either the Levin Lab or Allen Discovery Center at Tufts on papers or software. I'll immediately put you in touch. We stand on the shoulders of giants. But how would Ally feel about being called a "giantess," I wonder? :thinking:

**Comment by brettc** [comment]
> She's currently polishing up a super-fun upcoming computational paper with Dr. Levin that "lies at the precarious intersection between graph theory and computational biology." I may not understand what that means, but I like what I hear. Despite not understanding, I still want to spill the beans and tell you all about it – but I shouldn't spill the beans. The beans would then smell.

This all sounds very interesting. I have wrestled with graphs a bit and love making pretty pictures with them.
 
> **Relatedly:** let me know if you'd ever like to collaborate with Ally, Dr. Levin, or anyone in either the Levin Lab or Allen Discovery Center at Tufts on papers or software. I'll immediately put you in touch. 

Thank you! I have a talk (unpublished) on evolving self-healing patterns that might be of interest to folk in the lab. Basically, I show off some swirly patterns and make outrageous claims. I'll contact you by email...

**Comment by leycec** [comment]
**Hah, hah!** Yes. Oh, yes. Dr. Levin would *definitely* be interested in "evolving self-healing patterns." For one, he's obsessed with patterns. For another, he's obsessed with [self-healing arthrobots](https://www.scientificamerican.com/article/robots-made-from-human-cells-can-move-on-their-own-and-heal-wounds). The intersection of these obsessions is probably a mega-obsession that eclipses all other obsessions.

Oh – and apologies for not replying immediately. I'm a bad human. Specifically, I'm bad at time management. I still have yet to release the `beartype 0.18.0` release I promised the scientific world two weeks ago. And... I probably shouldn't have promised that. Promises will be the death of my social life, which admittedly only consists of my wife and three cats with frighteningly large claws. :smiling_face_with_tear:

**Comment by brettc** [comment]
Arthrobots could definitely be the new Tamagotchis! 

(I emailed you at your gmail address with some more info)
