### ISSUE TITLE
[Bug] PyTorch + `jaxtyping` + @beartype = :boom: ...but it's not our fault, I swear it!

### ISSUE THREAD

**Issue by jaanli** [beartype/beartype#343]
Reproduction script: 

```
import torch 
from torch import nn
from beartype import beartype 
from jaxtyping import Float

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        x = nn.functional.relu(self.conv1(x))
        return nn.functional.relu(self.conv2(x))
    

class BearNet(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    @beartype
    def forward(self, x):
        x = nn.functional.relu(self.conv1(x))
        return nn.functional.relu(self.conv2(x))
    
if __name__ == "__main__":
    net = Net()
    x = torch.randn(1, 1, 28, 28)
    y = net(x)
    print(y)

    model = torch.compile(net)
    y = model(x)
    print(y)

    net = BearNet()
    x = torch.randn(1, 1, 28, 28)
    y = net(x)
    print('with beartype: ', y)

    model = torch.compile(net)
    y = model(x)
    print('with beartype: ', y)
```

First this throws an error that asks for installing something (Mac OS 14):

```
OpenMP support not found. Please try one of the following solutions:
(1) Set the `CXX` environment variable to a compiler other than Apple clang++/g++ that has builtin OpenMP support;
(2) install OpenMP via conda: `conda install llvm-openmp`;
(3) install libomp via brew: `brew install libomp`;
(4) manually setup OpenMP and set the `OMP_PREFIX` environment variable to point to a path with `include/omp.h` under it.
```

After installing libomp: `brew install libomp`, this works. 

However, then this next reproduction script breaks: 

```
import torch 
from torch import nn
from beartype import beartype 
from jaxtyping import Float
from torch import Tensor

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        x = nn.functional.relu(self.conv1(x))
        return nn.functional.relu(self.conv2(x))
    

class BearNet(nn.Module):
    def __init__(self):
        super(BearNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    @beartype
    def forward(self, x):
        x = nn.functional.relu(self.conv1(x))
        return nn.functional.relu(self.conv2(x))
    

class BearNetJaxTyped(nn.Module):
    def __init__(self):
        super(BearNetJaxTyped, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    @beartype
    def forward(self, x: Float[Tensor, "1 1 28 28"]):
        x = nn.functional.relu(self.conv1(x))
        return nn.functional.relu(self.conv2(x))

if __name__ == "__main__":
    net = Net()
    x = torch.randn(1, 1, 28, 28)
    y = net(x)
    print(y)

    model = torch.compile(net)
    y = model(x)
    print(y)

    net = BearNet()
    x = torch.randn(1, 1, 28, 28)
    y = net(x)
    print('with beartype: ', y)

    model = torch.compile(net)
    y = model(x)
    print('with beartype: ', y)

    net = BearNetJaxTyped()
    x = torch.randn(1, 1, 28, 28)
    y = net(x)
    print('with beartype: ', y)

    model = torch.compile(net)
    y = model(x)
    print('with beartype: ', y)
```

Results:

```
  File "/Users/me/projects/phare-sandbox/.venv/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 235, in get
    return eval(name, self.scope, CLOSURE_VARS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
torch._dynamo.exc.InternalTorchDynamoError: '_thread._local' object has no attribute 'value'


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

This script runs fine when disabling beartype:

```
PYTHONOPTIMIZE=1 python test_compile.py
... prints out tensors
```

cc @patrick-kidger as this might be too complicated to support via beartype alone (not sure about how these libraries interface, but they have both been lifesavers!). 

This is also an issue on Ubuntu virtual machines (e.g. on AWS), and on Jupyter notebooks: https://github.com/beartype/beartype/issues/341 (disabling beartype for now works :)

**Comment by patrick-kidger** [comment]
Youch. I'm guessing this might be something to do with one of jaxtyping's threadlocal values [here](https://github.com/patrick-kidger/jaxtyping/blob/main/jaxtyping/_storage.py).

If so then this definitely won't be beartype's fault, and you should be able to reproduce this just by manually doing an `isinstance` check. You could also try going back a few jaxtyping versions (prior to the introduction of some of these threadlocal values) and see if that changes things.

Ultimately it may be wisest to consider this a PyTorch bug (or at least, an unsupported feature). What jaxtyping does is clearly supported by the underlying Python runtime, after all.

**Comment by leycec** [comment]
**Ho, ho, ho.** What is this madness I espy with my lazy eye? I'd *never* have been able to disentangle what was going on here. Like QA Santa Claws, @patrick-kidger dispenses wisdom and workarounds to all GitHubbers who are nice. Truly, a star shone bright when Dr. Kidger was born.

> If so then this definitely won't be beartype's fault

:star_struck: 

> Ultimately it may be wisest to consider this a **PyTorch bug** (or at least, an unsupported feature).

*...hurk.*

@justinchuby: I summon thee from the depths of Redmond. We know you're rather busy bringing about the AGI Singularity, <sup>*...bring it!*</sup> but what do you make of this? Unreadable PyTorch exception messages like `torch._dynamo.exc.InternalTorchDynamoError: '_thread._local' object has no attribute 'value'` suggest a potential incompatibility with thread-local values in other third-party packages like `jaxtyping`. Maybe?

Or maybe it's time for sleep already. Friday night, I'm done with you! :sleepy:

**Comment by justinchuby** [comment]
Hi! I would love to help but I am not familiar with this internal error. If I have to guess, is it this line?

https://github.com/pytorch/pytorch/blob/6d9588a12b5834f29bd8970936749a9725e7f609/torch/_dynamo/guards.py#L316

```python
t = type(self.get(guard.name))
```

and somehow in `eval(name, self.scope, CLOSURE_VARS)` it is trying to access `value` which does not exist?

**Comment by leycec** [comment]
Thanks so much for chiming in, @justinchuby! Indeed, this is an obscure darkness. And thanks a heap for opening up that upstream issue, @jaanli. Someone who is smarter than me <sup>*...so, anybody*</sup> will get to the bottom of this. I am grateful to that person.

Also, @ezyang's [reply](https://github.com/pytorch/pytorch/issues/122093#issuecomment-2005719451):

> beartype 👀

*...heh.* :smiling_face_with_tear:

**Comment by leycec** [comment]
Not even @beartype got time to solve obscure thread-local race conditions in other people's code. We barely stomp on our own bugs here. They chitter, they multiply, and they're literally everywhere. ["The Trouble with Tribbles"](https://www.dailymotion.com/video/x762hcv) was really about @beartype.

As we stand on the threshold of @beartype 0.18.0, let's feel better about doing nothing for this issue by pretending we did something for this issue. If we quietly close this, that's almost as good as doing something. My face is tired. I now lie down. :face_exhaling:
