### ISSUE TITLE
Unexpexted behaivior with type hint `list[Literal[...]]`

### ISSUE THREAD

**Issue by rwiegan** [beartype/beartype#347]
Hey @leycec,

first of all thanks for the nice package!

I encountered some weird behavior since version 0.17.0.
Beartype seems to have a problem detecting the correct input when its hints describe a list of literals.
Here is a short example (using version 0.17.2):

```python
from beartype import beartype
from beartype.typing import Literal, List

@beartype
def do_stuff(a: List[Literal["a", "b", "c"]]):
    print("stuff")
```
```python
do_stuff(["a", "b" , "invalid"])
> ---------------------------------------------------------------------------
BeartypeCallHintParamViolation            Traceback (most recent call last)
Cell In[16], line 1
----> 1 do_stuff(["a", "b" , "invalid"])

File <@beartype(__main__.do_stuff) at 0x7f07381fd7e0>:51, in do_stuff(__beartype_object_139669087268784, __beartype_object_139669087040240, __beartype_object_139669086975792, __beartype_getrandbits, __beartype_get_violation, __beartype_conf, __beartype_func, *args, **kwargs)

BeartypeCallHintParamViolation: Function __main__.do_stuff() parameter a=['a', 'b', 'invalid'] violates type hint list[typing.Literal['a', 'b', 'c']], as list index 2 item str 'invalid' != 'a', 'b', or 'c'.

```
```python
do_stuff(["invalid", "a", "b"])
> stuff
```

```python
do_stuff(["a", "invalid", "b"])
> stuff
```

The behavior overall is inconsistent. Even running the same call multiple times can lead to different results.
I am relatively new to typing, so please let me know if the error is on my side here.

Thanks in advance!

René

**Comment by JWCS** [comment]
On that note, there's 2 scenarios that seem common, that could justify an "in-between" parameterizable level of type checking (when you get around to it): full-fat checking collection of literals and "small flat collection" (for a definition of small; 10? 20?). 
(Mostly overlapping, but a dict with literal keys may justify full-fat key-type-checking, but not full-fat value-type-checking)

**Comment by rwiegan** [comment]
Thanks so much for the quick response and very helpful explanation.
