### ISSUE TITLE
[Feature request/Bug] Yanking releases 0.18.0 and 0.18.1

### ISSUE THREAD

**Issue by RobPasMue** [beartype/beartype#361]
Hi @leycec!

We've been consumers of beartype for several releases already and we are super happy with it! However, we were making use of some forward references on our code and it was causing failures with releases 0.18.0 and 0.18.1 (if I remember properly).

Dependabot opened a PR for using 0.18.2 and it seems that the problems are fixed. I was wondering if you would consider to yank the previous 0.18.0 and 0.18.1 releases so that other projects are not affected (unawarely) of this issue.

In any case, this is more of a suggestion/question rather than an issue - but I did want to throw it out there to you. Nonetheless... congrats for the great work with this library!

Repo using it: https://github.com/ansys/pyansys-geometry

**Comment by leycec** [comment]
Thanks so much for the kind words! Now take all my abject apologies for the slew of dysfunctional 0.18.0 releases, @RobPasMue. Although the @beartype test suite is already 40 thousand lines or so, even that wasn't enough to predict how badly I would break the Python ecosystem over my knee. I laugh. Then I cry. :smiling_face_with_tear: 

Pulling dysfunctional releases is a *great* idea. I should've thought of that. Exactly as you suggest, I'll quietly yank both 0.18.0 and 0.18.1 first thing in the morning. Luckily, the PyPI UI makes this *super* easy. They probably hit this sort of apocalypse a lot.

![](https://media1.tenor.com/m/4F3E7v97K3YAAAAC/no-nooo.gif)
<sup>*@beartype 0.18.0 enters the chat*</sup>

**Comment by RobPasMue** [comment]
That'd be awesome - thanks @leycec for taking into consideration my suggestion. Let me share with you this link that provides some screenshots on how the yanking of a release is performed

https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/
