### ISSUE TITLE
Desynchronization failure with dictionary with tuple keys

### ISSUE THREAD

**Issue by alisaifee** [beartype/beartype#371]
# Description

`beartype.roar._BeartypeCallHintPepRaiseDesynchronizationException` raised when a function returns a dictionary with a tuple as keys.

## Minimal reproduction
```python
import beartype 

def tuple_keys() -> dict[tuple[int, int], int]:
    return {(42,42): 42}

tuple_keys()
```

beartype_version: `0.18.3`

**Comment by leycec** [comment]
**Gah!** Thanks so much for the rapid heads up, @alisaifee. You're awesome sauce. I've locally resolved this and *will* push out a new @beartype 0.18.4 release in a few hours. The accursed @beartype 0.18.X release cycle continues to bedevil our poor world. :hand_over_mouth:

**Comment by leycec** [comment]
**Resolved by fd0096a1a.** Thanks yet again for the super-fast and concise issue, @alisaifee.

@beartype 0.18.4: "Coming right up. In fact, it'll be there by the time you wake up. All *aboooooooard* the Hype Train!" :steam_locomotive: :dash:

**Comment by alisaifee** [comment]
The wabbit(s) are very grateful - in fact specifically to the `0.18.x` series as it has helped uncover many.. many.. badly typed signatures (especially the naughty ones telling lies through `AnyStr`) here at [coredis](https://github.com/alisaifee/coredis/compare/4.16.0...4.17.0). The wabbit(s) are also generally pretty excited about these new improvements (perhaps Spring finally arriving has something to do with their overall enthusiasm.. but who knows what goes on underneath those fluffy ears)

**Comment by leycec** [comment]
You're most welcome, wabbits. :joy: 

And thanks so much for all the kind words from the Land of Wascally Wabbits – which, apparently, is Burnaby. <sup>*...remind me to bring a carrot bag when I visit*</sup> And might I add at this opportune moment that... `coredis` looks *so* hot! **Wow.** I'm stunned at the sheer polish, blood-letting, and sweaty tears that have gone into that thing. Congratulations, for you are about to own Python's in-memory DB space.

> The wabbit(s) are also generally pretty excited about these new improvements...

**Yes!** There's so much fun on the horizon, too. Beartype 0.19.0 will probably bring deep type-checking support for some combination of:

* **Iterable collections** (e.g., `set[...]`, `frozenset[...]`, `collections.abc.Collection[...]`).
* **Recursive type hints** (e.g., `type MuhRecursiveTypeHint = list[MuhRecursiveTypeHint]`).

The future is so bright it blinds even the wabbits currently doing suspicious things in our compost pile.
