### ISSUE TITLE
Decrease the minimum amount for a monthly donation

### ISSUE THREAD

**Issue by Artur-Galstyan** [beartype/beartype#377]
I like this project and want to support it by "buying you a coffee" (i.e. sponsor 3$ per month). But I can't because it says it needs to be 10$ minimum :( I sponsor other projects I use for the same amount and would like to do it here too.

**Comment by leycec** [comment]
Thanks so much for your generous sagacity, @Artur-Galstyan. And may I now take this opportune moment to proudly shout that Hamburg is a *wonderful* port city. I interned at the [Das Technologie-Zentrum Informatik und Informationstechnik (TZI) der Universität Bremen](https://www.uni-bremen.de/tzi) for a summer back when I still had youth and hair. So much love for your incredible nation! :heart_eyes_cat: :de: :heart_eyes: 

Likewise, your *extremely* sensible desire to pump @leycec's stomach full of caffeine and other amped-up neurotransmitters **has now been resolved.** Please feed @beartype any amount of money whatsoever! Honestly, I thought it was always that way. It wasn't – but that was always my intention. In my haste and ignorance, I misconfigured GitHub Sponsors. We now see that the road to poverty is paved with good intentions. :smiling_face_with_tear: 

Thanks so much, again. I *never* would have noticed that if you hadn't kindly mentioned it.

> May you code like the wind for all of your days. For all who crave cranial stimulation, let there be coffee.
> — @leycec, prolly
