### ISSUE TITLE
[Feature Request] Transitive propagation of `@typing.no_type_check` effects across class boundaries in defiance of sanity and static type-checkers: "What could possibly go wrong?" :panda_face: 

### ISSUE THREAD

**Issue by jakelongo** [beartype/beartype#378]
Minimal-ish example

Suppose an awesome third party library contains the following useful class that I can't live without:

```
import typing

@typing.no_type_check
class thirdPartyClass(typing.Mapping[str, typing.Any]):
    def __init__(self):
        self.name = 'my class'

    def __getitem__(self, key: str) -> typing.Any:
        return self.key

    def __iter__(self) -> typing.Iterator[str]:
        return []

    def __len__(self) -> int:
        return 1

    def some_method(self) -> int:
        return 1

    __eq__ = object.__eq__
    __hash__ = object.__hash__
```

I then want to have an instance of that class as an argument to my equally useful function

```
from beartype import beartype

from thirdparty import thirdPartyClass

@beartype
def my_useful_function(arg0: str, arg1: thirdPartyClass):
    arg1.some_method()
    print(arg0)

if __name__ == "__main__":
    a1 = thirdPartyClass()
    my_useful_function("so bearable", a1)
```

I will get hit with the dreaded `#pep-585-deprecations` warnings and I am forced to disable type checking for `my_useful_function` entirely.

It could be the intended behaviour but....not what I expected to happen

**Comment by leycec** [comment]
*...heh.* This is a fun one. If we do what you want us to do, then static type-checkers like mypy and `pyright` will hate us. More specifically, static type-checkers like mypy and `pyright` will hate *you* and the codebase you rode in on. Then, your users will also hate *you* and said codebase.

Here at Barely Beartype Studios, we're prepared for your users to hate you. But we're also concerned that you'll then hate @beartype by the transitive property of hate transference. <sup>*pretty sure that's a thing*</sup>

## ...please stop talking

**Look.** This is what I'm saying here:

```python
from typing import no_type_check

@no_type_check
class Ugh(object): ...

def ugh(arg: Ugh): ...

ugh('Pretty sure not an "Ugh".')
```

Mypy hates that:

```
bodo.py:9: error: Argument 1 to "ugh" has incompatible type "str"; expected "Ugh"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

In other words, the `@typing.no_type_check` decorator does *not* propagate across class boundaries. That decorator *only* affects the contents of the classes and callables it directly decorates. Other callables remain unaffected. This means that both @beartype and static type-checkers like mypy will continue to type-check the `arg: thirdPartyClass` parameter accepted by your `my_useful_function()` function in the standard way – *regardless of whether the `thirdPartyClass` class has been decorated by `@typing.no_type_check` or not.*

## ...i hate you

*...heh.* I accept all your hatred. What choice do I have, anyway!?!?

Seriously, though. Although @beartype could make this happen, @beartype would then be in violation of PEP standards and desynchronized from static type-checkers. That is to say, @beartype would be wrong. @beartype is already wrong about so many things. Let us try to make @beartype right about something for once. :cry: 

> I will get hit with the dreaded `#pep-585-deprecations` warnings and I am forced to disable type checking for `my_useful_function` entirely.

You could do that... *or you could do something better!* That's what I'd do. I'd do the better thing. Specifically, consider:

* **Silencing that warning.** It's only global scope. So, efficiency concerns aren't really a concern. Right? Just tell `@beartype` to stop being so "helpful": e.g.,

```python
from beartype import beartype
from beartype.roar import BeartypeDecorHintPep585DeprecationWarning
from thirdparty import thirdPartyClass
from warnings import catch_warnings

# Totally untested! Totally works! Believe these sweet lies and you will feel happy.
with catch_warnings(action='ignore', category=BeartypeDecorHintPep585DeprecationWarning):
    @beartype
    def my_useful_function(arg0: str, arg1: thirdPartyClass):
        arg1.some_method()
        print(arg0)
```

* **Submitting an upstream issue against that third-party package.** Their package is about to break. Please inform them. They will then thank you and shower you with praise. If they do something else, redirect them here and I'll rectify the situation by publicly shaming them into compliance. No one can withstand the wrath of a thousand anime shitpost memes.

![](https://media1.tenor.com/m/bCBfFjhk8oQAAAAC/kagome-rage.gif)
<sup>fury hath no scorn like a **[**_whatevah's going on here_**]**</sup>

**Comment by leycec** [comment]
*...heh.* Pretty sure I just talked myself out of this feature request. This is a fascinating topic, though. Please do publicly beat my GitHub avatar over the head if there's something reasonable that @beartype *should* be doing here (but is currently *not* doing).

Until then, our emojis can only weep. :cry: :crying_cat_face: :sob:
