### ISSUE TITLE
No love for NotImplemented?

### ISSUE THREAD

**Issue by posita** [beartype/beartype#38]
When overriding binary special methods (e.g., `__eq__`, etc.), returning [`NotImplemented`](https://docs.python.org/3/library/constants.html?highlight=notimplemented#NotImplemented) is a common convention, and generally omitted from returned types. But omitting it doesn't agree with poor old bear:

```python
from beartype import beartype

class Sneetch:
    @beartype
    def __init__(self, star: bool):
        self._upon_thars = star

    @beartype
    def __eq__(self, other) -> bool:
        if isinstance(other, Sneetch):
            return True  # Sylvester McMonkey McBean can pound sand
        else:
            return super().__eq__(other)

assert Sneetch(True) == Sneetch(False)  # all good
assert (Sneetch(True) == 42) is False  # boom
```

This will result in the following:

```python
beartype.roar.BeartypeCallHintPepReturnException: @beartyped Sneetch.__eq__() return "NotImplemented" violates type hint <class 'bool'>, as "NotImplemented" not bool.
```

Making `NotImplemented` an explicit part of the return type is apparently hard (see python/mypy#4791).

I'm not sure what the right play is here. One could probably make a pretty good case that one should omit the `@beartype` decorator and lean on the internals (in which case, this should be closed as not-a-bug). But I thought I'd raise it anyway to get another opinion.

**Comment by leycec** [comment]
**Wow!** You're on a beartype issues roll today. Tell Matt what he's won, folks. It's... it's a Gold Star for Participation. Look, it's all the prize committee could afford. :medal_sports: 

> poor old bear

I chuckled. Then the bear growled and I stopped.

```
# Sylvester McMonkey McBean can pound sand
```

I chuckled even harder. Go pound sand, poor old bear.

*Phew!* I think I got that outta my system. So, your astute observations and keen intuitive sense for hot problem spots in my code are yet again spot on. Mypy (even moreso than official PEP standards) is the de-facto authority on everything typing-related. What mypy does, we do.

You're in luck... *again.* Mypy does [exactly what everyone wants](https://github.com/agronholm/typeguard/issues/178#issuecomment-800123199), which means I now need to ~~disembowel~~ refactor beartype to do exactly the same thing. Specifically, mypy avoids raising warnings or errors for binary dunder methods (and *only* binary dunder methods) both annotated by and returning `NotImplemented`. Unsurprisingly, that's exactly what we'll do too.

It's time to roll up the white-collar tuxedo sleeves and actually do something. :man_in_tuxedo:

**Comment by leycec** [comment]
**Fixed by 57e7e99.** `NotImplemented` singleton: *you have now been implemented.*

Let's now excrete a new stable release containing all of these delectable goodies... and more! :candy:

**Comment by posita** [comment]
> … You're in luck... _again._

For some definition of luck, perhaps. Or maybe the emphasis belongs on recognizing that it was exactly one of us who was lucky here.

> [Mypy does exactly what everyone wants](https://github.com/agronholm/typeguard/issues/178#issuecomment-800123199).

![Oh! Well I guess that's all fixed then.](https://media.tenor.com/images/fa29cdaacc670a17f31b868556051d4b/tenor.gif)

It may be but a small consolation that this irony was not lost on me.

> That means I now need to ~disembowel~ refactor beartype to do exactly the same thing. Global happiness ensues.

A part of me celebrates resolution. After reading 57e5e99, however, another part wonders with great trepidation, "What have I wrought?"

![The horror!](https://media.tenor.com/images/15caefeb77966d176473e26569515065/tenor.gif)

May we allpersevere with some sliver of hope that somehow the cure turns out not to be worse than the disease.

**Comment by posita** [comment]
I am reluctant to reopen this, but I _**think**_ restricting this behavior to methods that return `bool` is probably too narrow. Consider:

```python
from operator import add as op_add
from numbers import Integral, Real
from typing import Union
from beartype import beartype
class Numberwang:
  @beartype
  def __init__(self, value: Union[float, Real] = 0):
    self._value = int(value)
  @beartype
  def __int__(self) -> int:
    return self._value
  @beartype
  def __eq__(self, other: "Numberwang") -> bool:
    return self._value == other._value
  @beartype
  def __add__(self, other) -> "Numberwang":
    return Numberwang(op_add(self._value, other)) if isinstance(other, Integral) else NotImplemented
  @beartype
  def __radd__(self, other) -> "Numberwang":
    return Numberwang(op_add(other, self._value)) if isinstance(other, Integral) else NotImplemented
Integral.register(Numberwang)  # <- a lie, but a noble one for illustration
import pytest
assert Numberwang(1) + Numberwang(1) == Numberwang(2)
assert Numberwang(1) + 1 == Numberwang(2)
assert 1 + Numberwang(1) == Numberwang(2)
with pytest.raises(TypeError):
  Numberwang(27) + "That's Wangernumb!"  # <- this will roar
```

The last line of the above will result in a `beartype` violation:

```
beartype.roar.BeartypeCallHintPepReturnException: @beartyped Numberwang.__add__() return "NotImplemented" violates type hint 'Numberwang', as "NotImplemented" not <protocol "__main__.Numberwang">.
```

I tried fixing it myself by broadening the hint coercion in `cachehint.py` via #40, but surprisingly encountered this: https://github.com/beartype/beartype/pull/40#issuecomment-873682231.

**Comment by leycec** [comment]
**Brilliant!** I hadn't realized Mypy also accepted non-boolean binary dunder methods, although that's painfully obvious in hindsight.

I also realized there's a related issue with our current approach: it doesn't permit unannotated returns. Interestingly, mypy *does* permit that and is thus totally down with this wacky tabacky:

```
class CodeGoneWild(class):
    def __add__(self, other):   # <-- this is fine, bro
        return (
            42 if isinstance(other, CodeGoneWild) else
            NotImplemented
        )
```

So, we also need to explicitly handle the case of binary dunder methods lacking return annotations. Both of us deserve a well-deserved break and it's not even Monday. :sob:
