### ISSUE TITLE
[Future] Remove `beartype.typing.ByteString` under Python ≥ 3.14

### ISSUE THREAD

**Issue by JelleZijlstra** [beartype/beartype#386]
We deprecated `typing.ByteString` some time ago (https://docs.python.org/3.13/library/typing.html#typing.ByteString) and Python 3.14 will remove it, but `beartype.typing` unconditionally imports it.

I ran into this trying to run the beartype test suite with my PEP 649 implementation.

**Comment by leycec** [comment]
**Intended as working.** Suspicious, yet true. You are probably now narrowing your eyes in disgust. Allow me to now tediously explain. Actually, it's super-trivial. The `beartype.typing` subpackage is a one-to-one drop-in replacement for the standard `typing` module. If the standard `typing` module defines a public attribute, so does `beartype.typing` – *even if that attribute is deprecated,* crucially.

After all, a deprecated attribute is still an importable attribute. Right? The attribute still needs to exist... for the moment, anyway. That said, I'll make an internal `FIXME:` to remind myself to remove the `beartype.typing.ByteString` attribute under Python ≥ 3.14. For obvious reasons, that's not *quite* a pressing issue. Still, it's better to be prepared for a horrifying future than not prepare.

Flex it, @beartype. :muscle: :bear:

**Comment by JelleZijlstra** [comment]
Certainly not pressing, but would you accept a change to put the import in a try-except or behind an `if sys.version_info` guard? That would make it easier to test Python 3.14 earlier, which is important to me so I can check the impact of PEP 649 on beartype.

**Comment by leycec** [comment]
**Gah!** So sorry for the untimely delay, @JelleZijlstra. I've been putting out raging fires across the @beartype codebase like `Type[Self]` support at issue #389 and `multiprocessing` support at issue #382. Thankfully, the fires have now been quelled.

Both this issue and full-blown Python 3.13 conformance at issue #387 are now my highest priority. Optimistically, this means that @beartype should officially support Python 3.13 within a day or two. If you'd prefer to go hard on testing @beartype against PEP 649 even sooner, I'd be delighted to **accept absolutely any PRs you throw my way.** I mean... you're @JelleZijlstra. You're the `typing` guy. You have @beartype's full attention and my complete support. :smile:

**Comment by leycec** [comment]
**Resolved by 4b27fbb518cabad.** I've also taken the liberty of scheduling the removal of `beartype.typing.AnyStr` under Python ≥ 3.16 – which I see has also been similarly deprecated. Thanks for the heads up on all of this, mega `typing` boss @JelleZijlstra.

Onward to full-blown Python 3.13 conformance at issue #387. :partying_face:
