### ISSUE TITLE
[Feature Request] Support @sylvorg's officially introspectable third-party type hint factories

### ISSUE THREAD

**Issue by leycec** [beartype/beartype#388]
In [a comment to doco request #379](https://github.com/beartype/beartype/issues/379#issuecomment-2130618710), `typing` upstart @sylvorg independently invented a novel mechanism for defining what I now call **officially introspectable arbitrarily complex runtime-checkable third-party type hint factories** – which:

* Enable users to define **third-party type hint factories** (i.e., subscriptable objects defined in third-party packages that create and return new type hints when subscripted).
* Create **arbitrarily complex runtime-checkable type hints** (i.e., type hints capable of performing arbitrary logic when passed as the second parameter to the `isinstance()` builtin and are thus implicitly supported by *all* runtime type-checkers including @beartype).
* Play well with first-party `typing` introspection (e.g., `typing.get_args()`, `typing.get_origin()`) and are thus **officially introspectable.**

Moreover, this mechanism is astonishingly concise. Now introducing... *Sylvorg's Mechanism*:

```python
from types import GenericAlias
from typing import Generic, TypeVar

T = TypeVar("T")

class LazyAlias(GenericAlias):
    def __instancecheck__(self, value):
        return self.__args__[0](value)

class Lazy(Generic[T]):
    @classmethod
    def __class_getitem__(cls, *params):
        return LazyAlias(cls, *params)
```

**That's it.** That's Sylvorg's Mechanism. The proof is in the blood pudding:

```python
# Prove that Sylvorg's Mechanism is officially introspectable.
>>> from typing import get_origin, get_args
>>> get_origin(Lazy[lambda i: i < 1])
__main__.Lazy
>>> get_origin(Lazy[lambda i: i < 1]) is Lazy
True
>>> get_args(Lazy[lambda i: i < 1])
lambda i: i < 1

# Prove that Sylvorg's Mechanism is arbitrarily complex and runtime-checkable.
>>> isinstance(0, Lazy[lambda i: i < 1])
True
>>> isinstance(1, Lazy[lambda i: i < 1])
False
```

## Pretty Wild Stuff, Honestly.

I'm overwhelmed with emotion. Sadly, @beartype currently fails to support Sylvorg's Mechanism. Why? Because:

```python
>>> isinstance(Lazy[lambda i: i < 1], type)
False  # <-- wut u say
```

**So.** It comes to this. Clearly, Sylvorg's Mechanism produces:

* Type hints that are *not* classes.
* Type hints that are nonetheless passable as the second parameter to the `isinstance()` builtin. I didn't think that was even possible, honestly. I thought the *only* objects passable as the second parameter to the `isinstance()` builtin were:
  * Classes (types).
  * PEP 604-compliant new unions of types (e.g., `int | str`).
  * Tuples of types (e.g., `(int, str)`).

Clearly, the `isinstance()` builtin also accepts as the second parameter **isinstanceable objects** (i.e., arbitrary non-class objects whose classes define the `__instancecheck__()` dunder method).

## Here's Where We Get to the Bad Stuff

Currently, @beartype fails to support type hints that are **isinstanceable objects.** I'm pretty sure nobody's ever even tried that before. If they had, they would've complained and @beartype would've already supported isinstanceable objects by now. But nobody ever complained. Ergo, @sylvorg is probably the first upstart `typing` hellion to ever do this.

![](https://media1.tenor.com/m/WKe7TNAw9HkAAAAC/hail-the-victorious.gif)
<sup>all hail the @sylvorg for in his infinite wisdom he has given us the Sylvorg Mechanism</sup>

**Comment by sylvorg** [comment]
Thank you, thank you! I'll be here all night! ... Not really, I have to study for an Introductory Psychology midterm on Monday. _Fuck..._

😹

By the way, I'd completely forgotten generics aren't typically passable to `isinstance`. Whoops. 😅

Also, isn't: 
```python
>>> isinstance(Lazy[lambda i: i < 1], type)
False  # <-- wut u say
```
`False` for regular generics as well?

**Comment by sylvorg** [comment]
Also also, `LazyMeta` was for `is_bearable` specifically, so if `beartype` is update, it should no longer be necessary, right? 😅

**Comment by sylvorg** [comment]
Oh, and just for funsies:

```python
import collections.abc as cabc
import types
import typing

from abc import ABCMeta
from contextlib import suppress
from inspect import signature, Parameter, Signature, isgeneratorfunction
from types import GenericAlias, UnionType
from typing import _BaseGenericAlias, Any, ForwardRef, Generic, TypeVar

Annotation = type | _BaseGenericAlias | ForwardRef | GenericAlias | UnionType
# Annotation = str | type | _BaseGenericAlias | GenericAlias | UnionType


class GenericType(Generic[TypeVar("T")], metaclass=ABCMeta):
    @classmethod
    def __subclasscheck__(cls, C: Any) -> bool:
        with suppress(AttributeError):
            return issubclass(C, getattr(cabc, cls.__name__))
        with suppress(AttributeError):
            return issubclass(C, getattr(typing, cls.__name__))
        with suppress(AttributeError):
            return issubclass(C, getattr(types, cls.__name__))
        return False


def Type(__instancecheck__):
    Alias = type(
        f"{__instancecheck__.__name__}Alias",
        (GenericAlias,),
        dict(__instancecheck__=__instancecheck__),
    )
    return type(
        __instancecheck__.__name__,
        (GenericType,),
        dict(__class_getitem__=classmethod(Alias)),
    )


def normalize_signature(sig: Signature, t=Any):
    return sig.replace(
        return_annotation=t
        if sig.return_annotation is Parameter.empty
        else sig.return_annotation,
        parameters=(
            param.replace(annotation=t)
            if param.annotation is Parameter.empty
            else param
            for param in sig.parameters.values()
        ),
    )


@Type
def Callable(self, instance: Any) -> bool:
    with suppress(TypeError, ValueError):
        _sig = signature(instance)
        sig: Signature = normalize_signature(_sig)
        return (
            all(
                param.annotation is arg
                for param, arg in zip(
                    sig.parameters.values(), self.__args__[0], strict=True
                )
            )
            and sig.return_annotation is self.__args__[1]
        )
    return False


assert isinstance(lambda a, b: None, Callable[[Any, Any], Any])
assert isinstance(lambda a, b: None, Callable)
```

**Comment by leycec** [comment]
**ohnoes.** So sorry for the extreme delay! Life happened, the issue tracker exploded – *and then life happened some more.* But I really hope you passed your Introductory Psychology midterm and are well on your way to becoming a... Computer Psychoanalyst!? Yes, that too is probably now a thing. With the unfolding dawn of ASI, the prophesied time when even ASI becomes chronically depressed just by turning on the evening news is surely upon us.

As for the above, let's see here. I am now squinting furiously at the screen:

> Also, isn't:

```python
>>> isinstance(Lazy[lambda i: i < 1], type)
False  # <-- wut u say
```

> False for regular generics as well?

**Nope!** Behold:

```python
>>> from typing import Generic, TypeVar
>>> T = TypeVar('T')
>>> class MuhGeneric(Generic[T]): ...
>>> isinstance(MuhGeneric, type)
True
```

Honestly, that's kinda what concerns me about this whole thing. As far as I know, <sup>*so, not far*</sup> [PEP 3119 – Introducing Abstract Base Classes](https://peps.python.org/pep-3119) standardized both the `__instancecheck__()` and `__subclasscheck__()` dunder methods. Crucially, PEP 3119 does so only in the general context of **classes.** It's unclear whether the `isinstance()` and `issubclass()` builtins are actually intended to accept arbitrary objects as their second parameters or whether this is all just a long-standing bug that nobody's bothered to resolve in, like, *literally* twenty years.

I'm trending towards: "This is all just a long-standing bug that nobody's bothered to resolve in, like, *literally* twenty years." For obvious reasons, it'd be pretty Bad News™ for @beartype to support bugs. @beartype is trying (and mostly failing) to support the *opposite* of bugs. We're trying to crush bugs, not help them propagate a whole new colony of bugs that is now infesting every inch of your codebase.

## You Suck, @leycec!

You're not necessarily wrong, but... **hear me out.** Let's revisit the initial example that got this oddly shaped ball rolling:

```python
from types import GenericAlias
from typing import Generic, TypeVar

T = TypeVar("T")

class LazyAlias(GenericAlias):
    def __instancecheck__(self, value):
        return self.__args__[0](value)

class Lazy(Generic[T]):
    @classmethod
    def __class_getitem__(cls, *params):
        return LazyAlias(cls, *params)

print(isinstance(0, Lazy[lambda i: i < 1]))
```

Technically, Python accepts that as valid by printing ``True``. Fine. That's fine. But what do linters and static type-checkers have to say about that? **Linters and static type-checkers hate that code, bro.**

Specifically:

* `pylint` emits the following linter warning on the `print(...)` line:

  ```
  isinstance-second-argument-not-valid-type: Second argument of isinstance is not a type
  ```

* mypy emits the following **unreadable fatal error** on the `print(...)` line:

  ```
  yolobro.py:15: error: Type expected within [...]  [misc]
  yolobro.py:15: error: The type "type[Lazy[Any]]" is not generic and not indexable  [misc]
  Found 2 errors in 1 file (checked 1 source file)
  ```

* `pyright` emits the following **much more readable fatal error** on the `print(...)` line:

  ```
  /home/leycec/tmp/yolobro.py
    /home/leycec/tmp/yolobro.py:17:21 - error: Second argument to "isinstance" must be a class or tuple of classes
      Generic type with type arguments not allowed for instance or class checks (reportArgumentType)
    /home/leycec/tmp/yolobro.py:17:26 - error: Expected type expression but received "(i: Unknown) -> Unknown" (reportGeneralTypeIssues)
  2 errors, 0 warnings, 0 informations 
  ```

So. It comes to this. Linters and static type-checkers hate Python. Even though Python *technically* accepts that as valid by printing ``True``, linters and static type-checkers insist that Python is dumb.

Python might be right – but linters and static type-checkers ultimately have the last say. In the sad world we live in, the IDE reigns supreme. And the IDE says: "This is badness. Stop the madness."

## You Still Suck, @leycec!

*...heh.* Maybe so – but the current approach isn't gonna fly. Let's find an alternative (and probably slightly longer) way of expressing this same idea **while still satisfying linters and static type-checkers.** :thinking:

**Comment by sylvorg** [comment]
Actually, I've been trying to come up with my own runtime type checking and dispatch system; obviously, it won't be `O(1)`, but still, better than nothing, I think. To that end I've overridden `isinstance` and `issubclass` and am currently in the process of adding every type from `typing`, `types`, and `collections.abc` that even remotely make sense. I'll post it here as soon as possible, though you may have to mark it as off topic, but at least I've got [nested] `TypeVars` working!

... So would overriding `isinstance` and `issubclass` work here too? 😅

**Comment by sylvorg** [comment]
Also, yes, the midterm went _very_ well, thank you for asking! 37/40! I'm on a roll, baby! 😹

**Comment by leycec** [comment]
> Actually, I've been trying to come up with my own runtime type checking and dispatch system...

:open_mouth: 

**Wowza!** That sounds *super* fun. The sad world that is Python QA could always use another general-purpose runtime type-checker. This once-crowded space is pretty empty at the moment. There used to be a metric *ton* of different runtime type-checkers. Over the slow grinding of time, they all bit-rot, fell over into the swamp, whimpered quietly to themselves, and then died. @beartype and `typeguard` are pretty much it, really. It is lonely when you walk alone.

Drop [the `/r/Python` subreddit](https://www.reddit.com/r/Python/) a line when you've pushed out your `0.1.0`, too! Social media is the Big Boss of open-source advertising.

**Comment by leycec** [comment]
**Gah!** This was *such* a fascinating concept – but IDEs, linters, and static type-checkers alike hate this concept. Python itself loves this concept, of course. I wish that was enough. I wish that I still had hair, too.

Let's reopen this if we ever figure out how to get this right in a standards-compliant way that satisfies everybody. By everybody, I mostly mean "IDEs, linters, and static type-checkers." It's *not* hard to satisfy runtime type-checkers. We permissively accept everything! But... *yeah.* As always, static analysis is the laggard that slows us all down.

After heaving a reluctant sigh, I quietly close this and pray for better days. :face_exhaling:

**Comment by sylvorg** [comment]
Ah, well; that's unfortunate. Being and to use `get_origin` and `get_args` would solve so many problems, especially since `__origin__` and `__args__` don't seem to cover everything...

**Comment by leycec** [comment]
**Totally agree.** The discrepancy between CPython itself and all of that *other* tooling is super-odd. Usually, CPython and tooling agree. Here, they hate each other's festering guts. I can only shake my head while grimacing, fam. :face_with_diagonal_mouth:

**Comment by sylvorg** [comment]
One day! \*shakes fist angrily at the sky\* One day! 😹

Until then, do you have any advice while I try to build my own type checker? I wonder if there's a way to tell mypy and other static type checkers to ignore `isinstance` and `issubclass` if overriding it won't work...

**Comment by leycec** [comment]
**Hmm...** Yeash, indeedy. The customary way to ~~maliciously lie to~~ gently persuade static type-checkers is with an `if` conditional testing the standard `typing.TYPE_CHECKING` magic boolean: e.g.,

```python
from typing import TYPE_CHECKING

# If the current submodule is being statically type-checked...
if TYPE_CHECKING:
    # Avoid defining __instancecheck__() and __subclasscheck__(),
    # because lies are the basis of a healthy society.
    class MuhClass(...):
        ...
# Else, the current submodule is being run by a Python interpreter.
else:
    class MuhClass(...):
        def __instancecheck__(...) -> bool:
            ...
        def __subclasscheck__(...) -> bool:
            ...
```

Of course, even that *probably* still won't help you with popular linters like `pylint` and `ruff`. Which is why it's generally best *not* to lie about everything. Of course, sometimes you just can't help but lie about everything.

Ideally, though, I'd *probably* consider an alternative solution that used the standard metaclass approach. It's usually best to "paint within the lines" – especially where type-checking is concerned. A core assumption of QA is that **QA is standards-compliant.** QA that violates standards isn't particularly useful... *to most users,* anyway. Why? Because nobody wants to think about QA. The world is complicated enough without QA tooling adding additional complications. QA should just work out-of-the-box, batteries-included, no-migraine-included.

That's kinda why @beartype blew up (in a good way) whereas competing QA software mostly just blew up (in a bad way). To the extent that @beartype "works," @beartype "works" out-of-the-box, batteries-included, no-migraine-included – and it does so in a mostly normal way that complies with mostly all existing PEP standards.

Wherever your own type-checker goes, it should *definitely* go for PEP-compliance. That's the First and Final Rule of Type-checking Fight Club: "Comply with standards or GTFO." So, I'm super-excited to see what you've invented over there. Blow our socks off! My socks could use being blown off. Frankly, I think they could use a wash too. :laughing:

**Comment by sylvorg** [comment]
Well, that's irritating; generics don't seem to play well with metaclasses, it seems, so you couldn't even inherit from one of the supported generic parents. Hmm...

I'll figure something out. Though I'll have to restructure my project first; it's technically a precursor to my other projects, which means it holds all the shared functions and classes that they use. That'll take a while, especially with school. I've already been working on them for a couple years now, and I'm starting to wonder what the point is. 😹
