### ISSUE TITLE
[Bug] Bizarre `beartype.roar.BeartypeHintOverridesException` under CPython 3.12.0 + Windows = :zipper_mouth_face: 

### ISSUE THREAD

**Issue by denballakh** [beartype/beartype#399]
Running this line of code: 
```py
import beartype
```
I get this:
```py
Traceback (most recent call last):
  File "...\_.py", line 2, in <module>
    import beartype
  File "...\Lib\site-packages\beartype\__init__.py", line 58, in <module>
    from beartype._decor.decormain import (
  File "...\Lib\site-packages\beartype\_decor\decormain.py", line 26, in <module>
    from beartype._conf.confcls import (
  File "...\Lib\site-packages\beartype\_conf\confcls.py", line 46, in <module>
    from beartype._conf.confoverrides import (
  File "...\Lib\site-packages\beartype\_conf\confoverrides.py", line 109, in <module>
    BEARTYPE_HINT_OVERRIDES_PEP484_TOWER = BeartypeHintOverrides({
                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\beartype\_conf\confoverrides.py", line 92, in __init__
    raise BeartypeHintOverridesException(
beartype.roar.BeartypeHintOverridesException: Recursive type hint override float: typing.Union[float, int] currently unsupported. Please complain on our friendly issue tracker if you feel that this is dumb:
    https://github.com/beartype/beartype/issues
```

Some info:
- `beartype                      0.18.5`
- `CPython 3.12.0`
- Windows 10

**Comment by leycec** [comment]
**lol.** Indeed, I know awfulness when I see awfulness. Tragically for everyone involved, the [50,000-line @beartype test suite currently passes under **CPython 3.12.4** + **Windows 10**](https://github.com/beartype/beartype/actions/runs/9689491432/job/26737837842). I can't replicate this, which means I can't resolve this. Well, I could *try...* But it's probably best not to poke around in the dark like a blind leper.

Would you mind trying these things, @denballakh:

1. **Try uselessly upgrading CPython.** CPython 3.12.0 is quite old. Who knows? It might work. It almost certainly won't. of course. Upgrading never does anything. But wishful thinking is all I've got, really. :sob: 
2. **Try uselessly installing the most recent live @beartype commit.** Obviously, *nobody* wants to play fast and loose with live @beartype commits. Nonetheless, it's worth a shot in the dark. Oh, who am I kidding!? There's no way this improves matters. But let's humour @leycec in his dotage:

```bash
pip install git+https://github.com/beartype/beartype.git@d5807967f10b7bce31bb093c9251c0492d58e309
```

**Comment by leycec** [comment]
**Possibly resolved by 3ce5ff0bee.** Honestly, your CPython 3.12.0 just seems kinda busted. I'd *strongly* advise upgrading to the newest version of CPython 3.12 as soon as feasible. Failing that, consider trying the newest commit on our `main` branch via:

```bash
pip install git+https://github.com/beartype/beartype.git@3ce5ff0bee43af66d74b603596c52c279aa82460
```

Please do let me know if you find joy with either of these. And thanks again for flying the friendly @beartype skies! :fly:

**Comment by denballakh** [comment]
1. installing latest version using your command fixed the problem
2. upgrading to 3.12.4 didnt break anything
3. installing `beartype==0.18.5` back caused the same problem

do it is not because my python is old, there was something wrong in `0.18.5`

**Comment by denballakh** [comment]
You probably forgot to remove this `print(...)` line: https://github.com/beartype/beartype/blob/main/beartype/_conf/confoverrides.py#L147
```py
>>> import beartype
>>> beartype.BeartypeHintOverrides(a=42)
HINT_OVERRIDE_RECURSION_REGEX: \[[^]]*\b'a'[^]]*\]
BeartypeHintOverrides({'a': 42})
```
I dont think users want to see stuff like `HINT_OVERRIDE_RECURSION_REGEX: \[[^]]*\b'a'[^]]*\]`

@leycec thank you for the quick fix anyway!

**Comment by leycec** [comment]
**Gah!** I did *totally* forget that. You're absolutely right. Thanks so much for the quick heads-up, @denballakh. I'll spin out a @beartype 0.19.0 beta 0 pre-release this weekend addressing this. *Green frog face for the win!* :frog:
