### ISSUE TITLE
[Bug] `joblib` + @beartype = `joblib` explodes :exclamation: 

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [beartype/beartype#405]
Hi!

Dear Bear, I really want badly beartype to work on my [project](https://github.com/thiswillbeyourgithub/DocToolsLLM/) but I'm running into issues that are **completely bonkers**.

There's somewhat a lot to unwrap so I'll speak bullets:
1. I was not able to reproduce the error using minimal code but I keep having this issue on my codebase
2. That's why I'm more coming for guidance / to tell you, than actually reporting a specific issue to pinpoint and fix. If you don't have the time or don't want to try to reproduce that's understandable but I would really like your input on how to avoid this.
3. My code uses a lot of dependencies but it seems 100% triggered by beartype, never happened without it, turns on and off immediately as soon as I use the beartype decorator.
4. As you can see [I have a env flag that i use to trigger beartype or not](https://github.com/thiswillbeyourgithub/DocToolsLLM/blob/dev/DocToolsLLM/utils/typechecker.py). Basically I couldn't make `beartype_this_package` work so I have a `@optional_typecheck` decorator on most of my functions, and depending on the env flag it will either be `beartype.beartype` or a `beartype in warn mode` or just return the func. Conveniently: this allows me to turn on or off the bug.
5. The issue is stemming from using this decorator on function that are already decorated with a joblib.Memory decorator. Basically you just `from joblib import Memory ; mem = Memory("my_cache_dir") ; chached_func = mem.cache(non_cached_func)`.
6. For some reason it always starts with [my _file_hasher][https://github.com/thiswillbeyourgithub/DocToolsLLM/blob/352ae000946f41d10734ed27dc3106f5494aae73/DocToolsLLM/utils/misc.py#L162) function. And if I workaround this function, it will happen further down the execution to other functions, usually in [loaders.py](https://github.com/thiswillbeyourgithub/DocToolsLLM/blob/dev/DocToolsLLM/utils/loaders.py). I'm guessing this is not important.
7. The actual error (well, part of it) is : the arguments to the cache function seems to have been "tuppelized": `{'doc": "thing"} -> ({"doc": "thing"},)`. BUT 1. it crashes, 2 it's not telling me there's a typing error but crashing. Usually with: `Wrong number of arguments for _file_hasher(abs_path: str, stats: List[int]) -> str:
     _file_hasher({'doc': "[a text]", 'q': '[a question]'}, ) was called`
8. The stacktrace traces it back to `File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/func_inspect.py", line 292, in filter_args`. I have joblib version 1.4.2 and beartype 0.18.5.
9. The issue for this function disappears if I use the joblib decorator on top of the beartype decorator. But it makes no sense for me to do that because it would reset all cache if you change the typechecking env flag.
10. More weirdly: the issue disappears also if I don't use the @optional_typechecker syntax but instead do `func = optional_typechecker(func)` which I can't at all explain and am pretty sure if caused by beartype's witchcraft.
11. The issue disappears too if I remove the joblib cache decorator, but that's not acceptable.
12. The issue happens wether I'm using `optional_typecheck = beartype.beartype` or `optional_typecheck = beartype(conf=BeartypeConf(violation_type=UserWarning))`
13. **But most absurdly : these function are actually never called**. For example _file_hasher is **only** called by `file_hasher` above it and if I add breakpoints / raise SystemExit / compelte nonsense / returns etc to file_hasher : I still get the issue at _file_hasher meaning that its own parent is never executed. I even tried renaming the functions in case it was a weird scope issue and it changed nothing.
14. The arguments are not even appropriate : the dict I get is not for _file_hasher at all. If I "workaround" file_hasher, the other cached functions that are crashing (which still have nothing to do with what I'm actually calling) receive the same exact argument, which is still not for them.
15. The issue does not happen straight away, it's like 15s in my run, after documents are retrieved by their embeddings.

There's a way to maybe reproduce it on your side but unfortunately the simplest way I found without taking too much of your time involves running in a way that actually needs _file_hasher, but the bug remaing the same.

If you want to try to reproduce, I can't find a better way than just trying my code with python 3.11.7 (didn't test other versions). Fortunately I made a version that hopefully works even without API keys:
* `pip install git+https://github.com/thiswillbeyourgithub/DocToolsLLM.git@dev`
* `DocToolsLLM summary --path "https://github.com/thiswillbeyourgithub/DocToolsLLM/tree/dev" --debug --modelname "testing/testing"`

Here's the full trace:
```
Error when loading doc with filetype url: 'Wrong number of arguments for _file_hasher(abs_path: str, stats: List[int]) -> str:
     _file_hasher(, path=https://github.com/thiswillbeyourgithub/DocToolsLLM/tree/dev) was called.'. Arguments: {'task': 'summarize', 'temp_dir': PosixPath('/home/USER/.cache/DocToolsLLM/file_load_b4e2971f-7d92-4580-a2f6-07e39c13ea51'), 'path': 'https://github.com/thiswillbeyourgithub/DocToolsLLM/tree/dev', 'filetype': 'url', 'file_hash': '919a0984e4d4b4c290b5'}
Line number: 250
Full traceback:
  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/utils/batch_file_loader.py", line 250, in load_one_doc_wrapped
    out = load_one_doc(**doc_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<@beartype(DocToolsLLM.utils.loaders.load_one_doc) at 0x799a69129760>", line 117, in load_one_doc

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/utils/loaders.py", line 316, in load_one_doc
    docs = load_url(**kwargs)
           ^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 577, in __call__
    return self._cached_call(args, kwargs, shelving=False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 483, in _cached_call
    args_id = self._get_args_id(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 616, in _get_args_id
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/func_inspect.py", line 292, in filter_args
    raise ValueError(

  File "/home/USER/.pyenv/versions/3.11.7/bin/DocToolsLLM", line 8, in <module>
    sys.exit(cli_launcher())
             ^^^^^^^^^^^^^^

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/__init__.py", line 77, in cli_launcher
    instance = DocToolsLLM(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^

  File "<@beartype(DocToolsLLM.DocToolsLLM.DocToolsLLM_class.__init__) at 0x799a691762a0>", line 593, in __init__

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/DocToolsLLM.py", line 403, in __init__
    self.loaded_docs = batch_load_doc(
                       ^^^^^^^^^^^^^^^

  File "<@beartype(DocToolsLLM.utils.batch_file_loader.batch_load_doc) at 0x799a77cdc680>", line 74, in batch_load_doc

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/utils/batch_file_loader.py", line 287, in batch_load_doc
    doc_lists = Parallel(
                ^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^

  File "<@beartype(DocToolsLLM.utils.batch_file_loader.batch_load_doc.load_one_doc_wrapped) at 0x799962402f20>", line 15, in load_one_doc_wrapped

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/utils/batch_file_loader.py", line 250, in load_one_doc_wrapped
    out = load_one_doc(**doc_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<@beartype(DocToolsLLM.utils.loaders.load_one_doc) at 0x799a69129760>", line 117, in load_one_doc

  File "/home/USER/Documents/Perso/Bordel/git_repository/DocToolsLLM/DocToolsLLM/utils/loaders.py", line 316, in load_one_doc
    docs = load_url(**kwargs)
           ^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 577, in __call__
    return self._cached_call(args, kwargs, shelving=False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 483, in _cached_call
    args_id = self._get_args_id(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/memory.py", line 616, in _get_args_id
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/USER/.pyenv/versions/3.11.7/lib/python3.11/site-packages/joblib/func_inspect.py", line 292, in filter_args
    raise ValueError(

Wrong number of arguments for _file_hasher(abs_path: str, stats: List[int]) -> str:
     _file_hasher(, path=https://github.com/thiswillbeyourgithub/DocToolsLLM/tree/dev) was called.
<class 'ValueError'>                                                       
                                                                           
--verbose was used so opening debug console at the appropriate frame. Press 'c' to continue to the frame of this print.
```

So please dear bear, would you please enlighten me on what **witchbonkeritchcraftery** you bears are doing to MY pythons that can explain *THAT*?

(Beartype rocks though.)

Thank you.

**Comment by leycec** [comment]
**Ho, ho, ho.** Absolute madness, huh? I'm all for absolute madness. In this case, I love this maddening issue, your fanatical attention to detail, and your successful use of levity in a disastrous maelstrom of anguish fabricated by @beartype.

Would you mind upgrading to the most recent @beartype `0.19.0rc0` pre-release and trying again? That pre-release contains related fixes for issues with:

* The standard `multiprocessing` package, which `joblib` internally uses.
* Bizarre decorator chaining scenarios, which *might* be relevant here.

Admittedly, this is unlikely to help. Upgrading never helps. Still, humour me. I beg this! :bow: 

Ultimately, this is probably the issue:

> The issue for this function disappears if I use the `joblib` decorator on top of the `beartype` decorator.

Right? Decorator chaining. It sounds like there might be a subtle issue in the `joblib` codebase... but maybe it's @beartype's fault after all. Or... maybe both `joblib` *and* @beartype are to blame. Decorators often hate each other. @beartype tries to play nicely – but sometimes the gloves come off.

What a sad issue. Cry, type-checking QA bear!

![](https://media1.tenor.com/m/vAHlOsfhWEcAAAAd/grizzly-we-bare-bears.gif)
<sup>*QA bear is sad and hugs a tree sadly*</sup>

**Comment by leycec** [comment]
*...heh.* Let's assume `beartype 0.19.0rc0` doesn't help you, which it probably won't. I now have a simple idea that should allow us to narrow down the culprit: is `joblib` to blame or is it me? Here's the idea. You will facepalm. In your package, temporarily:

* **Stop importing @beartype** (i.e., no more `from beartype import beartype` stuff anywhere).
* **Define a new placeholder `@beartype` decorator** implemented with the standard decorator pattern that just silently reduces to a noop: e.g.,

```python
# The dumbest decorator possible. Does "joblib" still hate *THIS* decorator?
from functools import wraps
def beartype(func):
    @wraps(func)
    def dumb_noop_wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return dumb_noop_wrapper
```

Right? Dumb decorator is dumb. But the point is that dumb decorator also exhibits issues with *other* third-party packages like `joblib`. How? By **reducing the signature of the user-defined function `func` that it wraps** to just the variadic arguments `*args*` and `**kwargs`. Most packages tolerate stuff like that. Some packages don't, because they hate signature changes. Hatred is real in this world.

My untested hypothesis is that **`joblib` hates all decorators including `@beartype`.** If this hypothesis is correct, then `joblib` should still fail with the exact same exception as above even *after* you replace the actual `@beartype` decorator with the dumb decorator defined above. Does that happen? Does `joblib` still fail? If so, the issue is `joblib`. If not, the issue is @beartype.

I'm chewing popcorn over here with bated breath.

![](https://media1.tenor.com/m/X0uJSBblnXAAAAAC/stephen-colbert-popcorn.gif)
<sup>*the 3d glasses help him debug better*</sup>

**Comment by thiswillbeyourgithub** [comment]
Hi! Thanks a lot for the quick reply! Quick as a bear I might say.

Well to our surprise upgrading ~~bearly~~ completely fixes the issue!

I did test your other suggestion though and nope, the issue does not exist if I use a noop decorator.

Thanks a lot for the quick help, do you have a rough ETA estimation for the next beartype release?

**Comment by leycec** [comment]
Great question is great. On the one hand, `beartype-0.19.0rc0` sorta *is* a valid public @beartype release; just require `dependencies = ["beartype >=0.19.0rc0", ...]` in your `pyproject.toml` and you'll be good to go right now. On the other hand, I *totally* get it. You'd feel safer with a full-blown non-pre-release like `beartype-0.19.0`, right?

In that case, here's the current soft blockers for @beartype `0.19.0`:

* PEP 602-compliant `ParamSpec(...).args` and `ParamSpec(...).kwargs` support at feature request #404.
* The new `beartype.door.infer_hint()` type hint inference API at feature request #403.

Both are in-progress and "nearly there." So, maybe another week? Let's go with that. One whole week till the release party! :partying_face:

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot a lot for the quick helpful reply and I really like your vibe :) happy week end!
