### ISSUE TITLE
[Docos] Document magical `__type_beartype__` property for resolving forward reference proxy types

### ISSUE THREAD

**Issue by jennydaman** [beartype/beartype#410]
I want to inspect the return type of a method of a `@beartype` decorated class. Without beartype, this is achieved using `typing.get_type_hints`. Beartype breaks things because it modifies the method to return `beartype._check.forward.reference.fwdrefmeta.BeartypeForwardRefMeta` instead of the forward-referenced return type. e.g.

```python
from beartype import beartype


@beartype
class Actual:
    def fun(self) -> "SomeReturnClass":
        pass

class SomeReturnClass:
    pass


def test_beartype_bug():
    assert typing.get_type_hints(Actual.fun)['return'] is SomeReturnClass
```

Pytest output:

```
Expected :<class 'tests.test_beartype_bug.SomeReturnClass'>
Actual   :<forwardref SomeReturnClass(__name_beartype__='SomeReturnClass', __scope_name_beartype__='tests.test_beartype_bug')>
```

Trying to call `BeartypeForwardRefMeta.resolve` didn't work:

```python
typing.get_type_hints(Actual.fun)['return'].resolve()
```

Give you

```
beartype.roar.BeartypeDecorHintForwardRefException: <forwardref BeartypeForwardRefABC(__name_beartype__=None, __scope_name_beartype__=None)> subclass <forwardref resolve(__name_beartype__='SomeReturnClass.resolve', __scope_name_beartype__='tests.test_beartype_bug')> not instantiatable.
```

Well, as a workaround I wanted to see whether it at least quacks like a duck. Sadly, no.

```python
import beartype
import dataclasses

@beartype
@dataclasses.dataclass
class Actual:
    actual_field: int

    def fun(self) -> "SomeReturnClass":
        pass


@dataclasses.dataclass
class SomeReturnClass:
    expected_field: str


def test_beartype_bug():
    field_names = set(f.name for f in dataclasses.fields(typing.get_type_hints(Actual.fun)['return']))
    assert field_names == {"expected_field"}
```

Pytest output:

```
Expected :{'expected_field'}
Actual   :{'actual_field'}
```

**Comment by jennydaman** [comment]
Here's a workaround:

```python
import importlib
import typing

from beartype import beartype


@beartype
class BeartypedClass:
    def bear_method(self) -> "DummyReturn":
        ...


class DummyReturn:
    pass


def beartype_workaround410(t):
    if '__name_beartype__' not in dir(t) or '__scope_name_beartype__' not in dir(t):
        return t
    module = importlib.import_module(t.__scope_name_beartype__)
    return module.__dict__[t.__name_beartype__]


def test_beartype_workaround_minimalcase():
    method_return_type = typing.get_type_hints(BeartypedClass.bear_method)['return']
    assert beartype_workaround410(method_return_type) is DummyReturn
```

**Comment by leycec** [comment]
*...heh.* Horrifying forward references defined as stringified type hints, huh? In truth, the current @beartype behaviour is more a feature than a bug. You're now thinking:

> "I hate @beartype."

I can't disagree. From @beartype's perspective, what @beartype is doing here is entirely reasonable. The forward reference proxies that @beartype produces are *only* intended to proxy calls to the `isinstance()` and `issubclass()` builtins. Why? Because those are the only things @beartype cares about, because those are the only things that runtime type-checkers care about: e.g.,

```python
from beartype import beartype

@beartype
class Actual:
    def fun(self) -> "SomeReturnClass":
        pass

class SomeReturnClass:
    pass

assert isinstance(SomeReturnClass(), Actual.fun.__annotations__['return'])
```

Shockingly, **that works.** The @beartype-specific `Actual.fun.__annotations__['return']` forward reference proxy successfully proxies the expected `SomeReturnClass` class passed as the second parameter to the `isinstance()` builtin.

Sadly, **that's all that works.** As you've discovered, @beartype-specific forward reference proxies currently do *not* proxy anything else. Could they? Maybe. No idea, honestly. Kinda never thought about it. Nobody's ever needed that before. I quietly dodged the issue... *until now.*

## `pyserde`, @beartype Begs You to Stop Punching It

Does `pyserde` need full-blown forward reference proxying, @yukinarit? If so, we can *definitely* thinking about exploding @beartype's current forward reference proxying to do all sorts of crazy stuff – like proxying method calls, attribute lookups, attribute setting, attribute deletion, and so on. Proxying gets *really* crazy *really* fast, though; it's non-trivial, error-prone, and not something @beartype wants to do unless it *really* has to.

Also...

```python
def beartype_workaround410(t):
    if '__name_beartype__' not in dir(t) or '__scope_name_beartype__' not in dir(t):
        return t
    module = importlib.import_module(t.__scope_name_beartype__)
    return module.__dict__[t.__name_beartype__]
```

**...this is the Road to Pure Hell.** Your intentions are pure, but so were Thanos'. The above workaround only works when the passed class is defined in global scope. Nested classes and classes defined in closures break that workaround over their knees. Instead, what you want to do is **explicitly access the `__type_beartype__` dunder property** on @beartype-specific forward references: e.g.,

```python
from beartype import beartype

@beartype
class Actual:
    def fun(self) -> "SomeReturnClass":
        pass

class SomeReturnClass:
    pass

assert Actual.fun.__annotations__['return'].__type_beartype__ is SomeReturnClass
```

That does exactly what you want. So...

## What's the Big Deal, Bro?

`__type_beartype__` is undocumented private black magic that I currently reserve the despicable right to rename, remove, or otherwise break at any time. Do you *really* need this sort of black magic, @jennydaman and/or @yukinarit?

If so, let's think deeply about this. Flaming dragons are breathing fire here. :dragon_face:

**Comment by jennydaman** [comment]
Thank you for the great explanation @leycec 

>  Do you really need this sort of black magic?

It’s not a need, only a want. It is something I expected to work, but doesn’t.

Here’s the situation: I’m trying to build a library called aiochris. It depends on pyserde, which depends on beartype. I don’t care much for beartype in particular, and to my knowledge, pyserde uses beartype in appropriate ways. Don’t blame @yukinarit! The bear-puncher is me.

Here’s what I’m actually trying to do: aiochris is a client library for a HTTP backend. I'll create a much simpler example using the Cat Fact API: https://catfact.ninja

```python
import requests


class CatFactClient:

    def __init__(self, url):
        self._url = url

    def get_breeds(self):
        res = requests.get(f'{self._url}/breeds')
        return res.json()

    def get_fact(self):
        res = requests.get(f'{self._url}/fact')
        return res.json()
```

Pretty simple, but I also want to add deserialization, return types, and maybe type-checking too. Here is a first and flawed attempt at deserialization and return types, without type-checking, using dataclasses:

```python
import requests
import dataclasses
from typing import TypeVar, Type


@dataclasses.dataclass(frozen=True)
class BreedList:
    data: list[dict[str, str]]
    first_page_url: str
    last_page_url: str
    next_page_url: str
    total: int


@dataclasses.dataclass(frozen=True)
class CatFact:
    fact: str
    length: int


T = TypeVar('T')


def deserialize(data: dict, t: Type[T]) -> T:
    field_names = frozenset(field.name for field in dataclasses.fields(t))
    kwargs = {
        k: v for k, v in data.items()
        if k in field_names
    }
    return t(**kwargs)


class CatFactClient:

    def __init__(self, url: str):
        self._url = url

    def get_breeds(self) -> BreedList:
        res = requests.get(f'{self._url}/breeds')
        return deserialize(res.json(), BreedList)

    def get_fact(self) -> CatFact:
        res = requests.get(f'{self._url}/fact')
        return deserialize(res.json(), CatFact)
```

Looks ok, but there is a lot of code repetition in the methods `get_breeds` and `get_fact`. We could use a helper function:

```python
def do_request(base_url: str, path: str, t: Type[T]) -> T:
        res = requests.get(f'{base_url}/{path}')
        return deserialize(res.json(), t)



class CatFactClient:

    def __init__(self, url: str):
        self._url = url

    def get_breeds(self) -> BreedList:
        return do_request(self._url, 'breeds', BreedList)

    def get_fact(self) -> CatFact:
        return do_request(self._url, 'fact', CatFact)
```

But, could we do any better? We could use a decorator to figure out the parameters for `do_request`, by reading the method's return type hint:

```python
class CatFactClient:

    def __init__(self, url: str):
        self._url = url

    @magic_http_decorator('breeds')
    def get_breeds(self) -> BreedList:
        ...

    @magic_http_decorator('fact')
    def get_fact(self) -> CatFact:
        ...
```

This is as perfect as the code can get. We are left with the hard part: what is the implementation of `magic_http_decorator`?

Well, `magic_http_decorator` needs to read the type hints of a given function, so it'll either have to use `typing.get_type_hints` or `fn.__annotations__`.  And this all works well. It works in situations where you need forward references too.

The cat facts API is too simple for my next example. Here's a fictional example which demonstrates the need for forward references. Suppose we had a bearific API which had endpoints like:

```
GET https://example.com/api/bear/1
{ "weight": 100.7, "link_to_fur": "https://example.com/api/bear/1/fur" }

GET https://example.com/api/bear/1/fur
{ "color": "brown", "link_to_owner": "https://example.com/api/bear/1" }
```

The API resources `Fur` and `Bear` link to each other, so a forward reference is necessary. Here's a hypothetical way we could code it up:

```python
class Fur:
    color: str
    link_to_owner: str

    @magic_http_decorator_linked('link_to_owner')
    def get_owner(self) -> 'Bear':
        ...

class Bear:
    weight: float
    link_to_fur: str

    @magic_http_decorator_linked('link_to_fur')
    def get_fur(self) -> Fur:
        ...


class BearificClient:
    def get_a_bear(self) -> Bear:
        res = requests.get('https://example.com/api/bear/1')
        return deserialize(res.json(), Bear)
```

Ok! That was all hypothetical. What would the real code look like?

- I would want to use pyserde with beartype for deserialization and type-checking.
- The `@magic_http_decorator` and `@magic_http_decorator_linked` decorators would need to inspect the return types of methods decorated by `@beartype`
- Forward references are necessary

**Comment by JWCS** [comment]
I like that idea of removing redundant parameterization by re-using the required/explicit function typing; tho it's a bit disappointing that the function typing can only be gotten after the function has been defined, not while it's being defined. 
In any case, the decorator bit is clever, and might actually get around your original problem. If I remember correctly (❓), beartype auto-decorators happen at the end of the decorator stack, so it can inspect the whole typing changes applied. Like below:
```
class Fur:
    color: str
    link_to_owner: str

    @beartype    # Implicit on import!
    @magic_http_decorator_linked('link_to_owner')
    def get_owner(self) -> 'Bear':
        ...
```
In this case, magic_decorator has access to the raw function, so you can do the ""normal""
```
def magic_decorator(*args, **kwargs): # Factory
    path = kwargs.get('path', args[0])
    def decorator(typed_fn):
      assert hasattr(typed_fn, SERDE_SCOPE) # Serde doesn't change types... just pollutes scope(s)??
      ret_t = typed_fn.__annotations__['return']
      def final_fn(*args, **kwargs):
        res = requests.get(f'{g_base_url}/{path}')
        return from_json(ret_t, res.json())
      final_fn.__annotations__ = typed_fn.__annotations__ # Don't actually know if this works
      return final_fn
   return decorator
```
No beartype machinations needed. (Tho, I write decorators once in a blue moon, so maybe there's supposed to be a wraps() or partial() in there somewhere...)

**Comment by jennydaman** [comment]
@JWCS I appreciate your input.

Sadly, for my use case I can’t move the `@beartype` decorator from the class to the method because where and how `@beartype` is used is an implementation detail of pyserde.

**Comment by JWCS** [comment]
Er, I mean, you don't have to beartype decorate anything. A class decorated with beartype (like serde does), recursively decorates the members... after they've already been decorated by whatever magic you want. 

But it is true, @leycec , that there doesn't seem to be a "nice" way to change the beartype fwdref back into a type; I've put an MRE below that seems to meet @jennydaman 's design goal. It is pretty close to working... but not quite. I think, ideally, instead of adding a beartype specific function to dereference, it'd be nice if there was a standard way to do so... I think part of the problem is that the only standard fwd ref resolver `typing.get_type_hints()`, as crummy as it is (doesn't take strings), doesn't trigger beartype to have to resolve the forward ref, like it later would when it actually needs to do something. Alternatively, if testing for and setting a possible type forward reference to `__type_beartype__` is the best way... then the below does work.

<details>
<summary>demo_serde_deco_magic.py</summary>

```python
#!/bin/env python
# demo_serde_deco_magic.py

# When the get_owner method is commented out, this runs; uncomment to break
# To unofficially fix, uncomment the if hasattr(ret_t, '__type_beartype__'): block

GET_DATA = {
"https://example.com/api/bear/1":
    '{ "weight": 100.7, "link_to_fur": "https://example.com/api/bear/1/fur" }',
"https://example.com/api/bear/1/fur":
    '{ "color": "brown", "link_to_owner": "https://example.com/api/bear/1" }',
}
class requests:
    @staticmethod
    def get(url):
        return GET_DATA[url]

from serde import serde
from serde.json import from_json, to_json
import typing

# magic ~
def magic_http_decorator_linked(link_field):
    def decorator(func):
        # Note: can't define ret_t here, as circular
        # forward type references maybe/are not yet defined
        def wrapper(self, *args, **kwargs):
            # Note: type is now defined, for normal types, and this resolves
            # the string forward reference to the actual type
            # (unlike func.__anotations__['return'] which is still a string)
            ret_t = typing.get_type_hints(func)['return'] # Type now defined
            url = getattr(self, link_field)
            res_json = requests.get(url)
            # Note: this breaks, for Fur.get_owner -> 'Bear'
            # globals['Bear'] = <class '__main__.Bear'>
            # ret_t = __annotations__['return'] =
            #   <forwardref Bear(__name_beartype__='Bear', __scope_name_beartype__='__main__')>
            # serde.compat.SerdeError: <forwardref BeartypeForwardRefABC(...)> subclass <forwardref Bear(...)> not instantiatable
            # Note, if you uncomment this, it works again... unofficially
            #if hasattr(ret_t, '__type_beartype__'):
            #    ret_t = ret_t.__type_beartype__
            return from_json(ret_t, res_json)
        wrapper.__annotations__ = func.__annotations__
        return wrapper
    return decorator

class BearificalliestClient:
    def get_a_bear(self) -> 'Bear':
        res_json = requests.get('https://example.com/api/bear/1')
        return from_json(Bear, res_json)

@serde
class Fur:
    color: str
    link_to_owner: str

    @magic_http_decorator_linked('link_to_owner')
    def get_owner(self) -> 'Bear':
        ...

@serde
class Bear:
    weight: float
    link_to_fur: str

    @magic_http_decorator_linked('link_to_fur')
    def get_fur(self) -> Fur:
        ...

def test_client(client):
    bear = client.get_a_bear()
    print('MyBear:', bear)
    fur = bear.get_fur()
    print('ThatFur:', fur)
    #owner = fur.get_owner()
    #print('FurBelongsToBear:', owner)
    #print('Bear == Bear:', to_json(bear) == to_json(owner))

def main():
    print('bearificalliest client')
    clientificalliest = BearificalliestClient()
    test_client(clientificalliest)

if __name__ == '__main__':
    main()

# demo_serde_deco_magic.py

```
</details>

**Comment by leycec** [comment]
**Wonderful discussion.** Thanks so much for the deep dive into your impressively concise use case that leverages metaprogramming to the hilt for fun and profit, @jennydaman. Like a genius named @JWCS before me, I agree that the decorator-based `@magic_http_decorator` approach is the RightWay™; it's concise, it's elegant, it's magical, and it preserves the Don't Repeat Yourself (DRY) maxim.

You can't ask for more than that in this world.

## I See a Simple Solution, I Upvote

Thankfully, I have a simple solution! It's so simple even baby @leycec could code it.

If I'm reading your `@magic_http_decorator` implementation correctly, @jennydaman, it seems that all `aiochris` *really* needs is for @beartype's forward reference proxies to additionally **proxy the `__call__()` dunder method.** The `return` statement of your `deserialize()` function expects the passed parameter `t` to be an instantiable type. For edge cases in which you annotate methods like `Fur.get_owner()` with stringified forward references, however, `t` is instead a non-instantiable @beartype-specific forward reference proxy: e.g.,

```python
# Most of this is fine and great, except for...
def deserialize(data: dict, t: Type[T]) -> T:
    field_names = frozenset(field.name for field in dataclasses.fields(t))
    kwargs = {
        k: v for k, v in data.items()
        if k in field_names
    }
    return t(**kwargs)   # <-- *BIG TROUBLE IN LITTLE API!* this breaks down, because "t" sadly isn't what you think it is
```

## Let's Do This for the Great Glory

If that's the *real* underlying issue, then our upcoming @beartype 0.19.0 release can trivially solve that for you by just proxying the `__call__()` method from the @beartype-specific forward reference proxy `t` to the underlying type referred to be that proxy. Proxying `__call__()` would *effectively* make @beartype's forward reference proxies instantiable in the way that you expect, @jennydaman.

That's how metaclasses work anyway, interestingly; when you define the `__call__()` dunder method on a metaclass, you're *actually* ["overriding" the `__new__()` and `__init__()` dunder methods on the class whose metaclass is that metaclass](https://stackoverflow.com/a/39363704/2809027). <sup>*...well, sort of, anyway. it's best not to think too hard about metaprogramming. my brain hurts already.*</sup>

For my sanity and yours, let's assume that's all `aiochris` needs. In that case, let's narrow the scope of this feature request a bit to avoid a summertime brain freeze. I can feel the migraine already! Woe is @beartype. :smiling_face_with_tear:

**Comment by jennydaman** [comment]
> let's assume that's all aiochris needs.

sadly, no.

To make my example easier to understand and accept, I wrote an implementation of `deserialize` using only stdlib. The actual use case in aiochris uses [`serde.from_dict`](https://yukinarit.github.io/pyserde/api/serde.html#from_dict) instead, which is much more complicated.

**Comment by leycec** [comment]
Complicated stuff, huh? It's true. Forward reference proxying is a bit of a wicked problem. If you really do need a general-purpose one-size-fits-all solution to "undo" forward references proxied by @beartype, the @JWCS approach is almost certainly what you want to do:

> Alternatively, if testing for and setting a possible type forward reference to `__type_beartype__` is the best way... then the below does work.

For simplicity, let's just run with the above `deserialization()` function. Of course, your actual `deserialization()` function is hellish and complex. But simplicity is the root of enlightenment:

```python
def deserialize(data: dict, t: Type[T]) -> T:
    field_names = frozenset(field.name for field in dataclasses.fields(t))
    kwargs = {
        k: v for k, v in data.items()
        if k in field_names
    }

    # !!!!!! NEW STUFF STARTS HERE !!!!!!
    # If the passed type is actually a @beartype-specific forward reference proxy
    # that refers to the desired type, dereference that proxy to obtain that type.
    t = getattr(t, '__type_beartype__', None) or t
    # !!!!!! NEW STUFF ENDS HERE !!!!!!

    return t(**kwargs)
```

**That's it.** The trivial one-liner `t = getattr(t, '__type_beartype__', None) or t` does everything you want. On the other hand...

> @leycec it sounds like this would be a hard problem to solve in beartype.

*...heh.* @beartype can do anything. No problem is too hard for autism. But I'm not quite sure what *exactly* you're trying to accomplish, honestly. If you'd like to provide an even harder minimal working example (MWE), I'd be happy to have a go at that.

If I were you, I'd just run with the above one-liner `t = getattr(t, '__type_beartype__', None) or t`. That works *now* without requiring any other third-party open-source devs – be it @beartype or `pyserde` – to do anything. That's key. We're all lazy and mostly unpaid here. The less users want us to do, the better for our binging of the next season of *The Expanse.*

> For my own sake, maybe I should version pin beartype in the meantime...

*...hmm.* Unsure how pinning would solve anything, but... sure! You do you, you know?

Personally, I've only ever hit disaster by pinning something. I try to do that as little as possible. Inevitably, pinning causes dependency conflicts throughout my workflows – if not today, then certainly tomorrow. Pinning today guarantees explosions tomorrow. :boom: 

> ...then make a PR to `pyserde` so that it can optionally not use @beartype?

*...heh.* @yukinarit is *probably* not gonna like that. Without @beartype, there is no validation of (de)serialized data – or less validation, anyway. Would you trust unvalidated (de)serialized data? I wouldn't, generally speaking. "Trust in nothing" is the safest policy, both in life and in software. But... sure! You can hash that out with @yukinarit if you feel there's a demonstrable use case there. You do you and what's best for you.

Thanks again for this fascinating issue, @jennydaman. I'm kinda unclear whether there's something here for @beartype to do or not. Maybe just document that currently undocumented `__type_beartype__` magic property? Sure. That's reasonable. Can't go wrong with a little more documentation.

**Comment by jennydaman** [comment]
@leycec yup, `getattr(t, '__type_beartype__', None) or t` works great. It would be awesome if `__type_beartype__` could be considered "stable" and "documented" or whatever.

Many thanks for your time and thoughts!

**Comment by leycec** [comment]
> It would be awesome if `__type_beartype__` could be considered "stable" and "documented" or whatever.

**You got it!** It's officially official now. I've revised the `__type_beartype__` docstring to note that **(A)** it's now officially supported as of the upcoming @beartype 0.19.0 *and* **(B)** guaranteed to be stable and publicly available across *all* newer versions.

Thanks again for all the API fun. I'll leave this open until I've fully documented this at `https://beartype.readthedocs.io`. Until then, best of luck with `aiochris` and all the glorious stuff you're doing there. High fives all around, Bear Squad. :hand: :bear:  :hand:
