### ISSUE TITLE
[Release Begging] Please Gods, Release @beartype 0.19 Already

### ISSUE THREAD

**Issue by WeepingClown13** [beartype/beartype#420]
Hi,

First of all, I see the v0.19.0rc0 tag. Great! And thanks for your hardwork :)
Now, the issue at hand. I try to keep up with the beartype releases in Debian by packaging the latest available ones. The case now is that there are several mypy errors for v0.18.5, which I notice are gone in the current HEAD of the repo (d9b64e20 as I type it). The issue is that since the debian beartype package currently fails to build (since tests are enabled in build time), there is a [Release Critical bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077404) for it and it will be removed from Debian testing in less than two weeks. I could package the release candidate version from the tag (which still has one mypy error but is patchable ig), but I prefer to have the stable versions if possible.

So, all things considered, is expecting the 0.19.0 update (very) soon a good idea?
Hasta la vista until I am back again, and I'll be.

**Comment by JWCS** [comment]
@leycec At the sheer volume of code added since 0.19.0.rc0, you might want to quickly release an rc1, just in case, to have time to put out any discovered fires, and then just call it good enough for 0.19.0. There's plenty enough bugfixes in there to justify.

**Comment by leycec** [comment]
**Yikes.** Super-bad Debian breakage that is now costing @beartype users and making everything look bad, huh? This is all on me. I am perfectionism incarnate – which is to say "pretty dumb."

Clearly, I should just ship @beartype 0.19.0 already. There are two soft blockers:

* Bug #414. I *hate* leaving open known bugs in a QA tool, which is all about crushing bugs. But nobody else has hit this bug and probably nobody else ever will. It's *pretty* edge case. Maybe I'll just pretend a bug doesn't exist and ship 0.19 as is anyway. :yawning_face: 
* Feature request #403. Type hint inference is *soooooo* close to being perfect. I've finished everything except **tensor type hint inference,** which is partially implemented but entirely untested. That's... not great. Tensor type hint inference was kinda the whole point, too. I'd *really* like to hack on this one for another few days before churning out @beartype 0.19.0rc1. Bear with my perfectionism, bear bros. I beg this.

Everybody's right about everything. Free time, where art thou, free time!?

@WeepingClown13: How tight of a deadline are we talking here? If I hack on #403 this weekend and release @beartype 0.19.0rc1 by next Wednesday, would that give you enough time to ship @beartype 0.19.0rc1 before it gets pulled from Debian testing? Would Monday be better? Do I even know what I'm talking about anymore? *The answer to all these questions will surprise me.*

**Comment by WeepingClown13** [comment]
Well, the short answer is that I prefer you do it your way. The package is supposed be removed from Debian testing on Aug 27, but I can simply upload the latest version to Debian unstable after that and once fine it'll just migrate back to testing. So technically speaking, there is no reason to rush you, per se. Afterall, cleaner upstream means less or no patching downstream for me. So go ahead with your plans and we'll cross that bridge when we get there? If anything, thanks for being responsive! If you do an rc1 now, I could still package that if need be anyway.

All that said, I'd still love it if it's ready before the removal, but as mentioned, that's no reason for you to rush it.

**Comment by leycec** [comment]
**Aww!** You're *so* nice, @WeepingClown13 – even after I callously pushed back against #421 due to being a bad dude dev. As always, thanks for being so accommodating of my cray-cray. Still...

...*it's time.* I like rushing. Rushing is fun! I haven't rushed in awhile. Let's get the blood pumping and rebrand this an "agile sprint." The finish line is in sight. I can do this. Bear bros, I can do this.

![](https://media.tenor.com/tIeWl8uK6FIAAAAM/taking-deep-breaths-dr-randall-mindy.gif)
<sup>*the @beartype 0.19.0 release cycle goes pear-shaped in a dilapidated truck stop bathroom*</sup>

**Comment by leycec** [comment]
**mic drop.** Type hint inference via feature request #404 is now *fait accompli.* This was the final blocker for 0.19.0rc1. We are good to go. Engines are squealing. Rubber is burning. The light is green. Some guy in a chequered NASCAR jumpsuit is waving a flag.

I choose to believe I'll release 0.19.0rc1 by... Monday evening? Let's *gooooooooooooooooo,* fam.

**Comment by WeepingClown13** [comment]
leysec gets things done in a sec... there we go..... *insert roaring noices*

**Comment by leycec** [comment]
**We be doin' this.** @beartype 0.19.0 drops tomorrow. We quietly put this venerable discussion to bed.

May the @beartype 0.19.0 release cycle be remembered only for what it has given us – not how bug-filled, overdue to the breaking point, and derailed by BeartypeAI™ hype it truly was. :rofl:

**Comment by WeepingClown13** [comment]
@leycec managed to notice this only earlier but 0.19.0 is [now in debian unstable](https://tracker.debian.org/news/1570331/accepted-python-beartype-0190-1-source-into-unstable/) :) (will take some time for the built binaries to be available)

**Comment by leycec** [comment]
**Tremendous!** Thanks so much for your gruelling devotion to the Debian ecosystem. Ubuntu – and thus my wife, who *really* loves Kubuntu perhaps more than is healthy – depends on you. We all appreciate it so much. :hugs:

**Comment by WeepingClown13** [comment]
Haha, **thank you** for being the really understanding and co-operative upstream you are. Thanks to you I barely have downstream work :)
