### ISSUE TITLE
Beartype needs a badge

### ISSUE THREAD

**Issue by posita** [beartype/beartype#44]
This is the most urgent issue in the backlog, _obviously_.

Consider this 100% hand-crafted, artisan, free-range, gluten free, non-GMO, certified organic, naturally essenced <sup>because "essence" [is a verb now](https://www.gocomics.com/calvinandhobbes/1993/01/25), apparently</sup> prototype made with love  and care using the [shields.io API](https://shields.io/#your-badge):

- [![Bear-ified™](https://img.shields.io/badge/%F0%9F%91%8C%F0%9F%90%BB-Bear--ified%E2%84%A2-dead7f)](https://github.com/beartype/beartype)
  - `[![Bear-ified™](https://img.shields.io/badge/%F0%9F%91%8C%F0%9F%90%BB-Bear--ified%E2%84%A2-dead7f)](https://github.com/beartype/beartype)`

_[insert preferred, "fixed it for ya", "hold my beer", or just plain "boom" meme here]_

**Comment by posita** [comment]
To try it on for size, see the top of [this README from an upcoming release](https://github.com/posita/dyce/blob/posita/0/try-beartype/README.md).

**Comment by leycec** [comment]
**OMFG.** My wife and I collectively lmao-ed hard and then high-fived your shapeless avatar. Is... is [that an Atari-era anvil](https://avatars.githubusercontent.com/u/222581?v=4), by the way? I'm pretty sure I shot that to increase my score multiplier in *Centipede.* The details are hazy.

> naturally essenced <sup>because "essence" is a verb now, apparently</sup>

Srlsy. I lol-ed. Verbing essencing really is something the cosmeceutical industry would do, if they haven't already, which they probably have.

You receive an additional score multiplier for the hidden Bill Watterson URL. I didn't know what I was clicking on and suddenly got bludgeoned by a retro wave of 80's childhood nostalgia, which is the best and only kind I have.

> Hobbes: "Maybe we can eventually make language a complete impediment to understanding."

*mic drop*

But this:

![Bear-ified](https://camo.githubusercontent.com/171147e695ae70e8bf31e082a89be4420dcdf35338f109adfbc7389d78eb6ed0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2546302539462539312538432546302539462539302542422d426561722d2d69666965642545322538342541322d646561643766)

...my wife and I and our Bengal and Maine Coon cats *looooooove* it. The comforting pastel palette. The adorable yet stern bear face that commands respect even as it confers profound QA relief. The *OK!* hand sign that is the Transnational Beartype Seal of Quality™.

You have outdone even your previous Corinthian heights of headiness. I actually have the *perfect* place for this, assuming you're of sound mind, stout heart, and able body: [the hidden `beartype-assets` repo](https://github.com/beartype/beartype-assets)!

Yes, friends; it exists. Just in case shields.io ever destroys their business model, I'd love to preserve your ostensible genius in a new `badge/` subdirectory [resembling the existing `banner/` subdirectory of that repo](https://github.com/beartype/beartype-assets/tree/main/banner).

I'm delighted to do the heavy lifting myself; alternately, [perhaps you'd prefer to submit a PR there?](https://github.com/beartype/beartype-assets/pulls) You don't have to, of course. You've already gone above and beyond the call of the wild here. But... you know. You can, if you like. :wink: 

We should also stuff your painstaking brilliance into our trauma-inducing `README.rst` somewhere – maybe [immediately after `pip` and `conda` installation instructions in our *Install* section](https://github.com/beartype/beartype#install), maybe? Let us contemplate the mysteries of the Universe together.

**Comment by posita** [comment]
[Done](/beartype/beartype-assets/pull/4) and [done-ish](/beartype/beartype/pull/46), at least in draft forms appropriate for review and feedback.

Regarding my avatar, it was [GitHub's default Identicon](https://github.blog/2013-08-14-identicons/) (c. 2013), but it's funny you should mention Centipede. For years those evoked memories of Space Invaders for me. I don't know whether to laugh or cry (or both) seeing [this particular treatment](https://games.aarp.org/games/atari-centipede) of our shared nostalgia.
