### ISSUE TITLE
Unexpected and unconsistent behaviour of @beartype in nested type-checking

### ISSUE THREAD

**Issue by Fedezzab** [beartype/beartype#468]
Hi,
I want to say upfront that I've just started using beartype, so I apologize if I'm bringing up an issue that's already known.

I stress-test a bit the decorator `@beartype` to see whether or not it can deal with non trivial case occurring in real-case scenario. I found an unexpected behaviour when validating an input which is expected to be a list of tuples, each of them composed by two array from numpy.

This is what happen:

```
from numpy import array, ndarray
from beartype import beartype



@beartype
def dumb_func(input_data: list[tuple[ndarray, ndarray]]):
    # do any computation with input data
    arr_00, arr_01 = input_data[0]
    return arr_00


input_data = [(array(1), array(1))]
print(dumb_func(input_data=input_data))
# Output: 1 <-- CORRECT, I expected this

wrong_input_data = [(1, 1)]
print(dumb_func(input_data=wrong_input_data))
# Error: beartype.roar.BeartypeCallHintParamViolation: .... <-- CORRECT, since (1, 1) is not on the form (ndarray, ndarray)

more_complicated_wrong_data = [(array(i), array(i)) for i in range(1000000)] + [(1, 1)]
print(dumb_func(input_data=more_complicated_wrong_data))
# Output: 0 <-- WRONG, I did not expect this, since the last tuple (1, 1) it's not on the form (ndarray, ndarray)

another_wrong_data= [(array(i), array(i)) for i in range(10)] + [{"ciao": "amico"}]
print(dumb_func(input_data=another_wrong_data))
# Output: 0 <-- WRONG, I did not expect this, since the last element of the list is not even a tuple!
```
Is this scenario somehow expected due to an internal limitation of beartype? Did I miss something?

Consider I am using **Python 3.10.6** and **beartype 0.19.0**

**Comment by Fedezzab** [comment]
Understood from the documentation, thank you!

**Comment by leycec** [comment]
**...heh.** Apologies for any confusion, @Fedezzab. It's all true. To preserve performance, @beartype currently only randomly type-checks nested items. A future version of @beartype will let tweak this by linearly type-checking *all* nested items. But... *yeah.* Not quite there yet, I'm afraid. Maybe by late 2025 if all goes well? Let's choose to believe these words I am saying. :smile:
