### ISSUE TITLE
[BUG] `beartype.cave` does not explicitly reexport anything *le sigh*

### ISSUE THREAD

**Issue by antonagestam** [beartype/beartype#57]
We run mypy with [`--no-implicit-reexport`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport) to discover accidental imports from modules where a name is not publicly exposed. Beartype fails this `from beartype.roar import BeartypeException`, seemingly because its defined in `beartype.roar._roarexc` and isn't in contained in `beartype.roar.__all__`.

Is there a good reason that the exceptions are defined in an other module than what's exposed? If so, would you consider adding an `__all__` to make them explicitly reexported?

**Comment by antonagestam** [comment]
Noted your comment about Norwegian Black Metal in the other thread and decided I must include a depiction of an implicitly reexported name. Here it is. Look at it. Do you really want to import _that_!?

![image](https://user-images.githubusercontent.com/218551/136582013-348683d2-5aaf-4e7b-b4d0-c73e83e7a95f.png)

**Comment by leycec** [comment]
> Is there a good reason that the exceptions are defined in an other module than what's exposed?

**...none. None whatsoever.**

Very well. You deserve the uncomfortable truth. My fifteen year-old Vim setup coughs and then falls over when confronted with long Python files. I won't admit what "long" specifically means, because it's sad.

> If so, would you consider adding an `__all__` to make them explicitly reexported?

**Yes!** This is easier and safer than revising my fifteen year-old Vim setup. Even a Canadian man living in the ice wastes dares not trod on that holy ground.

**Comment by rsokl** [comment]
It looks like `beartype.cave` could use the same treatment

![image](https://user-images.githubusercontent.com/29104956/151020352-259176ec-735d-496e-9c00-5c7a4cd46fa3.png)


^ pyright is mad

**Comment by leycec** [comment]
`</gulp>`

You are not wrong, MIT Ryan. You never are. Let's reopen this under a fashionably late new name. Some bugs never stay squashed. :hiking_boot: :bug:

**Comment by antonagestam** [comment]
@leycec Note that mypy just changed behavior (unreleased) to be in line with other type checkers, and now consider `from mod import *` as an explicit re-export. Not sure if that would help here though, as the explicitness would just have to moved one level further down.

**Comment by leycec** [comment]
**Noice.** Thanks for the heads up, fellow aficionado of the great frozen wastes of the North! We applaud mypy conforming to community standards while hanging our head in snow-drenched shame that `beartype.cave` itself fails to conform to community standards.

[Some APIs you just can't reach.](https://www.youtube.com/watch?v=452XjnaHr1A)

**Comment by leycec** [comment]
**Resolved by 7cd3333...** *yet again.*

`beartype.cave` now explicitly reexports its public API. In theory, this means the entire @beartype API is now explicitly reexported and should pass `mypy --no-implicit-reexport` without complaint or shocking scandal.

In practice, you're our last line of defence. In @antonagestam we trust. :statue_of_liberty:
