### ISSUE TITLE
`autodoc` mocked modules in `sphinx` trigger `beartype` exceptions when building docs

### ISSUE THREAD

**Issue by jklaise** [beartype/beartype#61]
I've been experimenting with `beartype` and ran into this issue - basically mocking modules at runtime for `sphinx` doc building means that the types no longer correspond to what's expected, raising `beartype` exceptions: https://github.com/SeldonIO/alibi/pull/511#issuecomment-950861810.

This is not really a `beartype` issue (I don't think, although mocking could be more widespread in test suites which may trigger similar behaviour?) but I was wondering if there are any "best practices" around this so we can have our cake (mock modules for `sphinx` jobs) and eat it too (`beartype` not raising exceptions when that happens).

**Comment by leycec** [comment]
**Resolved by 722731a,** which *is* actually passing. Don't believe GitHub's lies.

Specifically, `@beartype` now conditionally detects when it *thinks* `autodoc` is running and silently reduces itself to a noop. This has been extensively tested on our end with [a surprisingly robust functional test that passes everywhere except Python ≥ 3.10](https://github.com/beartype/beartype/blob/main/beartype_test/a90_func/lib/test_sphinx.py), where [Sphinx's continued ill-advised usage of `distutils` raises deprecation warnings](https://github.com/sphinx-doc/sphinx/issues/9820). <sup>...so not our problem</sup>

I'll be officially releasing this tomorrow with `beartype 0.9.1`. This is critical stuff. It's time.

Thanks yet again for the generous consideration at SeldonIO/alibi#511, @jklaise. Whether `alibi` elects to continue hardening itself with `beartype` or opt instead for its crass older brother `pydantic`, you've helped us patch up a critical chink in our breastplate. I humbly wish you all the best with @SeldonIO... and beyond! :man_astronaut:
