### ISSUE TITLE
typing.ContextManager --- warned against but unactionable?

### ISSUE THREAD

**Issue by dycw** [beartype/beartype#74]
Hi @leycec , sorry to bother you again. 

I am one to treat warnings as errors, and thus PEP 484/585 require me to make migrations of the form

```python
from typing import Hashable
```

to

```python
from collections.abc import Hashable
```

However, there appears not to be an analogue of `typing.ContextManager`. Accordingly, what do I do in this situation?

Here's a minimal example:

```python
from contextlib import contextmanager
from collections.abc import Iterator
from typing import ContextManager
from warnings import filterwarnings, simplefilter
from beartype import beartype

filterwarnings("error")


@contextmanager
@beartype
def foo() -> Iterator[None]:
    yield


f = foo()
print("\n\n\nfoo is correctly typed: {}\n\n\n".format(f))


@beartype
def bar(cm: ContextManager[None]) -> None:
    pass


bar(f)
print("did not get here")
```

resulting in:

```
> python foo.py



foo is correctly typed: <contextlib._GeneratorContextManager object at 0x7f3104e4d3a0>



Traceback (most recent call last):
   <snip>
    warn(
beartype.roar.BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.ContextManag
er[NoneType] deprecated by PEP 585 scheduled for removal in the first Python version released
after October 5th, 2025. To resolve this, either drop Python < 3.9 support and globally replac
e this hint by the equivalent PEP 585 type hint (e.g., "typing.List[int]" by "list[int]") or s
ee this discussion topic for saner and more portable solutions:
    https://github.com/beartype/beartype#pep-484-deprecations
```

**Comment by TeamSpen210** [comment]
It's replaced by `contextlib.AbstractContextManager`.

**Comment by leycec** [comment]
> Hi @leycec , sorry to bother you again.

Oh, you're *never* a bother! You're among my most valued, respected, and applause-worthy users. Please keep your hard-hittin' issues a-comin'. After all, criticism only makes us stronger and more virile.

> However, there appears not to be an analogue of `typing.ContextManager`.

**Ah-ha!** This is your lucky dev evening. Thankfully, there *is* actually a one-to-one analogue of `typing.ContextManager`; it just goes by a completely different name and lives in a completely unexpected module.

To cleanly map between deprecated PEP 484 type hints and the equivalent non-deprecated PEP 585 type hints, see [the *"Implemented" section of PEP 585](https://www.python.org/dev/peps/pep-0585/#id6). Here's how the mapping works:

* For each type hint with a straightforward mapping, PEP 585 lists the PEP 585 type hint *without* listing the PEP 484 type hint (e.g., the PEP 585 type hint `collections.OrderedDict`, which deprecates the PEP 484 type hint `typing.OrderedDict`).
* For each type hint with a non-obvious mapping, PEP 585 lists the PEP 585 type hint first followed by the PEP 484 type hint as a `#`-prefixed comment (e.g., `collections.abc.Set # typing.AbstractSet`, implying that the PEP 585 type hint `collections.abc.Set` deprecates the PEP 484 type hint `typing.AbstractSet`).

Does that answer your concern, Derek?

**Comment by leycec** [comment]
**...sniped by Spence.** Remind me never to foolishly engage in a vicious eBay bidding war over Portal memorabilia with you, Spence. That is the day I would surely lose everything.

**Comment by dycw** [comment]
Ahh, thanks guys for the help. I could've sworn I did a poor man's `grep` (a.k.a., `Ctrl-F`) for `ContextManager`, but however that went wrong. In any case, onward with the `@beartype`ing! Confidence like no other!

**Comment by leycec** [comment]
I'm a simple CLI man. I see `rg`, I upvote with emoji. And thanks so much for all the `@beartype`-ing! You're flexing with some impressive real-world stats there. :muscle: 

Our own usage is spineless like a jellyfish by compare. The public shame I feel is real:

``` bash
$ rg '@beartype' **/*.py --stats
582 matches
582 matched lines
88 files contained matches
217 files searched
13504 bytes printed
1555310 bytes searched
0.001865 seconds spent searching
0.006695 seconds
```
