### ISSUE TITLE
desynchronization failure for IO[str] type hint and _io classes

### ISSUE THREAD

**Issue by NiklasRosenstein** [beartype/beartype#75]
A simple example to reproduce:

```py
import typing as t
from beartype import beartype

@beartype
def test(f: t.IO[str]) -> None:
  pass

with open(__file__) as fp:
  test(fp)
```

This results in

```
beartype.roar._BeartypeCallHintPepRaiseDesynchronizationException: @beartyped test() parameter f=<_io.TextIOWrapper name='test.py'...'> violates type hint typing.IO[str], but utility function raise_pep_call_exception() suggests this object satisfies this hint. Please report this desynchronization failure to the beartype issue tracker (https://github.com/beartype/beartype/issues) with this object's representation and accompanying exception traceback:
<_io.TextIOWrapper name='test.py' mode='r' encoding='UTF-8'>
```

Using `t.TextIO` as a type hint instead works.

If you open the file in `rb` mode instead, you also get the `desynchronization` error whereas `t.TextIO` as a type hint tells you that the argument violates the type hint.

**Comment by leycec** [comment]
*ohnoes*

We failed to adequately test `typing.{Text,Binary,}IO` with subscripted arguments. Now everything's on fire, the cat's squealing in terror, and Santa's skipping our house this year. This is that cat:

![humbug bahs](https://s7d2.scene7.com/is/image/BedBathandBeyond/93632847183339p?$460$&wid=515&hei=515)

**Comment by leycec** [comment]
**Ho, ho, ho.** Merry Christmas from GrumpyCat™, the unofficial @beartype mascot for all your festive QA needs this Yuletide season.

Commit 65a4a58 now resolves *both* of the issues you helpfully noted, Niklas... or should I say **Saint Nicholas**, as you are more commonly known this time of year? Specifically:

* `@beartype` now explicitly supports the `typing.IO[typing.Any]`, `typing.IO[bytes]`, and `typing.IO[str]` type hints.
* `@beartype` now raises the expected (mostly) human-readable exception when erroneously attempting to pass file handles opened in binary mode to `@beartype`-decorated callables annotated as accepting only file handles opened in text mode: e.g.,

``` python
>>> import typing as t
>>> from beartype import beartype
>>> @beartype
... def test(f: t.IO[str]) -> None:
...   pass
>>> with open(__file__, 'rb') as fp:
...   test(fp)
Traceback (most recent call last):
  File "<string>", line 10, in <module>
    test(fp)
  File "<string>", line 28, in test
  File "/home/leycec/py/beartype/beartype/_decor/_error/errormain.py", line 301, in raise_pep_call_exception
    raise exception_cls(  # type: ignore[misc]
beartype.roar.BeartypeCallHintPepParamException: @beartyped test()
parameter f=<_io.BufferedReader name='sompy.py'> violates type hint
typing.IO[str], as <_io.BufferedReader name='sompy.py'> not instance of
<protocol "beartype._util.hint.pep.proposal.utilpep544._Pep544TextIO">.
```

We rejoice with bourbon-laced eggnog. :egg: :tropical_drink:

We'll be dropping the `beartype 0.10.0` hammer containing both of these fixes later this month. Until then, please substitute (with our humble apologies and all the public shame we can muster):

* `typing.IO[bytes]` with `typing.BinaryIO`.
* `typing.IO[str]` with `typing.TextIO`.

Although this *technically* resolves your small-scale issues, there are still two unrelated larger-scale issues I didn't quite find the time or goodwill towards my fellow Germanic coder to solve:

1. `@beartype` still fails to support parametrizations of `typing.IO` (e.g., `typing.IO[typing.TypeVar('T', bytes, str)]`).
2. `@beartype` continues to incorrectly accept pass file handles opened in text mode to `@beartype`-decorated callables annotated as accepting only file handles opened in binary mode. I'll need to examine this a bit more closely, but it strangely seems that open text file handles actually satisfy the `typing.BinaryIO` protocol. Why, Guido!? Why!?!?

I curse my continued lack of spare clones for these lapses. If you care about either of these, <sup>*please don't care please don't care*</sup> loudly complain about them in a separate issue and we'll get you sorted out there, too. Phew! :sweat_smile: 

Nothing is easy that is worth doing. The old adages are all true.

**Comment by leycec** [comment]
**Heh.** I couldn't help myself, because this is Christmas. So, I just went ahead and supported everything related to `typing.{Binary,Text,}IO[...]` type hints. `beartype 0.10.0` will surely make all your I/O QA dreams come true... or your GitHub karma back.

Let me know if you hit any further snags, Niklas.
