### ISSUE TITLE
Mock objects and beartype check

### ISSUE THREAD

**Issue by Masoudas** [beartype/beartype#92]
Hello,

Recently I was trying to pass a mock objects to a function that is decorated with beartype, but I noticed the simple solutions that works with isinstance to work around the type is not going to work for beartype, as the following simple example demonstrates:

```
# a.py
class B:
  pass

class A:
    @beartype
    def my_method(self, name: B):
        pass


# test.py
class MockB:
  pass

class Test(TestCase):
      @patch("a.B", MockB, spec=True)
      def test_my_method(self):
            b = MockB()
           
           # This raises a beartype exception
           A().my_method(b)
```
   
So, any suggestion how I should pass my mock object so as not to face this issue?

**Comment by TeamSpen210** [comment]
You may want to look into the `unittest.mock` module, which has objects for dynamically mocking things in a more convenient way including support for tricking `isinstance()`. But if you want to do it yourself, what you do is add a `@property` for the `__class__` attribute, returning the original. Then `isinstance()` will pretend it's that class.

```py
class MockB:
    @property
    def __class__(self) -> type:
        return B
```

**Comment by Masoudas** [comment]
Thank you very much for the response @TeamSpen210 

Actually the above method does trick isinstance. But I was wondering why it doesn't do the same for beartype.

Anyways, I appreciate the help.

Good luck.

**Comment by leycec** [comment]
The glare off your brilliance is blinding me over here, @TeamSpen210. I'd better throw on some cheap knock-off Canadian snow-shades before I go... [**_snowblind_**](https://www.youtube.com/watch?v=J8B4BdAs0h4).

> But I was wondering why it wouldn't do the same for beartype.

You're in luck, @Masoudas! Since `@beartype` is entirely based on `isinstance()` under the hood, Spen's momentous hack gracefully generalizes to `@beartype` too:

``` python
>>> from beartype import beartype
>>> class B:
...     pass
>>> class A:
...     @beartype
...     def my_method(self, name: B):
...         pass
>>> class MockB:
...     @property
...     def __class__(self) -> type:
...         return B
>>> A().my_method(MockB())
>>> print('Can't believe that actually worked, bro.')
Can't believe that actually worked, bro.
```

Since that works shockingly well *and* just reduces to a trivial two-liner, I'll go ahead and inject this into our FAQ. @TeamSpen210: pretty sure that guy's dynamite in human form.

**Comment by leycec** [comment]
**[New FAQ entry is a-go](https://github.com/beartype/beartype#mock-types).** Gratuitous thanks to @TeamSpen210 for the two-liner that saves everything from a fiery dumpster.

Let us know if you hit any other obstacles to progress, @Masoudas. Until then, may the @beartype be with you!
