### ISSUE TITLE
Beartype 0.10.0 broken in python 3.9.1

### ISSUE THREAD

**Issue by joelid** [beartype/beartype#99]
Hello, I noticed that since the new update, we can no longer import `beartype` within python 3.9.1. This is the error I get:
```bash
>>> import beartype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlidin/.local/share/virtualenvs/test-beartype/lib/python3.9/site-packages/beartype/__init__.py", line 129, in <module>
    from beartype._decor.main import beartype
  File "/home/jlidin/.local/share/virtualenvs/test-beartype/lib/python3.9/site-packages/beartype/_decor/main.py", line 71, in <module>
    ) -> Union[BeartypeableT, BeartypeConfedDecorator]:
  File "/home/jlidin/.local/share/pyenv/versions/3.9.1/lib/python3.9/typing.py", line 262, in inner
    return func(*args, **kwds)
  File "/home/jlidin/.local/share/pyenv/versions/3.9.1/lib/python3.9/typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "/home/jlidin/.local/share/pyenv/versions/3.9.1/lib/python3.9/typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/home/jlidin/.local/share/pyenv/versions/3.9.1/lib/python3.9/typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/home/jlidin/.local/share/pyenv/versions/3.9.1/lib/python3.9/typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
```
This was tested with a clean virtual environment and only `beartype` installed. It did work with python 3.10.2 however. Is the new version only compatible with python 3.10?

**Comment by matanster** [comment]
I had encountered partial stack traces in python 3.9.7, I wonder if that's a known issue too.

**Comment by leycec** [comment]
> ...we can no longer import `beartype` within python 3.9.1.

*ohnoes*

The sky is falling and we have only this flimsy microlight wingsuit.

![wtfbro](https://www.outsideonline.com/wp-content/uploads/migrated-images_parent/migrated-images_82/dubai-wingsuit_fe.jpg?crop=16:9&width=960&enable=upscale&quality=100)

> Is the new version only compatible with python 3.10?

Thank Guido, **no.** We still retain full backward and forward compatibility with Python 3.6.0–3.10.2. At least, we *thought* we did. :grimacing: 

Our GitHub Actions-hosted continuous integration (CI) workflow tends to only test on the most recently patch version of each CPython release. For the Python 3.9 release cycle, this means CPython 3.9.9. CPython 3.9.1 is rather crusty around the ears at this point and possibly a security concern.

Still, **we absolutely want to support all possible CPython versions.** This includes CPython 3.9.1. In this case, the CPython 3.9.1-specific implementation of the standard `typing` module appears to suffer critical defects with respect to PEP 448-style unions and child type hints containing lists. `</sigh>`

## zomg

**Oh, yes.** This is actually [a known CPython 3.9.1 issue (#42965) subsequently resolved in CPython 3.9.2](https://bugs.python.org/issue42965). Badness erupts! Older CPython being fundamentally broken kinda makes us a *bit* less inclined to want to try resolve this on our end – especially as the only means of doing so seems to be revert to deprecated `typing.Callable[...]` type hints under Python 3.9.1. I shake my bald head.

Given that your `typing` implementation is critically cracked up, is there any chance you'd be willing to update to a newer CPython 3.9 release, @joelid?

> I had encountered warnings having only partial stack traces (and therefore not pointing at the offending line of code) in python 3.9.7...

That... *also* doesn't sound good. When you get a spare moment, please drop us a traceback bomb and we'll guillotine that bug with aplomb. :headstone:

**Comment by leycec** [comment]
With profuse apologies and a sweaty brow, I'm closing this kinda awkwardly.  Python 3.9.1 is broke. No one should use broke Python. But someone is. But someone using broke Python is outside our wheelhouse.

Maybe there's a demonstrably good reason for someone to use broke Python? If so, angrily bang on that **Reopen** button and we'll tactfully revisit this. Until then, please upgrade your Python to something less visibly broke.

May the fist-bumping bear be with you always. :fist_left: :bear: :+1:

**Comment by joelid** [comment]
That was definitively the issue @leycec. Python 3.9.1 was the default in our template, but perhaps we should change that because of the presented issues. We upgraded the python version, and now it works flawlessly. Greatly appreciated.

**Comment by leycec** [comment]
Oh, you're most welcome. Thank *you* and your fearless team for the willingness to meet @beartype halfway. As you intelligently suggest, migrating your template to even **Python 3.9.2** should permanently silence this issue for future generations of enterprising techbros and volunteer interns alike. :wink: 

Let's change the QA world together – one type hint at a time!
